/**
 * scripts/rephrase-gen/run-level.mjs
 *
 * Orchestrator for one level (spec §3 loop), SYNCHRONOUS Messages API transport
 * (Opus 4.8 everywhere, prompt caching on the frozen prefix). Usage:
 *   node run-level.mjs <L2|L3|L4|L5> [--target 150] [--max-rounds 120] [--batch 25]
 *     [--gen-conc 25] [--solve-conc 40] [--min-enforce 100] [--near-dup 0.68] [--resume]
 *
 * Per round: generateSync (N concurrent) → Gate A STRUCTURAL (hard fails) →
 * Gate B (5/5 blind-solver agreement, 5 seeded shuffles) → sentence-level
 * near-dup dedup → admission control. After target, a prune/refill loop runs the
 * Python scanner on the full level until DIVERGING FEATURES: NONE.
 *
 * Emits GEN-V4-Lx.sql ($hs$-quoted, is_published defaults false, topic NULL),
 * accepted-Lx.json, review-Lx.json (10 spread items), report-Lx.md, and a
 * per-round checkpoint-Lx.json (resume with --resume). Nothing is published.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import { OUT_DIR, contentWords, jaccard, addUsage, mergeTok, costUSD } from './lib.mjs';
import { RECIPES } from './recipes.mjs';
import { generateSync, warmGenCache } from './generate.mjs';
import { runScanner } from './gate-a.mjs';
import { solveSyncAll } from './solve.mjs';
import { getLevelItems, getLevelGoldens } from './db.mjs';
import {
  loadTruthRates, newAcc, addToAcc, removeFromAcc, cloneAcc,
  admits, divergences, badnessScore,
} from './features.mjs';

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

// ─── args ────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const level = argv[0];
if (!RECIPES[level]) {
  console.error('Usage: node run-level.mjs <L2|L3|L4|L5> [--target N] [--max-rounds N] [--batch N] [--resume]');
  process.exit(1);
}
const getArg = (name, def) => { const i = argv.indexOf(name); return i !== -1 ? Number(argv[i + 1]) : def; };
const hasFlag = (name) => argv.includes(name);
const TARGET = getArg('--target', 150);
const MAX_ROUNDS = getArg('--max-rounds', 120);
const COUNT = getArg('--batch', 25);            // items requested per round
const GEN_CONC = getArg('--gen-conc', 25);      // concurrent generation calls
const SOLVE_CONC = getArg('--solve-conc', 40);  // concurrent solver calls
const MIN_ENFORCE = getArg('--min-enforce', 100);
const NEAR_DUP = getArg('--near-dup', 0.68);    // stem content-word Jaccard ≥ this ⇒ near-duplicate
const RESUME = hasFlag('--resume');
const recipe = RECIPES[level];
const CKPT = resolve(OUT_DIR, `checkpoint-${level}.json`);

// ─── SQL dollar-quoting ─────────────────────────────────────────────────────
function dq(v) { const s = String(v); let tag = 'hs', i = 0; while (s.includes(`$${tag}$`)) tag = 'hs' + ++i; return `$${tag}$${s}$${tag}$`; }
const num = (v, fb) => (Number.isInteger(v) ? v : fb);

function buildInsertSql(items) {
  const cols =
    'original_sentence, correct_answer, distractor_1, distractor_2, distractor_3, ' +
    'difficulty_level, generation_batch, mechanism_1, mechanism_2, mechanism_3, ' +
    'proximity_1, proximity_2, proximity_3, transformations, relation_count, ' +
    'hard_word_count, recipe, topic';
  const batch = `GEN-V4-${level}`;
  const rows = items.map((it) => {
    const m = it.mechanisms || [], p = it.proximities || [];
    const trans = Array.isArray(it.transformations) ? it.transformations.join(',') : String(it.transformations || '');
    const hw = Number.isInteger(it.hard_word_count) ? it.hard_word_count : 'NULL';
    return '  (' + [
      dq(it.stem), dq(it.correct), dq(it.distractors[0]), dq(it.distractors[1]), dq(it.distractors[2]),
      recipe.difficulty, dq(batch), dq(m[0] || ''), dq(m[1] || ''), dq(m[2] || ''),
      dq(p[0] || ''), dq(p[1] || ''), dq(p[2] || ''), dq(trans), num(it.relation_count, 1),
      hw, dq(batch), 'NULL',   // topic NULL (no subject tagging)
    ].join(', ') + ')';
  });
  return (
    `-- ${batch}: ${items.length} rows, difficulty ${recipe.difficulty}, is_published=false (default).\n` +
    `-- Generated by scripts/rephrase-gen. Do NOT flip is_published — that is Lion's manual decision.\n` +
    `BEGIN;\nINSERT INTO restatement_questions (${cols}) VALUES\n` + rows.join(',\n') + ';\nCOMMIT;\n'
  );
}

// ─── Gate A: structural per-item ────────────────────────────────────────────
function gateAStructural(draft, round, counters) {
  let items = draft.slice();
  for (let pass = 0; pass < 2; pass++) {
    const res = runScanner(items, level, `r${round}-${pass}`);
    if (res.code === null) throw new Error(`Gate-A scanner failed to run:\n${res.stdout}`);
    if (!res.structuralItems.length) return items;
    const drop = new Set(res.structuralItems);
    const kept = items.filter((_, i) => !drop.has(i + 1));
    counters.gateA += items.length - kept.length;
    items = kept;
    if (items.length < 4) return items;
  }
  return items;
}

// ─── shared state ───────────────────────────────────────────────────────────
const existing = await getLevelItems(recipe.difficulty);
const existingCount = existing.length;
const needed = Math.max(0, TARGET - existingCount);
const real = loadTruthRates(level);
const goldens = await getLevelGoldens(recipe.difficulty);

const tok = { input: 0, cache_read: 0, cache_write: 0, output: 0 };
const acc = newAcc();
const usedStemSets = [];
for (const r of existing) { addToAcc(acc, r); usedStemSets.push(contentWords(r.stem)); }

let accepted = [];
let counters = { drafted: 0, gateA: 0, gateB: 0, dedup: 0, balance: 0, malformed: 0 };
const fooledLog = [];
let round = 0;

console.log(`\n=== ${level} (difficulty ${recipe.difficulty}, position ${recipe.position}) — target ${TARGET} ===`);
console.log(`Existing at difficulty ${recipe.difficulty}: ${existingCount} → need ${needed} new. Concurrency: gen ${GEN_CONC}, solve ${SOLVE_CONC}.`);

// ─── checkpoint resume ──────────────────────────────────────────────────────
if (RESUME && existsSync(CKPT)) {
  const ck = JSON.parse(readFileSync(CKPT, 'utf8'));
  accepted = ck.accepted || [];
  counters = ck.counters || counters;
  round = ck.round || 0;
  Object.assign(tok, ck.tok || {});
  for (const it of accepted) { addToAcc(acc, it); usedStemSets.push(contentWords(it.stem)); }
  console.log(`Resumed from checkpoint: ${accepted.length} accepted, round ${round}, $${costUSD(tok).toFixed(2)} spent.`);
}
function saveCheckpoint() { writeFileSync(CKPT, JSON.stringify({ round, accepted, counters, tok }, null, 2)); }

function tryAccept(item, relief) {
  const cw = contentWords(item.stem);
  if (usedStemSets.some((prev) => jaccard(cw, prev) >= NEAR_DUP)) return 'dedup'; // sentence-level near-dup ONLY
  const enforce = !relief && existingCount + accepted.length >= MIN_ENFORCE;
  if (enforce && !admits(acc, item, real)) return 'balance';
  usedStemSets.push(cw);
  addToAcc(acc, item); accepted.push(item);
  return 'accepted';
}

async function fillLoop() {
  let noProgress = 0;
  while (accepted.length < needed && round < MAX_ROUNDS) {
    round++;
    const relief = noProgress >= 4;
    let draft = [];
    try {
      const recentStems = accepted.slice(-12).map((x) => x.stem);
      const { items, usage } = await generateSync(recipe, { count: COUNT, round, recentStems, goldens, concurrency: GEN_CONC });
      mergeTok(tok, usage);
      draft = items;
    } catch (err) { console.log(`  round ${round}: generation error (${err.message}); retrying`); continue; }
    counters.malformed += COUNT - draft.length;
    if (!draft.length) { console.log(`  round ${round}: no valid drafts`); continue; }
    counters.drafted += draft.length;

    const passA = gateAStructural(draft, round, counters);
    if (!passA.length) { console.log(`  round ${round}: Gate A dropped the batch`); continue; }

    let solved;
    try {
      const { results, usage } = await solveSyncAll(passA, { concurrency: SOLVE_CONC });
      mergeTok(tok, usage);
      solved = results;
    } catch (err) { console.log(`  round ${round}: solver error (${err.message}); retrying`); continue; }

    const passB = [];
    for (const { item, result } of solved) {
      if (result.pass) passB.push(item);
      else { counters.gateB++; if (result.fooledMechanisms.length) fooledLog.push(...result.fooledMechanisms); }
    }

    let added = 0;
    for (const item of passB) {
      if (accepted.length >= needed) break;
      const r = tryAccept(item, relief);
      if (r === 'accepted') added++; else counters[r]++;
    }
    noProgress = added <= 1 ? noProgress + 1 : 0;
    saveCheckpoint();
    const ratio = tok.input + tok.cache_read ? Math.round((100 * tok.cache_read) / (tok.input + tok.cache_read)) : 0;
    console.log(`  round ${round}: A ${passA.length} → B ${passB.length} → +${added}${relief ? ' (relief)' : ''} (accepted ${accepted.length}/${needed}) [$${costUSD(tok).toFixed(2)}, cache-read ${ratio}%]`);
  }
}

/** Drop up to `max` accepted GEN items that most reduce full-level divergence. */
function pruneOffenders(max = 12) {
  const curBad = badnessScore(acc, real);
  const scored = accepted.map((it, idx) => {
    const t = cloneAcc(acc); removeFromAcc(t, it);
    return { idx, bad: badnessScore(t, real) };
  }).filter((s) => s.bad < curBad).sort((a, b) => a.bad - b.bad).slice(0, max);
  const dropIdx = new Set(scored.map((s) => s.idx));
  if (!dropIdx.size) return 0;
  const kept = [];
  accepted.forEach((it, idx) => { if (dropIdx.has(idx)) removeFromAcc(acc, it); else kept.push(it); });
  accepted = kept;
  return dropIdx.size;
}

// ─── run ─────────────────────────────────────────────────────────────────
const warm = await warmGenCache(recipe, goldens); addUsage(tok, warm); // prime the frozen-prefix cache once
console.log(`Cache warmed (frozen prefix): wrote ${warm.cache_creation_input_tokens || 0} tokens.`);

await fillLoop();

let prunePasses = 0;
let fullDiv = '(not scanned)';
while (accepted.length >= needed && prunePasses < 8) {
  const full = runScanner([...existing, ...accepted], level, 'checkfull');
  fullDiv = full.divergingLine;
  if (full.code === 0) break;
  if (!divergences(acc, real).length) { console.log(`  full scan non-zero but no numeric divergence; stopping. ${full.divergingLine}`); break; }
  const dropped = pruneOffenders();
  if (!dropped) { console.log('  could not prune further; stopping'); break; }
  counters.balance += dropped;
  console.log(`  prune pass ${prunePasses + 1}: dropped ${dropped} (${full.divergingLine}); refilling`);
  prunePasses++;
  await fillLoop();
  saveCheckpoint();
}

// ─── artifacts ──────────────────────────────────────────────────────────
writeFileSync(resolve(OUT_DIR, `accepted-${level}.json`), JSON.stringify(accepted, null, 2));
writeFileSync(resolve(OUT_DIR, `GEN-V4-${level}.sql`), buildInsertSql(accepted));

// Review window: 10 items spread across the level's stem-length range (not the first 10).
function pickSpread(items, k) {
  if (items.length <= k) return items.slice();
  const sorted = items.slice().sort((a, b) => a.stem.split(/\s+/).length - b.stem.split(/\s+/).length);
  const out = [];
  for (let i = 0; i < k; i++) out.push(sorted[Math.round((i * (sorted.length - 1)) / (k - 1))]);
  return out;
}
const review = pickSpread(accepted, 10).map((it) => ({
  stem: it.stem,
  options: [it.correct, ...it.distractors].map((text, i) => ({ text, correct: i === 0 })),
  correct_answer: it.correct,
  mechanisms: it.mechanisms, proximities: it.proximities, transformations: it.transformations,
  relation_count: it.relation_count, hard_word_count: it.hard_word_count,
}));
writeFileSync(resolve(OUT_DIR, `review-${level}.json`), JSON.stringify({ level, difficulty: recipe.difficulty, count: review.length, items: review }, null, 2));

const fooledTally = {};
for (const m of fooledLog) fooledTally[m] = (fooledTally[m] || 0) + 1;
const samples = pickSpread(accepted, 5);
const fmtSample = (it, i) => {
  const opts = [it.correct, ...it.distractors];
  return `**Sample ${i + 1}** (key = option 1)\n- STEM: ${it.stem}\n` +
    opts.map((o, k) => `- ${k + 1}) ${o}${k === 0 ? '  ← correct' : ''}`).join('\n') +
    `\n- mechanisms: ${(it.mechanisms || []).join(', ')} | proximities: ${(it.proximities || []).join(', ')} | transforms: ${(it.transformations || []).join(', ')}`;
};

const reachedTarget = accepted.length >= needed;
const gateBDenom = counters.drafted - counters.gateA;
const gateAPct = counters.drafted ? (100 * counters.gateA) / counters.drafted : 0;
const gateBPct = gateBDenom > 0 ? (100 * counters.gateB) / gateBDenom : 0;
const cacheRatio = tok.input + tok.cache_read ? (100 * tok.cache_read) / (tok.input + tok.cache_read) : 0;
const divergesNONE = fullDiv.includes('NONE');
const guardrail = (!divergesNONE || gateBPct > 25 || !reachedTarget);

const report =
  `# ${level} generation report (GEN-V4-${level})\n\n` +
  `- **Accepted (new):** ${accepted.length} / ${needed} (level total ${existingCount + accepted.length})\n` +
  `- **Drafts generated:** ${counters.drafted}\n` +
  `- **Gate-A discards (structural):** ${counters.gateA}  (${gateAPct.toFixed(1)}%)\n` +
  `- **Gate-B discards (blind solver):** ${counters.gateB}  (${gateBPct.toFixed(1)}% of structural survivors)\n` +
  `- **Dedup discards (near-dup):** ${counters.dedup}\n` +
  `- **Balance/prune discards:** ${counters.balance}\n` +
  `- **Rounds:** ${round}\n` +
  `- **Fooled-solver mechanisms:** ${Object.keys(fooledTally).length ? JSON.stringify(fooledTally) : 'none'}\n` +
  `- **Scanner divergence (full level pre-insert sim):** \`${fullDiv}\`\n` +
  `- **Cache-read ratio:** ${cacheRatio.toFixed(1)}%\n` +
  `- **API spend (this level):** $${costUSD(tok).toFixed(2)} — input ${tok.input}, cache_read ${tok.cache_read}, cache_write ${tok.cache_write}, output ${tok.output}\n` +
  (guardrail ? `- **⚠️ GUARDRAIL:** ${!reachedTarget ? 'did not reach target; ' : ''}${!divergesNONE ? 'divergence not NONE; ' : ''}${gateBPct > 25 ? `Gate-B ${gateBPct.toFixed(0)}% > 25%; ` : ''}recipe may need rework.\n` : `- **Guardrail:** OK (NONE divergence, Gate-B ${gateBPct.toFixed(0)}% ≤ 25%).\n`) +
  `\n## 5 samples (spread by stem length)\n\n` + samples.map(fmtSample).join('\n\n') + '\n';

writeFileSync(resolve(OUT_DIR, `report-${level}.md`), report);
saveCheckpoint();
console.log('\n' + report);
console.log(`DONE ${level}: GEN-V4-${level}.sql · accepted-${level}.json · review-${level}.json · report-${level}.md${guardrail ? '  ⚠️ GUARDRAIL TRIPPED' : ''}`);
