do $$ begin
  if not exists (select 1 from affix_items where target_word=$q$preheat$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$pre-$q$, $q$prefix$q$, $q$TIME_PLACE$q$, $q$לפני, מראש$q$, $q$preheat$q$, $q$The recipe says to __________ the oven for ten minutes before the bread goes in, so that it starts baking at the right temperature.$q$, $q$["reheat", "preheat", "heat", "heater"]$q$::jsonb, 2, $q$["reheat פירושו לחמם מחדש. re- מסמנת שוב — משהו שכבר היה חם והתקרר.", "נכון. pre + heat = לחמם מראש. הרמז: before the bread goes in.", "heat פירושו לחמם. זה קרוב, אבל המשפט מדגיש חימום לפני שהלחם נכנס — ולכן דרושה pre-.", "heater הוא שם עצם (מחמם, תנור חימום). אחרי says to דרוש פועל."]$q$::jsonb, $q$pre + heat = לחמם מראש. before בהמשך המשפט הוא הרמז ל-pre-; אם היה again, זה היה re-.$q$, 3, $q$shabbat batch 2026-09-05, family=TIME_PLACE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$postpone$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$post-$q$, $q$prefix$q$, $q$TIME_PLACE$q$, $q$אחרי$q$, $q$postpone$q$, $q$Because of the heavy snow, the organizers decided to __________ the race until the following weekend.$q$, $q$["prepare", "oppose", "position", "postpone"]$q$::jsonb, 4, $q$["prepare פירושו להכין. אין קשר לדחייה, ו-until the following weekend לא מתאים.", "oppose פירושו להתנגד. המארגנים לא מתנגדים למרוץ; הם מזיזים אותו בזמן.", "position הוא שם עצם (מיקום, עמדה). אחרי decided to דרוש פועל.", "נכון. post + pone (להניח) = לדחות, להניח למועד מאוחר יותר. הרמז: until the following weekend."]$q$::jsonb, $q$post + pone = לדחות (להניח אחרי). post- פירושה אחרי: postwar, postgraduate. until + זמן עתידי הוא הרמז לדחייה.$q$, 4, $q$shabbat batch 2026-09-05, family=TIME_PLACE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$preliminary$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$pre-$q$, $q$prefix$q$, $q$TIME_PLACE$q$, $q$לפני, מראש$q$, $q$preliminary$q$, $q$These figures are only __________; the complete results will be published once every laboratory has finished its analysis.$q$, $q$["primary", "permanent", "prelude", "preliminary"]$q$::jsonb, 4, $q$["primary פירושו עיקרי, ראשי. המשפט אינו מדבר על חשיבות אלא על שלב מוקדם לפני התוצאות המלאות.", "permanent פירושו קבוע. זה ההפך: הנתונים יוחלפו בתוצאות המלאות.", "prelude הוא שם עצם (פתיחה, הקדמה). אחרי are only דרוש שם תואר, לא שם עצם.", "נכון. pre + liminary (סף) = ראשוני, מקדים. הרמז: only... the complete results will be published once — יש עוד שלב."]$q$::jsonb, $q$pre + liminary = שלפני הסף, ראשוני. only + ___ ואחריו the complete results אומר שיש גרסה מוקדמת ומלאה — ו-pre- מסמנת את המוקדמת.$q$, 6, $q$shabbat batch 2026-09-05, family=TIME_PLACE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$careless$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-less$q$, $q$suffix$q$, $q$WITHOUT$q$, $q$בלי, נטול$q$, $q$careless$q$, $q$The report contained so many __________ mistakes, such as misspelled names and wrong dates, that the editor sent it back immediately.$q$, $q$["careful", "carefully", "careless", "care"]$q$::jsonb, 3, $q$["careful פירושו זהיר. טעויות זהירות אינן דבר הגיוני; שמות שגויים ותאריכים לא נכונים נובעים מרשלנות.", "carefully הוא תואר הפועל (בזהירות) ואינו יכול לתאר את שם העצם mistakes.", "נכון. care + less = חסר תשומת לב, רשלני. הרמז: misspelled names and wrong dates — טעויות של חוסר זהירות.", "care הוא שם עצם או פועל (דאגה, לדאוג). לפני mistakes דרוש שם תואר."]$q$::jsonb, $q$care + less = בלי תשומת לב. careful/careless הם הפכים; הדוגמאות במשפט (such as...) מגלות איזה כיוון נכון.$q$, 3, $q$shabbat batch 2026-09-05, family=WITHOUT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$effortless$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-less$q$, $q$suffix$q$, $q$WITHOUT$q$, $q$בלי, נטול$q$, $q$effortless$q$, $q$The champion made the difficult routine look __________, though she later admitted it had taken her years of daily training to master.$q$, $q$["effortful", "efforts", "effortless", "effort"]$q$::jsonb, 3, $q$["effortful פירושו מלא מאמץ. זה ההפך ממה שהאלופה גרמה לתרגיל להיראות.", "efforts הוא שם עצם ברבים (מאמצים) ואינו יכול לתאר את routine במבנה made X look.", "נכון. effort + less = חסר מאמץ, קל למראה. הרמז: though... years of daily training — נראה קל, אבל לא היה.", "effort הוא שם עצם (מאמץ). אחרי made... look דרוש שם תואר."]$q$::jsonb, $q$effort + less = ללא מאמץ. look + שם תואר (look easy, look effortless) מתאר איך משהו נראה — ו-though אחר כך חושף שהמציאות הייתה שונה.$q$, 5, $q$shabbat batch 2026-09-05, family=WITHOUT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$successful$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ful$q$, $q$suffix$q$, $q$WITHOUT$q$, $q$מלא ב-, עם$q$, $q$successful$q$, $q$After two failed launches, the third attempt was finally __________, and the satellite reached its planned orbit.$q$, $q$["successful", "succeed", "successfully", "success"]$q$::jsonb, 1, $q$["נכון. success + ful = מוצלח. הרמז: reached its planned orbit — לעומת two failed launches.", "succeed הוא פועל (להצליח). was finally succeed אינו מבנה תקין.", "successfully הוא תואר הפועל (בהצלחה) ואינו יכול לבוא אחרי was כתיאור של the attempt.", "success הוא שם עצם (הצלחה). אחרי was finally דרוש שם תואר."]$q$::jsonb, $q$success + ful = מוצלח. -ful הופכת שם עצם לתואר: careful, useful, powerful. failed לפני ו-reached אחרי מראים את המהפך להצלחה.$q$, 4, $q$shabbat batch 2026-09-05, family=WITHOUT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$comfortable$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-able$q$, $q$suffix$q$, $q$CAPABLE$q$, $q$ניתן ל־, בר־$q$, $q$comfortable$q$, $q$The new chairs are far more __________ than the old wooden benches, and students no longer complain about back pain.$q$, $q$["comfortably", "comfortable", "comfort", "comforting"]$q$::jsonb, 2, $q$["comfortably הוא תואר הפועל (בנוחות) ואינו יכול לתאר את the chairs אחרי are.", "נכון. comfort + able = נוח. הרמז: no longer complain about back pain.", "comfort הוא שם עצם (נוחות). אחרי far more דרוש שם תואר להשוואה.", "comforting פירושו מנחם, מרגיע — מתאר דבר שמנחם אדם עצוב, לא כיסא נוח."]$q$::jsonb, $q$comfort + able = נוח. more ___ than הוא מבנה השוואה שדורש שם תואר, ו--able היא הסיומת שיוצרת אותו.$q$, 3, $q$shabbat batch 2026-09-05, family=CAPABLE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$renewable$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-able$q$, $q$suffix$q$, $q$CAPABLE$q$, $q$ניתן ל־, בר־$q$, $q$renewable$q$, $q$Solar and wind power are __________ sources of energy because, unlike coal or oil, they are never used up.$q$, $q$["renew", "renewable", "renewal", "renewed"]$q$::jsonb, 2, $q$["renew הוא פועל (לחדש). לפני sources דרוש שם תואר.", "נכון. re + new + able = מתחדש, שניתן לחדש. הרמז: never used up — האנרגיה לא נגמרת.", "renewal הוא שם עצם (חידוש). renewal sources אינו צירוף תקין.", "renewed פירושו חודש (בעבר). זה מתאר משהו שכבר חודש פעם אחת, לא מקור שמתחדש תמיד."]$q$::jsonb, $q$re + new + able = מתחדש. שלוש שכבות: re- שוב, new חדש, -able ניתן ל-. unlike coal or oil הוא רמז לניגוד עם מקורות שנגמרים.$q$, 4, $q$shabbat batch 2026-09-05, family=CAPABLE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$remarkable$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-able$q$, $q$suffix$q$, $q$CAPABLE$q$, $q$ניתן ל־, בר־$q$, $q$remarkable$q$, $q$Her recovery was __________: doctors had expected months of rehabilitation, yet she walked out of the hospital within a week.$q$, $q$["remark", "remarked", "unremarkable", "remarkable"]$q$::jsonb, 4, $q$["remark הוא שם עצם או פועל (הערה, להעיר). אחרי was דרוש שם תואר.", "remarked פירושו העיר (בעבר). was remarked אינו מתאר את ההחלמה.", "unremarkable פירושו לא מיוחד, רגיל. זה ההפך מהחלמה מפתיעה כל כך.", "נכון. remark + able = ראוי לציון, יוצא דופן. הרמז: הרופאים ציפו לחודשים, והיא יצאה תוך שבוע."]$q$::jsonb, $q$remark + able = ראוי לציון, מרשים. -able לפעמים פירושה ראוי ל- ולא ניתן ל-: remarkable, admirable, notable. הניגוד expected months / within a week הוא הרמז.$q$, 6, $q$shabbat batch 2026-09-05, family=CAPABLE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$protection$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-tion$q$, $q$suffix$q$, $q$NOUN$q$, $q$סיומת שיוצרת שם עצם מפועל$q$, $q$protection$q$, $q$The thick walls of the old fortress offered excellent __________ against both cannon fire and the bitter winter winds.$q$, $q$["protect", "protective", "protected", "protection"]$q$::jsonb, 4, $q$["protect הוא פועל (להגן). אחרי excellent (שם תואר) דרוש שם עצם.", "protective הוא שם תואר (מגן). excellent protective בלי שם עצם אחריו אינו מבנה תקין.", "protected הוא פועל בעבר או תואר (מוגן). offered excellent protected אינו משפט תקין.", "נכון. protect + tion = הגנה. offered excellent ___ against דורש שם עצם, ו-protection against הוא צירוף קבוע."]$q$::jsonb, $q$protect + tion = הגנה. שם תואר (excellent) + ___ + against = שם עצם. חפשו את הסיומת שיוצרת שם עצם.$q$, 3, $q$shabbat batch 2026-09-05, family=NOUN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$improvement$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ment$q$, $q$suffix$q$, $q$NOUN$q$, $q$סיומת שיוצרת שם עצם מפועל (כמו -tion)$q$, $q$improvement$q$, $q$Teachers noticed a clear __________ in the students' reading speed after just six weeks of daily practice.$q$, $q$["improving", "improved", "improvement", "improve"]$q$::jsonb, 3, $q$["improving היא צורת -ing. a clear improving in אינו מבנה תקין.", "improved הוא פועל בעבר או תואר (משופר). a clear improved in אינו מבנה תקין.", "נכון. improve + ment = שיפור. a clear ___ in דורש שם עצם, ו-improvement in הוא הצירוף הקבוע.", "improve הוא פועל (לשפר). אחרי a clear דרוש שם עצם."]$q$::jsonb, $q$improve + ment = שיפור. -ment היא אחות של -tion: agreement, development, movement. a + תואר + ___ = שם עצם.$q$, 4, $q$shabbat batch 2026-09-05, family=NOUN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$destruction$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-tion$q$, $q$suffix$q$, $q$NOUN$q$, $q$סיומת שיוצרת שם עצם מפועל$q$, $q$destruction$q$, $q$The earthquake caused widespread __________ in the old quarter, where almost none of the buildings had been reinforced.$q$, $q$["destroy", "destructive", "destruction", "destroyed"]$q$::jsonb, 3, $q$["destroy הוא פועל (להרוס). אחרי caused widespread דרוש שם עצם.", "destructive הוא שם תואר (הרסני). widespread destructive בלי שם עצם אחריו אינו מבנה תקין.", "נכון. destroy → destruction = הרס. caused + שם תואר (widespread) + ___ דורש שם עצם, ו-none... reinforced מסביר את ההרס הנרחב.", "destroyed הוא פועל בעבר או תואר (הרוס). caused widespread destroyed אינו משפט תקין."]$q$::jsonb, $q$destroy + tion = הרס (destruction). שימו לב לשינוי השורש: destroy → destruct-ion, כמו describe → description. caused + תואר + ___ = שם עצם.$q$, 5, $q$shabbat batch 2026-09-05, family=NOUN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$journalist$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ist$q$, $q$suffix$q$, $q$AGENT$q$, $q$אדם שעוסק בתחום$q$, $q$journalist$q$, $q$The __________ spent three months interviewing witnesses before she published her article about the factory fire.$q$, $q$["journalism", "journalist", "journey", "journal"]$q$::jsonb, 2, $q$["journalism הוא שם עצם מופשט (עיתונאות). המקצוע אינו מבצע פעולות; האדם כן.", "נכון. journal + ist = עיתונאי. הרמזים: interviewing witnesses ו-she published — אדם.", "journey פירושו מסע. מילה אחרת לגמרי שרק מתחילה באותן אותיות.", "journal הוא שם עצם (כתב עת, יומן). כתב עת אינו מראיין עדים."]$q$::jsonb, $q$journal + ist = עיתונאי. she בהמשך המשפט מצביעה על אדם — ו--ist היא סיומת של אדם. -ism לעומתה היא התחום או ההשקפה.$q$, 3, $q$shabbat batch 2026-09-05, family=AGENT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$observer$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-er$q$, $q$suffix$q$, $q$AGENT$q$, $q$מי שמבצע את הפעולה$q$, $q$observer$q$, $q$Even a casual __________ could see that the two paintings had been made by different artists, so different were the brush strokes.$q$, $q$["observation", "observant", "observer", "observe"]$q$::jsonb, 3, $q$["observation הוא שם עצם (תצפית, הבחנה). תצפית אינה יכולה could see; דרוש אדם.", "observant הוא שם תואר (ערני, שם לב). אחרי a casual דרוש שם עצם, לא תואר נוסף.", "נכון. observe + er = מתבונן, צופה. הרמז: a casual ___ could see — אדם שמסתכל.", "observe הוא פועל (להתבונן). אחרי a casual דרוש שם עצם."]$q$::jsonb, $q$observe + er = צופה. -er היא הסיומת הנפוצה ביותר לאדם שעושה פעולה: teacher, writer, observer. could see דורש נושא שיכול לראות.$q$, 4, $q$shabbat batch 2026-09-05, family=AGENT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$pessimist$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ist$q$, $q$suffix$q$, $q$AGENT$q$, $q$אדם שעוסק בתחום$q$, $q$pessimist$q$, $q$My grandfather was a lifelong __________ who assumed that every new plan would fail, yet he was often pleasantly surprised.$q$, $q$["pessimist", "pessimistic", "optimist", "pessimism"]$q$::jsonb, 1, $q$["נכון. pessim + ist = פסימיסט, מי שמצפה לרע. הרמז: assumed that every new plan would fail.", "pessimistic הוא שם תואר (פסימי). אחרי a lifelong דרוש שם עצם.", "optimist פירושו אופטימיסט. זה ההפך: אופטימיסט מצפה שהתוכניות יצליחו.", "pessimism הוא שם עצם מופשט (פסימיות). was a lifelong pessimism אינו הגיוני — הוא אדם, לא תכונה."]$q$::jsonb, $q$pessim + ist = פסימיסט. a + תואר (lifelong) + ___ + who = שם עצם של אדם. המשך המשפט (would fail) קובע אם זה pessimist או optimist.$q$, 5, $q$shabbat batch 2026-09-05, family=AGENT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$apologize$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ize$q$, $q$suffix$q$, $q$VERB$q$, $q$סיומת שהופכת שם תואר לפועל$q$, $q$apologize$q$, $q$The manager was forced to __________ publicly after customers discovered that the sale prices were higher than the regular ones.$q$, $q$["apologetic", "apologize", "apologies", "apology"]$q$::jsonb, 2, $q$["apologetic הוא שם תואר (מתנצל). to apologetic אינו מבנה תקין.", "נכון. apolog + ize = להתנצל. הרמז: forced to + פועל, והמצב (מחירי מבצע גבוהים מהרגילים) מצדיק התנצלות.", "apologies הוא שם עצם ברבים (התנצלויות) ואינו יכול לבוא אחרי to כפועל.", "apology הוא שם עצם (התנצלות). אחרי forced to דרוש פועל."]$q$::jsonb, $q$apology + ize = להתנצל. forced to / had to / decided to — אחרי to תמיד פועל, ו--ize היא סיומת של פועל.$q$, 3, $q$shabbat batch 2026-09-05, family=VERB$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$recognize$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ize$q$, $q$suffix$q$, $q$VERB$q$, $q$סיומת שהופכת שם תואר לפועל$q$, $q$recognize$q$, $q$After twenty years apart, the two old friends did not __________ each other at first and walked past without a word.$q$, $q$["recognized", "recognizable", "recognition", "recognize"]$q$::jsonb, 4, $q$["recognized היא צורת עבר. אחרי did not דרושה צורת המקור: did not recognize.", "recognizable הוא שם תואר (ניתן לזיהוי). did not recognizable אינו מבנה תקין.", "recognition הוא שם עצם (זיהוי, הכרה). אחרי did not דרוש פועל בצורת המקור.", "נכון. recogn + ize = לזהות. הרמז: walked past without a word — לא זיהו זה את זה."]$q$::jsonb, $q$recogn + ize = לזהות. אחרי did not / does not / will not דרושה צורת המקור של פועל — בלי -ed ובלי -tion.$q$, 4, $q$shabbat batch 2026-09-05, family=VERB$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$strengthen$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-en$q$, $q$suffix$q$, $q$VERB$q$, $q$סיומת שהופכת שם תואר לפועל (כמו -ize)$q$, $q$strengthen$q$, $q$Engineers added steel cables to __________ the bridge, which had begun to sway dangerously in strong winds.$q$, $q$["strengthen", "strongly", "strong", "strength"]$q$::jsonb, 1, $q$["נכון. strength + en = לחזק. הרמז: added steel cables to + פועל — ו-sway dangerously מסביר למה צריך חיזוק.", "strongly הוא תואר הפועל (בחוזקה) ואינו יכול לבוא אחרי to עם מושא.", "strong הוא שם תואר (חזק). אחרי to דרוש פועל.", "strength הוא שם עצם (חוזק). to strength the bridge אינו מבנה תקין."]$q$::jsonb, $q$strength + en = לחזק. -en הופכת תואר או שם עצם לפועל: widen (להרחיב), shorten (לקצר), weaken (להחליש). אחרי to — פועל.$q$, 5, $q$shabbat batch 2026-09-05, family=VERB$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$unreliable$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$un-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה — הופך את המשמעות$q$, $q$unreliable$q$, $q$The old bus schedule is so __________ that most passengers have stopped trusting it and simply wait at the stop until something arrives.$q$, $q$["reliably", "reliability", "unreliable", "reliable"]$q$::jsonb, 3, $q$["reliably הוא תואר הפועל (באופן אמין) ואינו יכול לתאר את the schedule אחרי is so.", "reliability הוא שם עצם (אמינות). אחרי so דרוש שם תואר שמתאר את הלוח.", "נכון. un- שוללת: reliable = אמין, unreliable = לא אמין. הרמז: stopped trusting it.", "reliable פירושו אמין. אם הלוח היה אמין, הנוסעים לא היו מפסיקים לסמוך עליו."]$q$::jsonb, $q$un + rely + able = לא ניתן לסמוך עליו. שימו לב שיש כאן שני חלקים: -able הופכת לתואר, ו-un- הופכת את המשמעות.$q$, 3, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$unexpected$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$un-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה — הופך את המשמעות$q$, $q$unexpected$q$, $q$The company's collapse was entirely __________; only a month earlier it had reported record profits.$q$, $q$["expectantly", "expected", "unexpected", "expectation"]$q$::jsonb, 3, $q$["expectantly הוא תואר הפועל (בציפייה) ואינו מתאר את הקריסה.", "expected פירושו צפוי. רווחי שיא חודש קודם לכן אומרים שאיש לא צפה את הקריסה.", "נכון. un + expected = לא צפוי. הרמז הוא הניגוד: record profits ואז collapse.", "expectation הוא שם עצם (ציפייה). אחרי was entirely דרוש שם תואר."]$q$::jsonb, $q$un + expect + ed = לא צפוי. כשיש ניגוד במשפט (only a month earlier), המילה החסרה בדרך כלל מסמנת הפתעה או שלילה.$q$, 3, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$unwilling$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$un-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה — הופך את המשמעות$q$, $q$unwilling$q$, $q$Although the two sides met several times, both remained __________ to make even the smallest concession.$q$, $q$["unwilling", "willingly", "willing", "willingness"]$q$::jsonb, 1, $q$["נכון. un + willing = לא מוכן. Although פותח ניגוד: נפגשו הרבה, ובכל זאת לא היו מוכנים לוותר.", "willingly הוא תואר הפועל (ברצון) ואינו יכול לבוא אחרי remained עם to.", "willing פירושו מוכן. אם שני הצדדים היו מוכנים לוותר, המילה although לא הייתה נחוצה.", "willingness הוא שם עצם (נכונות). אחרי remained דרוש שם תואר, כמו remained silent."]$q$::jsonb, $q$un + willing = לא מוכן. remained + שם תואר הוא מבנה קבוע (remained calm, remained unclear) — חפשו תואר, ואז בדקו את הכיוון.$q$, 4, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$unconvinced$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$un-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה — הופך את המשמעות$q$, $q$unconvinced$q$, $q$Despite the lawyer's long and detailed argument, the jury remained __________ and returned a guilty verdict within an hour.$q$, $q$["convincing", "unconvinced", "conviction", "convinced"]$q$::jsonb, 2, $q$["convincing פירושו משכנע — מתאר את הטיעון, לא את חבר המושבעים ששומע אותו.", "נכון. un + convinced = לא השתכנע. Despite מסמן שהטיעון הארוך לא עזר, ופסק הדין המהיר מאשר זאת.", "conviction הוא שם עצם (הרשעה, או אמונה עמוקה). אחרי remained דרוש שם תואר.", "convinced פירושו השתכנע. זה ההפך: אם השתכנעו, לא היו מרשיעים במהירות למרות הטיעון."]$q$::jsonb, $q$un + convinced = לא משוכנע. שימו לב להבדל בין convincing (מה שמשכנע) ל-convinced (מי שהשתכנע): הראשון מתאר את הטיעון, השני את השומע.$q$, 5, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$inaccurate$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$in-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה (in-, וגם il-/ir- לפני l/r)$q$, $q$inaccurate$q$, $q$Several of the figures in the report turned out to be __________, so the entire study had to be checked again from the beginning.$q$, $q$["inaccurate", "accurate", "accuracy", "accurately"]$q$::jsonb, 1, $q$["נכון. in + accurate = לא מדויק. הרמז: had to be checked again — משהו היה שגוי.", "accurate פירושו מדויק. אם הנתונים היו מדויקים, לא היה צורך לבדוק את המחקר מחדש.", "accuracy הוא שם עצם (דיוק). אחרי to be דרוש שם תואר שמתאר את המספרים.", "accurately הוא תואר הפועל (במדויק) ואינו מתאר את the figures."]$q$::jsonb, $q$in + accurate = לא מדויק. in- היא אחות של un-: incorrect, invisible, independent. לפני l היא הופכת ל-il (illegal) ולפני r ל-ir (irregular).$q$, 4, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$irrelevant$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$in-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה (in-, וגם il-/ir- לפני l/r)$q$, $q$irrelevant$q$, $q$The judge asked the witness to stop, explaining that his childhood memories were __________ to the question of who had signed the contract.$q$, $q$["relevantly", "relevance", "irrelevant", "relevant"]$q$::jsonb, 3, $q$["relevantly הוא תואר הפועל ואינו יכול לתאר את memories אחרי were.", "relevance הוא שם עצם (רלוונטיות). אחרי were דרוש שם תואר.", "נכון. ir + relevant = לא קשור לעניין. ir- היא צורת in- לפני r. הרמז: השופט מבקש להפסיק.", "relevant פירושו רלוונטי. אם הזיכרונות היו קשורים לעניין, השופט לא היה עוצר את העד."]$q$::jsonb, $q$ir + relevant = לא רלוונטי. in- משנה צורה לפי האות שאחריה: im- לפני b/m/p (impossible), il- לפני l (illogical), ir- לפני r (irregular). המשמעות זהה: לא.$q$, 5, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$disagree$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$dis-$q$, $q$prefix$q$, $q$REVERSE$q$, $q$היפוך הפעולה — עושה את ההפך$q$, $q$disagree$q$, $q$The two doctors __________ about the cause of the illness, so the patient decided to ask for a third opinion.$q$, $q$["disagree", "agreeable", "agreement", "agree"]$q$::jsonb, 1, $q$["נכון. dis + agree = לא להסכים. הרמז: המטופל מבקש דעה שלישית — כלומר שתי הדעות הראשונות סותרות זו את זו.", "agreeable הוא שם תואר (נעים, מקובל) ואינו יכול לשמש כפועל של המשפט.", "agreement הוא שם עצם (הסכמה). The two doctors הוא נושא, ואחריו דרוש פועל.", "agree פירושו להסכים. אם הרופאים היו מסכימים, לא היה צורך בדעה שלישית."]$q$::jsonb, $q$dis + agree = לחלוק. dis- הופכת את הפעולה, לא רק שוללת אותה: agree/disagree, like/dislike, appear/disappear.$q$, 3, $q$shabbat batch 2026-09-05, family=REVERSE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$disconnected$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$dis-$q$, $q$prefix$q$, $q$REVERSE$q$, $q$היפוך הפעולה — עושה את ההפך$q$, $q$disconnected$q$, $q$Because the bill had not been paid for three months, the phone company __________ the line without any further warning.$q$, $q$["disconnected", "reconnected", "connected", "connection"]$q$::jsonb, 1, $q$["נכון. dis + connect = לנתק. הסיבה (לא שולם) מובילה לפעולה ההפוכה לחיבור.", "reconnected פירושו חיבר מחדש. re- מסמנת שוב, וזה לא מה שקורה למי שלא שילם.", "connected פירושו חיבר. אי תשלום במשך שלושה חודשים מוביל לניתוק, לא לחיבור.", "connection הוא שם עצם (חיבור). אחרי the phone company דרוש פועל."]$q$::jsonb, $q$dis + connect = לנתק. כשמופיעות גם dis- וגם re- באפשרויות, שאלו: המשפט מתאר ביטול או חזרה? Because... not paid מוביל לביטול.$q$, 3, $q$shabbat batch 2026-09-05, family=REVERSE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$discourage$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$dis-$q$, $q$prefix$q$, $q$REVERSE$q$, $q$היפוך הפעולה — עושה את ההפך$q$, $q$discourage$q$, $q$High entry fees tend to __________ young athletes from competing, which is exactly the opposite of what the organizers intended.$q$, $q$["courage", "courageous", "encourage", "discourage"]$q$::jsonb, 4, $q$["courage הוא שם עצם (אומץ). אחרי tend to דרוש פועל.", "courageous הוא שם תואר (אמיץ) ואינו יכול לבוא אחרי tend to.", "encourage פירושו לעודד. המשפט אומר שהתוצאה היא ההפך ממה שהמארגנים רצו — והם ודאי רצו לעודד.", "נכון. dis + courage = לרפות ידיים, להרתיע. דמי כניסה גבוהים מרחיקים ספורטאים צעירים, ו-the opposite מאשר את הכיוון."]$q$::jsonb, $q$dis + courage = להרתיע (ההפך מ-encourage = לעודד). en- ו-dis- הן זוג: enable/disable, encourage/discourage.$q$, 4, $q$shabbat batch 2026-09-05, family=REVERSE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$reconsider$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$re-$q$, $q$prefix$q$, $q$AGAIN$q$, $q$שוב, מחדש$q$, $q$reconsider$q$, $q$After hearing the new evidence, the committee agreed to __________ its earlier decision and to vote on the matter once more.$q$, $q$["reconsider", "considerable", "consideration", "consider"]$q$::jsonb, 1, $q$["נכון. re + consider = לשקול מחדש. הרמזים: earlier decision ו-once more.", "considerable הוא שם תואר (ניכר, משמעותי). אחרי agreed to דרוש פועל.", "consideration הוא שם עצם (התחשבות, שיקול). אחרי to דרושה צורת המקור של פועל.", "consider פירושו לשקול. אבל ההחלטה כבר התקבלה (earlier decision), ולכן מדובר בשקילה מחדש."]$q$::jsonb, $q$re + consider = לשקול מחדש. re- כמעט תמיד באה עם רמז של פעם נוספת במשפט: again, once more, earlier, for the second time.$q$, 3, $q$shabbat batch 2026-09-05, family=AGAIN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$regain$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$re-$q$, $q$prefix$q$, $q$AGAIN$q$, $q$שוב, מחדש$q$, $q$regain$q$, $q$It took the swimmer nearly two years to __________ the strength she had lost during her long illness.$q$, $q$["gain", "against", "gainful", "regain"]$q$::jsonb, 4, $q$["gain פירושו להשיג. זה קרוב, אבל המשפט מדגיש שהכוח היה שלה קודם ואבד — ולכן דרוש חזרה.", "against היא מילת יחס (נגד) שרק נראית דומה. אין לה קשר ל-gain.", "gainful הוא שם תואר (מכניס, רווחי) ואינו יכול לבוא אחרי to.", "נכון. re + gain = להשיג בחזרה. הרמז הוא the strength she had lost — הכוח היה קיים, אבד, וחוזר."]$q$::jsonb, $q$re + gain = להשיג בחזרה. כשמופיע במשפט lost, המילה החסרה היא לעיתים קרובות re-: regain, recover, rebuild.$q$, 4, $q$shabbat batch 2026-09-05, family=AGAIN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$reunited$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$re-$q$, $q$prefix$q$, $q$AGAIN$q$, $q$שוב, מחדש$q$, $q$reunited$q$, $q$The brothers, separated as children during the war, were finally __________ more than forty years later thanks to an online records search.$q$, $q$["unity", "reunited", "untied", "united"]$q$::jsonb, 2, $q$["unity הוא שם עצם (אחדות). אחרי were finally דרוש פועל בצורת סביל או שם תואר.", "נכון. re + unite = לאחד מחדש. הרמז: separated as children ואז finally... forty years later.", "untied פירושו הותר, שוחרר מקשר — מילה אחרת (un + tied) שרק נראית דומה ל-united.", "united פירושו מאוחד. אבל האחים כבר היו יחד לפני שהופרדו — ולכן מדובר באיחוד מחדש."]$q$::jsonb, $q$re + unite = לאחד מחדש. זהירות ממילים דומות: united (מאוחד) ו-untied (מותר מקשר) נבדלות באות אחת ובמשמעות לגמרי.$q$, 5, $q$shabbat batch 2026-09-05, family=AGAIN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$misunderstood$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$mis-$q$, $q$prefix$q$, $q$WRONGLY$q$, $q$בטעות, באופן שגוי$q$, $q$misunderstood$q$, $q$The tourist __________ the sign and walked confidently onto the wrong platform, where his train never arrived.$q$, $q$["understandable", "misunderstood", "understanding", "understood"]$q$::jsonb, 2, $q$["understandable הוא שם תואר (מובן) ואינו מתאר פעולה של התייר.", "נכון. mis + understood = הבין לא נכון. הרמז: the wrong platform.", "understanding הוא שם עצם (הבנה) או צורת -ing; אחרי The tourist דרוש פועל בזמן עבר.", "understood פירושו הבין. מי שהבין את השלט לא היה מגיע לרציף הלא נכון."]$q$::jsonb, $q$mis + understand = להבין לא נכון. מילת המפתח wrong במשפט היא כמעט תמיד שותפה של mis-.$q$, 3, $q$shabbat batch 2026-09-05, family=WRONGLY$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$misleading$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$mis-$q$, $q$prefix$q$, $q$WRONGLY$q$, $q$בטעות, באופן שגוי$q$, $q$misleading$q$, $q$The advertisement was judged __________ because it showed a much larger portion than the one customers actually received.$q$, $q$["leader", "leading", "misleading", "mislaid"]$q$::jsonb, 3, $q$["leader הוא אדם (מנהיג). הסיומת -er מציינת מבצע פעולה, לא תכונה של מודעה.", "leading פירושו מוביל, בכיר. מודעה מובילה אינה סיבה לפסק דין נגדה.", "נכון. mis + leading = מטעה. המודעה הראתה מנה גדולה בהרבה מהאמיתית — כלומר הובילה את הלקוחות למסקנה שגויה.", "mislaid פירושו הניח במקום הלא נכון, איבד. אותה תחילית, אבל השורש lay אינו מתאים כאן."]$q$::jsonb, $q$mis + lead = להוביל לכיוון שגוי, להטעות. שימו לב שהתחילית לבדה לא מספיקה — גם השורש חייב להתאים למשפט (lead, לא lay).$q$, 4, $q$shabbat batch 2026-09-05, family=WRONGLY$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$miscalculated$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$mis-$q$, $q$prefix$q$, $q$WRONGLY$q$, $q$בטעות, באופן שגוי$q$, $q$miscalculated$q$, $q$The engineers had __________ the weight the bridge could carry, and the first heavy truck to cross it caused visible cracks.$q$, $q$["miscalculated", "calculation", "calculated", "recalculated"]$q$::jsonb, 1, $q$["נכון. mis + calculate = חישב לא נכון. הרמז: הגשר נסדק כבר במשאית הראשונה.", "calculation הוא שם עצם (חישוב). אחרי had דרושה צורת past participle של פועל.", "calculated פירושו חישב. החישוב נעשה, אבל הסדקים מראים שהוא היה שגוי — ודרושה מילה שאומרת זאת.", "recalculated פירושו חישב מחדש. re- מסמנת שוב, וזה לא מסביר את הסדקים."]$q$::jsonb, $q$mis + calculate = לטעות בחישוב. mis- מתארת טעות בפעולה: misjudge, miscount, misspell. התוצאה השלילית במשפט (cracks) היא הרמז.$q$, 5, $q$shabbat batch 2026-09-05, family=WRONGLY$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$overcrowded$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$over-$q$, $q$prefix$q$, $q$DEGREE$q$, $q$יותר מדי, במידה מוגזמת$q$, $q$overcrowded$q$, $q$The small clinic was so __________ that some patients had to wait in the corridor for more than four hours.$q$, $q$["crowded", "overcrowded", "crowd", "undercrowded"]$q$::jsonb, 2, $q$["crowded פירושו צפוף. זה מתאים, אבל המשפט מדגיש מצב קיצוני (יותר מארבע שעות במסדרון) — ולכן דרושה המילה החזקה יותר.", "נכון. over + crowded = צפוף יתר על המידה. המתנה של ארבע שעות במסדרון היא סימן לעומס מוגזם.", "crowd הוא שם עצם (קהל). אחרי so דרוש שם תואר.", "undercrowded אינה מילה מקובלת באנגלית, ובכל מקרה מתארת מיעוט אנשים — ההפך מהמצב במשפט."]$q$::jsonb, $q$over + crowded = צפוף מדי. over- מוסיפה מוגזם: overpriced (יקר מדי), overworked (עובד יותר מדי). חפשו במשפט תוצאה של עודף.$q$, 3, $q$shabbat batch 2026-09-05, family=DEGREE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$overlooked$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$over-$q$, $q$prefix$q$, $q$DEGREE$q$, $q$יותר מדי, במידה מוגזמת$q$, $q$overlooked$q$, $q$The detective had __________ a small detail in the first report — a detail that later turned out to solve the entire case.$q$, $q$["overlooking", "looked", "outlook", "overlooked"]$q$::jsonb, 4, $q$["overlooking היא צורת -ing ואינה יכולה לבוא ישירות אחרי had (had overlooked, לא had overlooking).", "looked פירושו הביט. looked a detail אינו מבנה תקין, ובכל מקרה המשפט מתאר פרט שפוספס.", "outlook הוא שם עצם (השקפה, תחזית). אחרי had דרוש past participle.", "נכון. over + look = להסתכל מעבר, כלומר לפספס. הרמז: הפרט התגלה כחשוב רק later."]$q$::jsonb, $q$over + look = לפספס (להסתכל מעל משהו בלי לראות אותו). זו דוגמה ש-over- לא תמיד פירושה יותר מדי — לפעמים היא מקום: מעל, מעבר. ההקשר מכריע.$q$, 5, $q$shabbat batch 2026-09-05, family=DEGREE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$underestimated$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$under-$q$, $q$prefix$q$, $q$DEGREE$q$, $q$פחות מדי, בחסר$q$, $q$underestimated$q$, $q$The organizers had badly __________ the number of visitors: they printed five hundred programs, and more than two thousand people came.$q$, $q$["overestimated", "underestimated", "estimation", "estimated"]$q$::jsonb, 2, $q$["overestimated פירושו העריך יותר מדי. זה היה נכון אם היו מדפיסים אלפיים ומגיעים חמש מאות — ההפך.", "נכון. under + estimate = להעריך בחסר. 500 תוכניות מול 2,000 מבקרים — ההערכה הייתה נמוכה מדי.", "estimation הוא שם עצם (הערכה). אחרי had badly דרוש past participle של פועל.", "estimated פירושו העריך, בלי לומר לאיזה כיוון. המשפט נותן מספרים שמראים כיוון ברור."]$q$::jsonb, $q$under + estimate = להעריך בחסר. כשיש over ו-under באפשרויות, המספרים במשפט מכריעים: ציפו למעט וקיבלו הרבה = under.$q$, 4, $q$shabbat batch 2026-09-05, family=DEGREE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$prehistoric$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$pre-$q$, $q$prefix$q$, $q$TIME_PLACE$q$, $q$לפני, מראש$q$, $q$prehistoric$q$, $q$The cave paintings are __________: they were made thousands of years before anyone in the region had learned to write.$q$, $q$["historian", "prehistoric", "historic", "historically"]$q$::jsonb, 2, $q$["historian הוא אדם (היסטוריון). אחרי are דרוש שם תואר שמתאר את הציורים, לא אדם.", "נכון. pre + historic = מלפני ההיסטוריה. הרמז: before anyone... had learned to write.", "historic פירושו היסטורי, בעל חשיבות היסטורית. אבל המשפט מדגיש שהציורים קדמו לכתב — כלומר לפני ההיסטוריה הכתובה.", "historically הוא תואר הפועל (מבחינה היסטורית) ואינו יכול לתאר את the cave paintings אחרי are."]$q$::jsonb, $q$pre + historic = שלפני ההיסטוריה. pre- פירושה לפני: preview (צפייה מוקדמת), precaution (אמצעי זהירות מראש).$q$, 3, $q$shabbat batch 2026-09-05, family=TIME_PLACE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$predictable$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$pre-$q$, $q$prefix$q$, $q$TIME_PLACE$q$, $q$לפני, מראש$q$, $q$predictable$q$, $q$The ending of the film was so __________ that half the audience guessed it within the first ten minutes.$q$, $q$["predicted", "prediction", "unpredictable", "predictable"]$q$::jsonb, 4, $q$["predicted פירושו נחזה — צורת עבר. so predicted that אינו מבנה טבעי, והמשפט מתאר תכונה של הסוף.", "prediction הוא שם עצם (תחזית). אחרי so דרוש שם תואר.", "unpredictable פירושו בלתי צפוי. זה ההפך: אם הסוף היה בלתי צפוי, איש לא היה מנחש אותו.", "נכון. pre + dict + able = ניתן לומר מראש, צפוי. הרמז: הקהל ניחש את הסוף כבר בעשר הדקות הראשונות."]$q$::jsonb, $q$pre + dict (לומר) + able = שאפשר לומר מראש. שלושה חלקים במילה אחת: pre- לפני, dict אמירה, -able ניתן ל-. פרקו מבחוץ פנימה.$q$, 4, $q$shabbat batch 2026-09-05, family=TIME_PLACE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$precaution$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$pre-$q$, $q$prefix$q$, $q$TIME_PLACE$q$, $q$לפני, מראש$q$, $q$precaution$q$, $q$As a __________, the museum moved its most valuable paintings to the basement several days before the storm was expected to arrive.$q$, $q$["caution", "cautious", "cautiously", "precaution"]$q$::jsonb, 4, $q$["caution פירושו זהירות. זה קרוב, אבל המשפט מתאר פעולה שנעשתה מראש, לפני הסערה — ולכן דרושה המילה עם pre-.", "cautious הוא שם תואר (זהיר). אחרי As a דרוש שם עצם.", "cautiously הוא תואר הפועל (בזהירות) ואינו יכול לבוא אחרי As a.", "נכון. pre + caution = אמצעי זהירות מראש. הרמז: several days before the storm."]$q$::jsonb, $q$pre + caution = זהירות מראש. המבנה As a ___ דורש שם עצם; ואז השאלה היא רק איזה — ו-before the storm מצביע על pre-.$q$, 5, $q$shabbat batch 2026-09-05, family=TIME_PLACE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$harmless$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-less$q$, $q$suffix$q$, $q$WITHOUT$q$, $q$בלי, נטול$q$, $q$harmless$q$, $q$Although the snake looks frightening, it is completely __________ and has never been known to bite a human.$q$, $q$["harmful", "harmless", "harmed", "harm"]$q$::jsonb, 2, $q$["harmful פירושו מזיק. זה ההפך ממה שהמשפט אומר: הנחש מעולם לא נשך אדם.", "נכון. harm + less = חסר נזק, לא מסוכן. Although פותח ניגוד: נראה מפחיד, אבל למעשה לא מזיק.", "harmed פירושו נפגע. זה מתאר מי שספג נזק, לא את הנחש עצמו.", "harm הוא שם עצם או פועל (נזק, להזיק). אחרי completely דרוש שם תואר."]$q$::jsonb, $q$harm + less = בלי נזק. -less ו--ful הן זוג הפוך: harmless/harmful, careless/careful. Although בתחילת המשפט אומר שהתמונה מתהפכת.$q$, 3, $q$shabbat batch 2026-09-05, family=WITHOUT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$countless$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-less$q$, $q$suffix$q$, $q$WITHOUT$q$, $q$בלי, נטול$q$, $q$countless$q$, $q$Over the centuries, __________ travelers have crossed this desert, and very few of them left any written record of the journey.$q$, $q$["countless", "countable", "counting", "counted"]$q$::jsonb, 1, $q$["נכון. count + less = שאי אפשר לספור, אינספור. הרמז: Over the centuries — מספר עצום של נוסעים.", "countable פירושו ניתן לספירה. זה ההפך מהרעיון של מספר עצום לאורך מאות שנים.", "counting היא צורת -ing (סופר). היא אינה מתארת כמות של נוסעים.", "counted פירושו נספרו. counted travelers היה אומר שמישהו ספר אותם — ואין לכך רמז."]$q$::jsonb, $q$count + less = אינספור (בלי אפשרות לספור). -less לא תמיד פירושה חוסר שלילי: countless, endless, timeless מתארות גודל או נצחיות.$q$, 4, $q$shabbat batch 2026-09-05, family=WITHOUT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$doubtful$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ful$q$, $q$suffix$q$, $q$WITHOUT$q$, $q$מלא ב-, עם$q$, $q$doubtful$q$, $q$Given how little rain has fallen this year, it is __________ whether the farmers will manage to harvest even half of their usual crop.$q$, $q$["doubtless", "doubtfully", "doubtful", "doubt"]$q$::jsonb, 3, $q$["doubtless פירושו ללא ספק, בוודאות. אבל המשפט מתאר אי-ודאות: whether... even half.", "doubtfully הוא תואר הפועל (בספקנות) ואינו יכול לבוא אחרי it is.", "נכון. doubt + ful = מלא ספק, מוטל בספק. הרמז: little rain ו-whether — לא ברור אם היבול יצליח.", "doubt הוא שם עצם או פועל (ספק, לפקפק). אחרי it is דרוש שם תואר."]$q$::jsonb, $q$doubt + ful = מלא ספק. doubtless (בלי ספק) ו-doubtful (עם ספק) הם הפכים — ו-whether במשפט הוא הרמז לאי-ודאות.$q$, 5, $q$shabbat batch 2026-09-05, family=WITHOUT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$avoidable$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-able$q$, $q$suffix$q$, $q$CAPABLE$q$, $q$ניתן ל־, בר־$q$, $q$avoidable$q$, $q$The investigation concluded that the accident had been entirely __________ and that a simple warning sign would have prevented it.$q$, $q$["avoidable", "avoidance", "avoid", "unavoidable"]$q$::jsonb, 1, $q$["נכון. avoid + able = שניתן היה להימנע ממנו. הרמז: a simple warning sign would have prevented it.", "avoidance הוא שם עצם (הימנעות) ואינו מתאר את התאונה.", "avoid הוא פועל (להימנע). אחרי had been entirely דרוש שם תואר.", "unavoidable פירושו בלתי נמנע. זה ההפך: אם אי אפשר היה למנוע, שלט אזהרה לא היה עוזר."]$q$::jsonb, $q$avoid + able = שאפשר להימנע ממנו. כשמופיעות גם -able וגם un-able, המשפט מכריע: would have prevented = אפשר היה למנוע.$q$, 3, $q$shabbat batch 2026-09-05, family=CAPABLE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$affordable$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-able$q$, $q$suffix$q$, $q$CAPABLE$q$, $q$ניתן ל־, בר־$q$, $q$affordable$q$, $q$The city promised to build thousands of __________ apartments so that teachers and nurses could live near the places where they work.$q$, $q$["affordably", "affording", "affordable", "afford"]$q$::jsonb, 3, $q$["affordably הוא תואר הפועל ואינו יכול לתאר שם עצם כמו apartments.", "affording היא צורת -ing של הפועל ואינה משמשת כתואר לדירות.", "נכון. afford + able = שאפשר להרשות לעצמו, במחיר סביר. הרמז: teachers and nurses — בעלי הכנסה בינונית שצריכים דיור במחיר סביר.", "afford הוא פועל (להרשות לעצמו). לפני apartments דרוש שם תואר."]$q$::jsonb, $q$afford + able = במחיר סביר. -able הופכת פועל לתואר: לפני שם עצם (apartments) חפשו תואר, ואז שאלו איזה.$q$, 4, $q$shabbat batch 2026-09-05, family=CAPABLE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$accessible$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ible$q$, $q$suffix$q$, $q$CAPABLE$q$, $q$ניתן ל־ (צורה אחרת של -able)$q$, $q$accessible$q$, $q$The new ramp finally made the library __________ to visitors in wheelchairs, who had previously been unable to reach the upper floor.$q$, $q$["inaccessible", "accessibility", "accessible", "access"]$q$::jsonb, 3, $q$["inaccessible פירושו לא נגיש. זה מתאר את המצב הקודם (previously), לא את מה שהרמפה עשתה.", "accessibility הוא שם עצם (נגישות) ואינו יכול לתאר את the library במבנה made X + תואר.", "נכון. access + ible = נגיש, שניתן להגיע אליו. הרמז: previously... unable to reach — עכשיו אפשר.", "access הוא שם עצם או פועל (גישה, לגשת). אחרי made the library דרוש שם תואר."]$q$::jsonb, $q$access + ible = נגיש. -ible היא בת דודה של -able ובעלת אותה משמעות: possible, visible, flexible. המבנה made + שם עצם + תואר (made the library accessible) הוא רמז לתואר.$q$, 5, $q$shabbat batch 2026-09-05, family=CAPABLE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$explanation$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-tion$q$, $q$suffix$q$, $q$NOUN$q$, $q$סיומת שיוצרת שם עצם מפועל$q$, $q$explanation$q$, $q$The teacher gave a clear __________ of the rule, and after that nobody in the class made the same mistake again.$q$, $q$["explained", "explanation", "explanatory", "explain"]$q$::jsonb, 2, $q$["explained הוא פועל בעבר. gave a clear explained אינו מבנה תקין.", "נכון. explain + tion = הסבר. שם תואר (clear) תמיד מתאר שם עצם, ו-gave a... דורש שם עצם.", "explanatory הוא שם תואר (הסברי). שני שמות תואר ברצף (clear explanatory) בלי שם עצם אחריהם אינם משפט תקין.", "explain הוא פועל (להסביר). אחרי a clear דרוש שם עצם."]$q$::jsonb, $q$explain + tion = הסבר. הנוסחה: a/an/the + שם תואר + ___ = שם עצם. -tion, -sion, -ment, -ness הן הסיומות שיוצרות אותו.$q$, 3, $q$shabbat batch 2026-09-05, family=NOUN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$reduction$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-tion$q$, $q$suffix$q$, $q$NOUN$q$, $q$סיומת שיוצרת שם עצם מפועל$q$, $q$reduction$q$, $q$The factory reported a sharp __________ in energy use after replacing its old machines, saving nearly a third of its monthly bill.$q$, $q$["reduce", "reducing", "reduced", "reduction"]$q$::jsonb, 4, $q$["reduce הוא פועל (להפחית). אחרי a sharp דרוש שם עצם.", "reducing היא צורת -ing. a sharp reducing in אינו מבנה תקין.", "reduced הוא פועל בעבר או תואר (מופחת). a sharp reduced אינו מבנה תקין בלי שם עצם אחריו.", "נכון. reduce + tion = הפחתה. a sharp ___ in דורש שם עצם, ו-saving a third מאשר שמדובר בירידה."]$q$::jsonb, $q$reduce + tion = הפחתה. שימו לב לשינוי הכתיב: reduce → reduction, produce → production, decide → decision. הסיומת משנה גם את סוף השורש.$q$, 4, $q$shabbat batch 2026-09-05, family=NOUN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$contribution$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-tion$q$, $q$suffix$q$, $q$NOUN$q$, $q$סיומת שיוצרת שם עצם מפועל$q$, $q$contribution$q$, $q$Although she never held a formal position, her __________ to the project was so significant that the final report was dedicated to her.$q$, $q$["contributed", "contribution", "contribute", "contributor"]$q$::jsonb, 2, $q$["contributed הוא פועל בעבר. אחרי her אי אפשר להציב פועל.", "נכון. contribute + tion = תרומה. her ___ to the project דורש שם עצם, והמשך המשפט (so significant) מתאר את התרומה עצמה.", "contribute הוא פועל (לתרום). אחרי her (שייכות) דרוש שם עצם.", "contributor הוא אדם (תורם). her contributor to the project היה אומר שיש לה תורם — לא הגיוני; המשפט מדבר על מה שהיא תרמה."]$q$::jsonb, $q$contribute + tion = תרומה. כשיש גם -or (אדם) וגם -tion (הדבר) באפשרויות, שאלו: המשפט מתאר מי או מה? was so significant — זה מה, לא מי.$q$, 6, $q$shabbat batch 2026-09-05, family=NOUN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$scientist$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ist$q$, $q$suffix$q$, $q$AGENT$q$, $q$אדם שעוסק בתחום$q$, $q$scientist$q$, $q$A __________ who works in a laboratory must record every experiment carefully so that others can repeat it.$q$, $q$["scientist", "science", "scientific", "scientifically"]$q$::jsonb, 1, $q$["נכון. scient + ist = מדען. הרמזים: A ___ who — מבנה שמתאר אדם — ו-works in a laboratory.", "science הוא שם עצם (מדע), אבל אינו אדם — ומדע לא עובד במעבדה.", "scientific הוא שם תואר (מדעי). אחרי A דרוש שם עצם, ו-who מצביע על אדם.", "scientifically הוא תואר הפועל (באופן מדעי) ואינו יכול לבוא אחרי A."]$q$::jsonb, $q$science + ist = מדען. who אחרי החסר הוא רמז חזק לאדם, ו--ist, -er, -or, -ant הן הסיומות של בני אדם.$q$, 3, $q$shabbat batch 2026-09-05, family=AGENT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$economist$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ist$q$, $q$suffix$q$, $q$AGENT$q$, $q$אדם שעוסק בתחום$q$, $q$economist$q$, $q$Almost every __________ interviewed by the newspaper predicted that prices would keep rising until at least next spring.$q$, $q$["economic", "economy", "economical", "economist"]$q$::jsonb, 4, $q$["economic הוא שם תואר (כלכלי). אחרי every דרוש שם עצם, ו-interviewed מצביע על אדם.", "economy הוא שם עצם (כלכלה). כלכלה אינה מתראיינת ואינה חוזה.", "economical הוא שם תואר (חסכוני) ואינו מתאר אדם שמתראיין.", "נכון. econom + ist = כלכלן. הרמזים: interviewed ו-predicted — פעולות של אדם."]$q$::jsonb, $q$economy + ist = כלכלן. פעלים כמו interviewed, predicted, argued דורשים נושא אנושי — ואז חפשו סיומת של אדם.$q$, 4, $q$shabbat batch 2026-09-05, family=AGENT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$optimist$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ist$q$, $q$suffix$q$, $q$AGENT$q$, $q$אדם שעוסק בתחום$q$, $q$optimist$q$, $q$Even after three failed attempts, she remained an __________, convinced that the fourth try would finally succeed.$q$, $q$["optimistic", "optimize", "optimism", "optimist"]$q$::jsonb, 4, $q$["optimistic הוא שם תואר (אופטימי). אחרי an דרוש שם עצם, לא תואר.", "optimize הוא פועל (למטב, לשפר). אחרי remained an אי אפשר להציב פועל.", "optimism הוא שם עצם מופשט (אופטימיות). remained an optimism אינו הגיוני — היא אדם, לא תכונה.", "נכון. optim + ist = אופטימיסט, אדם שמאמין בטוב. הרמז: an לפני החסר דורש שם עצם, ו-convinced that... would succeed מתאר אדם אופטימי."]$q$::jsonb, $q$optim + ist = אופטימיסט. -ist גם מציינת מי שמחזיק בהשקפה: realist, idealist, pessimist. an לפני החסר = שם עצם.$q$, 5, $q$shabbat batch 2026-09-05, family=AGENT$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$modernize$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ize$q$, $q$suffix$q$, $q$VERB$q$, $q$סיומת שהופכת שם תואר לפועל$q$, $q$modernize$q$, $q$The railway company plans to __________ its oldest stations by adding elevators, digital screens, and wider platforms.$q$, $q$["modernization", "modernize", "modernity", "modern"]$q$::jsonb, 2, $q$["modernization הוא שם עצם (מודרניזציה). אחרי to דרושה צורת המקור של פועל.", "נכון. modern + ize = לחדש, להפוך למודרני. הרמז: plans to דורש פועל, והרשימה (elevators, screens) מתארת פעולת שדרוג.", "modernity הוא שם עצם (מודרניות). plans to modernity אינו מבנה תקין.", "modern הוא שם תואר (מודרני). אחרי plans to דרוש פועל."]$q$::jsonb, $q$modern + ize = להפוך למודרני. אחרי to, will, can, must — תמיד פועל. -ize היא הסיומת שיוצרת פועל מתואר.$q$, 3, $q$shabbat batch 2026-09-05, family=VERB$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$minimize$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ize$q$, $q$suffix$q$, $q$VERB$q$, $q$סיומת שהופכת שם תואר לפועל$q$, $q$minimize$q$, $q$Wearing a helmet does not prevent every injury, but it can __________ the damage when a cyclist falls.$q$, $q$["minimum", "maximize", "minimal", "minimize"]$q$::jsonb, 4, $q$["minimum הוא שם עצם (מינימום). can minimum אינו מבנה תקין.", "maximize פירושו להגדיל למקסימום. זה ההפך: קסדה לא מגדילה נזק.", "minimal הוא שם תואר (מזערי). אחרי can דרוש פועל.", "נכון. minim + ize = להקטין למינימום. הרמז: does not prevent every injury, but... — הקסדה לא מונעת, אבל מפחיתה."]$q$::jsonb, $q$minim + ize = למזער. -ize מופיעה בזוגות הפוכים: minimize/maximize. but אחרי משפט שלילי מסמן שהמילה החסרה היא חיובית-חלקית: לא מונע, אבל מקטין.$q$, 4, $q$shabbat batch 2026-09-05, family=VERB$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$simplify$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$-ify$q$, $q$suffix$q$, $q$VERB$q$, $q$סיומת שהופכת שם תואר לפועל (כמו -ize)$q$, $q$simplify$q$, $q$The new tax form is meant to __________ the process, yet many people say it is even harder to complete than the old one.$q$, $q$["simple", "simply", "simplicity", "simplify"]$q$::jsonb, 4, $q$["simple הוא שם תואר (פשוט). אחרי is meant to דרוש פועל.", "simply הוא תואר הפועל (פשוט, בפשטות) ואינו יכול לבוא אחרי to עם מושא.", "simplicity הוא שם עצם (פשטות). to simplicity the process אינו מבנה תקין.", "נכון. simpl + ify = לפשט. הרמז: yet מציג ניגוד — הטופס נועד לפשט, אבל בפועל קשה יותר."]$q$::jsonb, $q$simple + ify = לפשט. -ify היא אחות של -ize: clarify (להבהיר), justify (להצדיק), intensify (להעצים). אחרי to — פועל.$q$, 5, $q$shabbat batch 2026-09-05, family=VERB$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$unaware$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$un-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה — הופך את המשמעות$q$, $q$unaware$q$, $q$Most residents were completely __________ of the planned construction until the trucks arrived one morning outside their homes.$q$, $q$["awake", "awareness", "unaware", "aware"]$q$::jsonb, 3, $q$["awake פירושו ער. מילה דומה בצליל אבל שונה בשורש ובמשמעות.", "awareness הוא שם עצם (מודעות). אחרי were completely דרוש שם תואר.", "נכון. un + aware = לא מודע. הרמז: until the trucks arrived — רק אז נודע להם.", "aware פירושו מודע. אם התושבים היו מודעים, הגעת המשאיות לא הייתה מפתיעה — ו-until לא היה נחוץ."]$q$::jsonb, $q$un + aware = לא מודע. until במשפט מסמן שמשהו השתנה בנקודת זמן — ולפניה המצב היה הפוך (לא ידעו).$q$, 4, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$unlikely$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$un-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה — הופך את המשמעות$q$, $q$unlikely$q$, $q$Given the strength of the opposing team, it seems __________ that our players will reach the final, though a surprise is always possible.$q$, $q$["alike", "likelihood", "unlikely", "likely"]$q$::jsonb, 3, $q$["alike פירושו דומה. מילה אחרת לגמרי שרק חולקת אותיות עם likely.", "likelihood הוא שם עצם (סבירות). אחרי seems דרוש שם תואר.", "נכון. un + likely = לא סביר. הרמזים: strength of the opposing team, ו-though שמציג את ההפתעה כיוצאת דופן.", "likely פירושו סביר. אבל היריבה חזקה, ו-though a surprise is possible מראה שהציפייה היא לכישלון."]$q$::jsonb, $q$un + likely = לא סביר. though בסוף המשפט מציג את החריג — ומה שלפניו הוא הכלל. אם ההפתעה היא החריג, הכלל הוא שלא יצליחו.$q$, 5, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$invisible$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$in-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה (in-, וגם il-/ir- לפני l/r)$q$, $q$invisible$q$, $q$The tiny insects are almost __________ to the naked eye, and most people never notice them at all.$q$, $q$["invisible", "visible", "vision", "visibly"]$q$::jsonb, 1, $q$["נכון. in + visible = בלתי נראה. הרמז: never notice them at all.", "visible פירושו נראה. אם החרקים היו נראים, אנשים היו מבחינים בהם.", "vision הוא שם עצם (ראייה). אחרי almost דרוש שם תואר.", "visibly הוא תואר הפועל (באופן גלוי) ואינו יכול לתאר את the insects אחרי are."]$q$::jsonb, $q$in + visible = בלתי נראה. הפועל notice בהמשך המשפט עם never הוא הרמז לכיוון השלילי.$q$, 3, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$illegal$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$in-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה (in-, וגם il-/ir- לפני l/r)$q$, $q$illegal$q$, $q$Parking on this street is __________ during the day, and cars left here are usually towed away within an hour.$q$, $q$["legal", "legally", "illegal", "legality"]$q$::jsonb, 3, $q$["legal פירושו חוקי. אם החניה הייתה חוקית, המכוניות לא היו נגררות.", "legally הוא תואר הפועל (באופן חוקי) ואינו יכול לבוא אחרי is כתיאור של Parking.", "נכון. il + legal = לא חוקי. il- היא צורת in- לפני l. הרמז: towed away — עונש על חניה אסורה.", "legality הוא שם עצם (חוקיות). אחרי is דרוש שם תואר שמתאר את החניה."]$q$::jsonb, $q$il + legal = לא חוקי. in- לפני l הופכת ל-il: illegal, illogical, illiterate. חפשו תוצאה שלילית במשפט (towed away).$q$, 4, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$insufficient$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$in-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה (in-, וגם il-/ir- לפני l/r)$q$, $q$insufficient$q$, $q$The evidence presented by the prosecution was __________ to prove guilt, and the judge therefore ordered the defendant released.$q$, $q$["sufficiency", "insufficient", "sufficiently", "sufficient"]$q$::jsonb, 2, $q$["sufficiency הוא שם עצם (די, מספיקות). אחרי was דרוש שם תואר.", "נכון. in + sufficient = לא מספיק. הרמז: ordered the defendant released — התביעה נכשלה.", "sufficiently הוא תואר הפועל (במידה מספקת) ואינו יכול לתאר את the evidence אחרי was.", "sufficient פירושו מספיק. אם הראיות הספיקו להוכחת אשמה, הנאשם לא היה משוחרר."]$q$::jsonb, $q$in + sufficient = לא מספיק. therefore אחרי החסר מציג תוצאה — ואם התוצאה היא שחרור הנאשם, הראיות לא הספיקו.$q$, 5, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$impatient$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$im-$q$, $q$prefix$q$, $q$NEGATION$q$, $q$שלילה לפני b/m/p$q$, $q$impatient$q$, $q$The customers grew __________ as the delay stretched past an hour, and several of them left without buying anything.$q$, $q$["patience", "patiently", "impatient", "patient"]$q$::jsonb, 3, $q$["patience הוא שם עצם (סבלנות). אחרי grew (במובן נעשו) דרוש שם תואר.", "patiently הוא תואר הפועל (בסבלנות) ואינו יכול לתאר את the customers אחרי grew.", "נכון. im + patient = חסר סבלנות. הרמז: left without buying — איבדו סבלנות.", "patient פירושו סבלני. לקוחות סבלניים לא עוזבים בגלל עיכוב."]$q$::jsonb, $q$im + patient = חסר סבלנות. grew + שם תואר פירושו נעשו (grew tired, grew angry). שימו לב ש-patient כשם עצם פירושו מטופל — כאן זה תואר.$q$, 4, $q$shabbat batch 2026-09-05, family=NEGATION$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$disappeared$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$dis-$q$, $q$prefix$q$, $q$REVERSE$q$, $q$היפוך הפעולה — עושה את ההפך$q$, $q$disappeared$q$, $q$The fog __________ within minutes once the sun rose, revealing a valley that had been hidden all morning.$q$, $q$["reappeared", "appeared", "appearance", "disappeared"]$q$::jsonb, 4, $q$["reappeared פירושו הופיע שוב. re- מסמנת חזרה, וזה ההפך ממה שקורה לערפל כשהשמש זורחת.", "appeared פירושו הופיע. אבל הערפל היה קיים כל הבוקר, והמשפט מתאר את היעלמותו — ולכן נחשף העמק.", "appearance הוא שם עצם (הופעה, מראה). אחרי The fog דרוש פועל.", "נכון. dis + appear = להיעלם. הרמז: revealing a valley that had been hidden — הערפל הלך."]$q$::jsonb, $q$dis + appear = להיעלם. revealing (חושף) אחרי החסר אומר שמשהו הסתלק — פעולה הפוכה להופעה.$q$, 3, $q$shabbat batch 2026-09-05, family=REVERSE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$dishonest$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$dis-$q$, $q$prefix$q$, $q$REVERSE$q$, $q$היפוך הפעולה — עושה את ההפך$q$, $q$dishonest$q$, $q$The salesman was fired after several customers complained that he had been __________ about the condition of the used cars he sold.$q$, $q$["honesty", "honest", "honestly", "dishonest"]$q$::jsonb, 4, $q$["honesty הוא שם עצם (יושר). אחרי had been דרוש שם תואר.", "honest פירושו ישר, כן. אבל לקוחות לא מתלוננים על מוכר ישר, ואיש לא מפוטר על כך.", "honestly הוא תואר הפועל (בכנות) ואינו יכול לתאר את המוכר אחרי had been.", "נכון. dis + honest = לא ישר. הרמזים: complained ו-fired — התנהגות שלילית."]$q$::jsonb, $q$dis + honest = לא ישר. dis- גם שוללת תארים: dishonest, disloyal, dissimilar. complained ו-fired הם רמזים לתוצאה של התנהגות שלילית.$q$, 4, $q$shabbat batch 2026-09-05, family=REVERSE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$decreased$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$de-$q$, $q$prefix$q$, $q$REVERSE$q$, $q$הסרה, ביטול, ירידה$q$, $q$decreased$q$, $q$Since the new bicycle lanes were built, the number of cars entering the city center has __________ by almost a quarter.$q$, $q$["decreased", "decrease", "increased", "creased"]$q$::jsonb, 1, $q$["נכון. de + crease = לרדת, לפחות. הרמז: נתיבי אופניים חדשים גורמים לפחות מכוניות במרכז העיר.", "decrease כפועל בצורת המקור אינו יכול לבוא אחרי has; דרוש past participle: has decreased.", "increased פירושו עלה. אבל נתיבי אופניים נועדו להפחית מכוניות, ו-by almost a quarter מתאר ירידה בהקשר זה.", "creased פירושו קומט (crease = קמט). מילה אחרת לגמרי שרק נראית כמו השורש."]$q$::jsonb, $q$de + crease = לרדת (ההפך מ-increase = לעלות). de- מסמנת הסרה או ירידה: defrost (להפשיר), devalue (להוריד ערך). הסיבה במשפט (Since...) קובעת את הכיוון.$q$, 5, $q$shabbat batch 2026-09-05, family=REVERSE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$rewrite$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$re-$q$, $q$prefix$q$, $q$AGAIN$q$, $q$שוב, מחדש$q$, $q$rewrite$q$, $q$The editor asked the author to __________ the final chapter, since the first version had confused every reader who tested it.$q$, $q$["write", "rewrite", "writer", "writing"]$q$::jsonb, 2, $q$["write פירושו לכתוב. אבל הפרק כבר נכתב (the first version), ולכן דרושה כתיבה מחדש.", "נכון. re + write = לכתוב מחדש. הרמז: the first version had confused — הגרסה הראשונה קיימת ונכשלה.", "writer הוא אדם (סופר). אחרי asked the author to דרוש פועל.", "writing הוא שם עצם (כתיבה) או צורת -ing. to writing the chapter אינו מבנה תקין."]$q$::jsonb, $q$re + write = לכתוב מחדש. הביטוי the first version הוא רמז ישיר ל-re-: אם הייתה גרסה ראשונה, עכשיו עושים שוב.$q$, 3, $q$shabbat batch 2026-09-05, family=AGAIN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$restore$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$re-$q$, $q$prefix$q$, $q$AGAIN$q$, $q$שוב, מחדש$q$, $q$restore$q$, $q$Experts spent five years working to __________ the palace to the condition it had been in before the fire of 1834.$q$, $q$["restore", "storage", "store", "restored"]$q$::jsonb, 1, $q$["נכון. re + store = לשחזר, להחזיר למצב הקודם. הרמז: the condition it had been in before the fire.", "storage הוא שם עצם (אחסון). אחרי working to דרוש פועל.", "store פירושו לאחסן. לאחסן ארמון אינו הגיוני, והמשפט מתאר החזרה למצב קודם.", "restored היא צורת עבר. אחרי to דרושה צורת המקור: to restore."]$q$::jsonb, $q$re + store = לשחזר. before the fire הוא רמז לזמן קודם שאליו חוזרים — ו-re- פירושה חזרה למצב הזה.$q$, 4, $q$shabbat batch 2026-09-05, family=AGAIN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$recurring$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$re-$q$, $q$prefix$q$, $q$AGAIN$q$, $q$שוב, מחדש$q$, $q$recurring$q$, $q$Flooding in the lower town is a __________ problem: it has happened almost every winter for the past twenty years.$q$, $q$["current", "recurring", "currency", "occurring"]$q$::jsonb, 2, $q$["current פירושו נוכחי. זה מתאר את ההווה בלבד, ולא בעיה שחוזרת מדי חורף.", "נכון. re + cur (לקרות) + ing = חוזר ונשנה. הרמז: almost every winter for twenty years.", "currency הוא שם עצם (מטבע). אין לו קשר לשיטפונות, והוא רק דומה בכתיב.", "occurring פירושו מתרחש. זה נכון דקדוקית אבל לא מבטא את החזרה שהמשפט מדגיש — every winter."]$q$::jsonb, $q$re + cur + ing = חוזר ונשנה (recur = לקרות שוב). every winter / for twenty years הם רמזים לחזרה — ו-re- היא התחילית של חזרה.$q$, 6, $q$shabbat batch 2026-09-05, family=AGAIN$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$misplaced$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$mis-$q$, $q$prefix$q$, $q$WRONGLY$q$, $q$בטעות, באופן שגוי$q$, $q$misplaced$q$, $q$I must have __________ my keys somewhere in the house, because I have searched every room and still cannot find them.$q$, $q$["misplaced", "placed", "placement", "replaced"]$q$::jsonb, 1, $q$["נכון. mis + place = להניח במקום הלא נכון, לאבד. הרמז: cannot find them.", "placed פירושו הנחתי. זה לא מסביר למה אי אפשר למצוא את המפתחות.", "placement הוא שם עצם (השמה, מיקום). אחרי must have דרוש past participle.", "replaced פירושו החלפתי. re- כאן פירושה במקום, לא שוב — ואיש לא מחליף מפתחות שהוא מחפש."]$q$::jsonb, $q$mis + place = לשים במקום לא נכון. must have + פועל בעבר הוא ניחוש על העבר, ו-cannot find הוא הרמז לטעות.$q$, 3, $q$shabbat batch 2026-09-05, family=WRONGLY$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$misjudged$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$mis-$q$, $q$prefix$q$, $q$WRONGLY$q$, $q$בטעות, באופן שגוי$q$, $q$misjudged$q$, $q$The captain __________ the distance to the shore and ordered the anchor dropped far too early, leaving the passengers a long swim.$q$, $q$["judgment", "judged", "misjudged", "prejudged"]$q$::jsonb, 3, $q$["judgment הוא שם עצם (שיפוט, הערכה). אחרי The captain דרוש פועל.", "judged פירושו העריך. ההערכה נעשתה, אבל התוצאה (far too early) מראה שהיא הייתה שגויה.", "נכון. mis + judge = לשפוט לא נכון, לטעות בהערכה. הרמז: far too early ותוצאה לא רצויה — long swim.", "prejudged פירושו שפט מראש, מתוך דעה קדומה. pre- מסמנת לפני, לא טעות."]$q$::jsonb, $q$mis + judge = לטעות בשיפוט. too early / too late במשפט הם סימנים לטעות בהערכה — משפחת mis-.$q$, 5, $q$shabbat batch 2026-09-05, family=WRONGLY$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$misspelled$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$mis-$q$, $q$prefix$q$, $q$WRONGLY$q$, $q$בטעות, באופן שגוי$q$, $q$misspelled$q$, $q$The winner's name was __________ on the trophy, so the club had to order a new one before the ceremony.$q$, $q$["dispelled", "spelling", "misspelled", "spelled"]$q$::jsonb, 3, $q$["dispelled פירושו הפיג, סילק (ספק, חשש). מילה אחרת שרק נשמעת דומה.", "spelling הוא שם עצם (איות). was spelling on the trophy אינו מבנה הגיוני כאן.", "נכון. mis + spell = לאיית לא נכון. הרמז: had to order a new one — הגביע היה פגום.", "spelled פירושו אוית. אם השם אוית כראוי, לא היה צורך בגביע חדש."]$q$::jsonb, $q$mis + spell = לאיית לא נכון. כשמשהו צריך להיעשות מחדש (order a new one), חפשו mis- שמסבירה למה.$q$, 4, $q$shabbat batch 2026-09-05, family=WRONGLY$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$overslept$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$over-$q$, $q$prefix$q$, $q$DEGREE$q$, $q$יותר מדי, במידה מוגזמת$q$, $q$overslept$q$, $q$He __________ on the morning of the exam and arrived at the hall just as the doors were being closed.$q$, $q$["overslept", "slept", "asleep", "sleepy"]$q$::jsonb, 1, $q$["נכון. over + slept = ישן יותר מדי, איחר לקום. הרמז: just as the doors were being closed.", "slept פירושו ישן. כולם ישנים בלילה; המשפט מסביר איחור, ולכן דרושה מילה שמבטאת עודף.", "asleep הוא שם תואר (ישן, במצב שינה). He asleep on the morning אינו משפט תקין.", "sleepy הוא שם תואר (ישנוני). אחרי He דרוש פועל בעבר."]$q$::jsonb, $q$over + sleep = לישון יותר מדי. over- + פועל = לעשות יותר מדי: overeat, overwork, overspend. איחור הוא הרמז.$q$, 3, $q$shabbat batch 2026-09-05, family=DEGREE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$overreacted$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$over-$q$, $q$prefix$q$, $q$DEGREE$q$, $q$יותר מדי, במידה מוגזמת$q$, $q$overreacted$q$, $q$Critics said the school had __________ by closing for a whole week because of a single case of mild illness.$q$, $q$["overreacted", "reacted", "reaction", "underreacted"]$q$::jsonb, 1, $q$["נכון. over + react = להגיב בהגזמה. הרמז: a whole week מול a single case of mild illness.", "reacted פירושו הגיב. אבל המשפט מציג ביקורת — סגירה של שבוע שלם בגלל מקרה קל אחד — ולכן דרושה מילה של הגזמה.", "reaction הוא שם עצם (תגובה). אחרי had דרוש past participle.", "underreacted פירושו הגיב פחות מדי. זה ההפך: כאן התגובה הייתה חזקה מדי."]$q$::jsonb, $q$over + react = להגיב בהגזמה. חוסר יחס במשפט (whole week מול single mild case) הוא סימן ל-over-.$q$, 5, $q$shabbat batch 2026-09-05, family=DEGREE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
  if not exists (select 1 from affix_items where target_word=$q$underpaid$q$ and generation_batch='affix_shabbat_2026-09-05') then
    insert into affix_items(affix, affix_type, family_code, meaning_he, target_word, stem, options, correct_option, explanations_he, decode_note_he, difficulty_pos, qa_note, generation_batch, is_published) values
    ($q$under-$q$, $q$prefix$q$, $q$DEGREE$q$, $q$פחות מדי, בחסר$q$, $q$underpaid$q$, $q$Many nurses feel __________ for the long hours they work, and some have left the profession for better-paying jobs.$q$, $q$["payment", "paid", "overpaid", "underpaid"]$q$::jsonb, 4, $q$["payment הוא שם עצם (תשלום). אחרי feel דרוש שם תואר, לא שם עצם.", "paid פירושו קיבל שכר. feel paid אינו מבטא את התלונה שהמשפט מתאר.", "overpaid פירושו מקבל שכר גבוה מדי. מי שמקבל יותר מדי לא עוזב בשביל שכר טוב יותר.", "נכון. under + paid = מקבל שכר נמוך מדי. הרמז: left... for better-paying jobs."]$q$::jsonb, $q$under + paid = מקבל פחות מדי. better-paying jobs בהמשך אומר שהשכר הנוכחי נמוך — כיוון under.$q$, 4, $q$shabbat batch 2026-09-05, family=DEGREE$q$, 'affix_shabbat_2026-09-05', true);
  end if;
end $$;
