-- QA לפריטי הכיול affix-calib-01 (שבת 2026-09-05): פיזור מיקום התשובה (היה תמיד #2), אפוסטרוף, family_code TIME→TIME_PLACE. מותנה ב-correct_option=2 ולכן אידמפוטנטי.
update affix_items set options='["construct", "construction", "reconstruct", "constructive"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->2, explanations_he->1, explanations_he->3), correct_option=3, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='a55bd632-a5cd-423f-86aa-ebec98c0386a' and correct_option=2;
update affix_items set options='["specialist", "special", "specialize", "specially"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->1, explanations_he->0, explanations_he->2, explanations_he->3), correct_option=1, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='1c0d154c-fdea-4c0e-85d7-a48f7388d5df' and correct_option=2;
update affix_items set options='["read", "reader", "reading", "readable"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->2, explanations_he->3, explanations_he->1), correct_option=4, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='475b6275-4b1f-4ad4-80f3-8c65ead03440' and correct_option=2;
update affix_items set options='["estimated", "overestimated", "underestimated", "estimation"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->1, explanations_he->2, explanations_he->3), correct_option=2, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='82dd80dd-754f-40e0-859c-2f2d3c6f65e7' and correct_option=2;
update affix_items set options='["precise", "precision", "precisely", "imprecise"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->2, explanations_he->3, explanations_he->1), correct_option=4, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='2109d5d2-40d2-4007-adb0-f06ce92d89e3' and correct_option=2;
update affix_items set options='["founded", "foundational", "unfounded", "refounded"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->2, explanations_he->1, explanations_he->3), correct_option=3, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='a851c63e-3ae9-4fcc-af74-13209c18bc2b' and correct_option=2;
update affix_items set options='["conclusion", "conclude", "conclusive", "conclusively"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->1, explanations_he->0, explanations_he->2, explanations_he->3), correct_option=1, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='fc7b60e1-6f99-4c89-b74b-661e364bec06' and correct_option=2;
update affix_items set options='["proved", "approved", "proof", "disproved"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->2, explanations_he->3, explanations_he->1), correct_option=4, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='76aac704-2dc0-4ce0-b61d-618fe4be2efb' and correct_option=2;
update affix_items set options='["assembled", "preassembled", "disassembled", "assembly"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->1, explanations_he->2, explanations_he->3), correct_option=2, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='c1cc4e5c-c370-410c-a84e-cfdc151f8dae' and correct_option=2;
update affix_items set options='["stable", "stability", "stabilize", "stably"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->2, explanations_he->1, explanations_he->3), correct_option=3, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='a43bdfee-ee2f-49a5-a0e7-5921274fe8d9' and correct_option=2;
update affix_items set options='["pointless", "point", "pointed", "appointed"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->1, explanations_he->0, explanations_he->2, explanations_he->3), correct_option=1, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='4400a070-6e7b-45da-925b-e7196895173f' and correct_option=2;
update affix_items set options='["interpreted", "interpretation", "interpreter", "misinterpreted"]'::jsonb, explanations_he=jsonb_build_array(explanations_he->0, explanations_he->2, explanations_he->3, explanations_he->1), correct_option=4, qa_note='shabbat QA 2026-09-05: reordered options (was always #2)', updated_at=now() where id='369058d6-37cb-4ba8-92ae-d1f5a60e023e' and correct_option=2;
update affix_items set stem=replace(stem,'The researchers main','The researchers'' main'), qa_note=coalesce(qa_note,'')||'; fixed apostrophe' where id='fc7b60e1-6f99-4c89-b74b-661e364bec06';
update affix_items set family_code='TIME_PLACE' where family_code='TIME';
