do $$ declare v_pid uuid; begin

  if not exists (select 1 from reading_passages where title = $q$How Hebrew Learned to Speak Again$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$How Hebrew Learned to Speak Again$q$, $q$For many centuries Hebrew was written and read constantly, yet almost nobody used it for ordinary daily conversation. Hebrew never died; it simply stopped being spoken. Jewish communities across Europe, North Africa and Asia prayed and studied in Hebrew, while speaking Yiddish, Ladino, Arabic or the local language at home. Scholars sometimes wrote letters and legal documents in Hebrew, and merchants from distant regions occasionally used it as a shared written code. The language was therefore alive on the page, but it had lost the everyday vocabulary that living speech requires.

That situation began to change in the late nineteenth century, when Jewish immigration to Ottoman Palestine brought together speakers of many different languages. Eliezer Ben-Yehuda, who arrived in Jerusalem in 1881, insisted on raising his son with Hebrew alone, an experiment that many neighbours considered strange. He compiled a vast dictionary and invented terms for objects the ancient texts had never named, drawing new words from old roots. Ben-Yehuda alone could not have revived a language, however, and his real importance lay in the movement that formed around him.

The decisive step was taken in schools, where teachers chose to give every lesson in Hebrew, even to children who barely understood it. A generation of pupils grew up hearing the language in the playground as well as the classroom, and they began to speak it naturally. Newspapers, theatre groups and public argument supplied the slang, insults and jokes that no dictionary could invent. By the 1920s Hebrew had been recognised as an official language of British Mandate Palestine.

Linguists still debate how far modern Hebrew resembles the language of the Bible, since its grammar and sound carry clear European traces. What is not disputed is the outcome: a language preserved mainly in texts became the first tongue of millions of ordinary speakers. No other language has made that journey so completely, which is why the Hebrew case is studied wherever people try to save an endangered tongue.$q$, $q$culture / language$q$, 5, 327, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$What is the main idea of the passage?$q$, $q$["Hebrew survived in writing for centuries and was turned into an everyday spoken language mainly through schools and a wider social movement.", "Eliezer Ben-Yehuda single-handedly restored Hebrew by compiling a dictionary and raising his son in the language.", "Jewish communities in Europe, North Africa and Asia used several different spoken languages at home.", "Modern Hebrew differs from biblical Hebrew in its grammar and in the sound of its speakers."]$q$::jsonb, 0, $q$["נכון. זהו הרעיון המרכזי של הקטע כולו: שפה ששרדה בכתב הפכה לשפת דיבור יומיומית, בעיקר דרך בתי הספר והתנועה החברתית שסביבם.", "לא נכון. הפסקה השנייה כותבת במפורש שבן-יהודה לבדו לא היה יכול להחיות שפה, ושחשיבותו האמיתית הייתה בתנועה שנוצרה סביבו.", "לא נכון. זו קביעה נכונה מהפסקה הראשונה, אך היא פרט רקע צר ולא הרעיון המרכזי של הקטע.", "לא נכון. זו קביעה נכונה מהפסקה האחרונה, אך היא הערה משנית ולא הרעיון המרכזי של הקטע."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E2, passage=hebrew-revival, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the third paragraph is to —$q$, $q$["explain why European scholars doubt that modern Hebrew resembles the biblical language.", "describe how classroom teaching and public life turned Hebrew into a spoken tongue.", "list the languages that Jewish communities spoke at home before the revival began.", "present Ben-Yehuda's dictionary work and the new words he built from ancient roots."]$q$::jsonb, 1, $q$["לא נכון. זהו תוכן הפסקה האחרונה — הדיון על הדמיון לעברית המקראית — ולא הפסקה השלישית.", "נכון. הפסקה השלישית מתארת כיצד ההוראה בכיתה, לצד עיתונות, תיאטרון וויכוח ציבורי, הפכה את העברית לשפה מדוברת.", "לא נכון. זהו תוכן הפסקה הראשונה — השפות שדוברו בבית — ולא הפסקה השלישית.", "לא נכון. זהו תוכן הפסקה השנייה — המילון והמילים החדשות של בן-יהודה — ולא הפסקה השלישית."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=hebrew-revival, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the second paragraph, what did Ben-Yehuda do when the ancient texts lacked a word he needed?$q$, $q$["He borrowed the missing term directly from the languages his neighbours spoke.", "He avoided the subject entirely and wrote about it in another language.", "He created a new word by building it from an existing old root.", "He asked the schools of Jerusalem to vote on a suitable replacement term."]$q$::jsonb, 2, $q$["לא נכון. הפסקה מציינת שהוא גזר מילים חדשות משורשים עתיקים, ולא ששאל אותן משפות השכנים.", "לא נכון. הפסקה מתארת יצירת מונחים חדשים, ולא הימנעות מהנושא.", "נכון. הפסקה השנייה כותבת שהוא המציא מונחים לעצמים שהטקסטים העתיקים מעולם לא נקבו בשמם, תוך גזירת מילים חדשות משורשים ישנים.", "לא נכון. הפסקה אינה מזכירה הצבעה כלשהי של בתי ספר בירושלים."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["drawing new words from old roots"]$q$::jsonb, $q$shabbat batch E2, passage=hebrew-revival, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the third paragraph, the word "decisive" most nearly means —$q$, $q$["Carried out with unusual speed and very little planning", "Producing the outcome that settled the matter", "Requiring a formal vote before it could take effect", "Regarded at the time as controversial and unpopular"]$q$::jsonb, 1, $q$["לא נכון. המילה אינה עוסקת במהירות או בהיעדר תכנון.", "נכון. 'decisive' פירושו מכריע — הצעד שהביא לתוצאה וסגר את העניין, וכאן זהו המעבר להוראה בעברית בבתי הספר.", "לא נכון. המילה אינה קשורה להליך הצבעה רשמי.", "לא נכון. המילה מתארת את חשיבות הצעד ולא את מידת הפופולריות שלו."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["The decisive step was taken in schools"]$q$::jsonb, $q$shabbat batch E2, passage=hebrew-revival, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the last paragraph that —$q$, $q$["modern Hebrew is identical to the Hebrew written in the Bible.", "few people are interested in the history of endangered languages today.", "the revival of Hebrew is treated as an unusually successful example of language recovery.", "linguists have concluded that the revival of Hebrew was a complete failure."]$q$::jsonb, 2, $q$["לא נכון. הפסקה מציינת שבעברית המודרנית ניכרים עקבות אירופיים בדקדוק ובהגייה, ולכן אינה זהה לעברית המקראית.", "לא נכון. הפסקה כותבת שהמקרה העברי נלמד בכל מקום שבו מנסים להציל שפה בסכנה, כלומר יש עניין רב בנושא.", "נכון. הפסקה מציינת ששום שפה אחרת לא עשתה את המסע הזה בשלמות כזו, ושלכן לומדים את המקרה בכל ניסיון להציל שפה — משמע הוא נחשב הצלחה יוצאת דופן.", "לא נכון. הפסקה כותבת שהתוצאה אינה שנויה במחלוקת: השפה הפכה לשפת אם של מיליונים."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=hebrew-revival, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$How the Olympic Games Were Rebuilt$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$How the Olympic Games Were Rebuilt$q$, $q$The ancient Olympic Games were held at Olympia in Greece for roughly a thousand years before Roman authorities ended them in the fourth century. Athletes competed in running, wrestling and chariot racing, and victory brought fame to the winner's home city. The site was excavated by German archaeologists in the 1870s, and their discoveries attracted wide public attention across Europe. Educated readers who admired classical Greece began to wonder whether such a festival could be created again. Several small revivals were attempted in Greece and in England, though none of them lasted.

The person who turned the idea into an institution was Pierre de Coubertin, a French aristocrat interested in education reform. He believed that organised sport built character, and he admired the athletic tradition of English schools. In 1894 he gathered delegates from several countries at the Sorbonne in Paris and persuaded them to support an international games. The meeting created the International Olympic Committee and chose Athens as the host of the first modern Olympics. Those games opened in 1896 with a few hundred competitors, almost all of them men, from a small group of nations.

The early Olympics were far from the spectacle they later became, and some were nearly ruined by being attached to world fairs. The events in Paris in 1900 and in St. Louis in 1904 stretched over months and competed for attention with commercial exhibitions. Stockholm in 1912 offered a clearer model, with a purpose-built stadium and a tighter programme of events. Women's participation grew slowly, and the number of competing nations rose steadily through the twentieth century. What began as one man's attempt to imitate antiquity had become the largest recurring event in world sport.$q$, $q$culture / sport$q$, 4, 278, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$An appropriate title for this text would be —$q$, $q$["The Excavation of Olympia by German Archaeologists", "Why the Paris and St. Louis Games Were Disappointing", "From an Ancient Festival to a Modern International Institution", "Pierre de Coubertin and the Reform of French Education"]$q$::jsonb, 2, $q$["לא נכון. החפירות מוזכרות בפסקה הראשונה כפרט רקע בלבד, ואינן נושא הקטע.", "לא נכון. משחקי פריז וסנט לואיס הם דוגמה אחת בפסקה השלישית ולא נושא הקטע כולו.", "נכון. הקטע עוקב אחר הדרך מהפסטיבל היווני העתיק אל מוסד בינלאומי מודרני, וזהו בדיוק מהלך הטקסט.", "לא נכון. רפורמת החינוך היא פרט על קובֶּרטֶן בפסקה השנייה, ולא הנושא המרכזי."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E2, passage=modern-olympics, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, what renewed European interest in the ancient Games?$q$, $q$["A series of successful revivals staged in Greece and England.", "The archaeological excavation of the site at Olympia in the 1870s.", "A decision taken by the Roman authorities to permit the old festival again.", "The founding of the International Olympic Committee in the 1890s."]$q$::jsonb, 1, $q$["לא נכון. הפסקה מציינת שנעשו ניסיונות החייאה קטנים, אך אף אחד מהם לא החזיק מעמד.", "נכון. הפסקה כותבת שהחפירות של הארכיאולוגים הגרמנים בשנות ה-70 של המאה ה-19 משכו תשומת לב ציבורית רחבה באירופה.", "לא נכון. הרומאים דווקא הפסיקו את המשחקים במאה הרביעית, ולא התירו אותם מחדש.", "לא נכון. הוועד האולימפי הבינלאומי נוסד רק ב-1894, לאחר שהעניין כבר התעורר."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=modern-olympics, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The passage describes the 1896 Games as opening "with a few hundred competitors." According to that sentence, those athletes came from —$q$, $q$["every continent that was then known to European geographers.", "the schools of England and nowhere else at all.", "only those countries whose delegates attended the Sorbonne meeting.", "a small group of participating nations."]$q$::jsonb, 3, $q$["לא נכון. המשפט אינו מזכיר יבשות כלל, אלא קבוצה קטנה של מדינות.", "לא נכון. בתי הספר האנגליים מוזכרים בפסקה השנייה כמקור השראה לקוברטן, ולא כמקור המתחרים.", "לא נכון. הקטע אינו קושר בין רשימת המשלחות ב-1896 לבין המדינות שהשתתפו בכינוס בסורבון.", "נכון. המשפט מציין במפורש שהמתחרים הגיעו מקבוצה קטנה של מדינות."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["with a few hundred competitors, almost all of them men, from a small group of nations"]$q$::jsonb, $q$shabbat batch E2, passage=modern-olympics, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the last paragraph is to —$q$, $q$["explain how Coubertin persuaded delegates at the Sorbonne to support his plan.", "describe the events and the prizes of the ancient Games held at Olympia.", "show that the early modern Games were unsteady before the format settled.", "argue that world fairs were more popular than athletic competitions."]$q$::jsonb, 2, $q$["לא נכון. זהו תוכן הפסקה השנייה — הכינוס בסורבון — ולא הפסקה האחרונה.", "לא נכון. זהו תוכן הפסקה הראשונה — המשחקים העתיקים — ולא הפסקה האחרונה.", "נכון. הפסקה האחרונה מראה שהמשחקים המוקדמים היו רחוקים מיציבות, עד שסטוקהולם 1912 הציעה מודל ברור יותר.", "לא נכון. הפסקה אינה משווה את הפופולריות של ירידי העולם לזו של התחרויות."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=modern-olympics, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The statement that some early Games "were nearly ruined by being attached to world fairs" suggests that —$q$, $q$["the Games worked better once they stood on their own feet.", "world fairs refused to allow athletic competitions on their grounds.", "the Olympic movement earned most of its early income from commercial exhibitions.", "Coubertin deliberately planned the Games as part of commercial exhibitions."]$q$::jsonb, 0, $q$["נכון. הפסקה מנגידה בין המשחקים שנבלעו בירידים לבין סטוקהולם 1912, שהציעה אצטדיון ייעודי ותוכנית מרוכזת — כלומר המשחקים הצליחו יותר כשעמדו בפני עצמם.", "לא נכון. הקטע מתאר את ההפך: המשחקים אכן נערכו לצד הירידים.", "לא נכון. הקטע אינו מזכיר כלל את הכנסות התנועה האולימפית.", "לא נכון. הקטע אינו מייחס לקוברטן תכנון מכוון של שילוב זה."]$q$::jsonb, $q$inference$q$, $q$anchor$q$, $q$["some were nearly ruined by being attached to world fairs"]$q$::jsonb, $q$shabbat batch E2, passage=modern-olympics, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$The Penny Universities of London$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$The Penny Universities of London$q$, $q$Coffee reached Europe from the Ottoman world in the seventeenth century, and the drink arrived together with the institution built around it. The first English coffee house opened in Oxford around 1650, and London followed within a few years. For a penny, a customer could enter, take a dish of coffee and stay as long as he liked. The price gave the places their nickname: penny universities, where a small coin bought hours of conversation.

What made these rooms unusual was not the coffee but the mixing of people who would never have drunk together elsewhere. Taverns served alcohol and encouraged noise, whereas the coffee house rewarded argument, reading aloud and the exchange of news. Newspapers and pamphlets lay on the tables, and customers who could not afford them read for the price of a drink. Rank mattered less inside than outside, and a merchant might contradict a gentleman without giving offence.

Several modern institutions grew directly out of particular houses and the trades that gathered in them. Merchants and ship captains met at Edward Lloyd's house near the Thames to trade shipping news, and the insurance market of Lloyd's grew from it. Dealers in stocks were expelled from the Royal Exchange for rowdiness and moved to Jonathan's, which became an early home of the London stock market. Scientists connected with the Royal Society argued over experiments in nearby rooms before presenting their results formally.

Governments were not always pleased by so much unsupervised talk about politics. Charles II tried to close London's coffee houses in 1675, complaining that they spread false reports, but the order was withdrawn within days. The episode suggests how firmly the habit had settled, and the coffee house remained a centre of public discussion until newspapers and private clubs took over its role.$q$, $q$culture / food$q$, 5, 296, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$What is the main idea of the passage?$q$, $q$["The seventeenth-century coffee house was a cheap public space whose mixing of people helped produce newspapers, markets and lasting institutions.", "Coffee was introduced to Europe from the Ottoman world during the seventeenth century.", "Charles II attempted to close the coffee houses of London in 1675 and then withdrew the order.", "Taverns and coffee houses competed for the same customers throughout seventeenth-century England."]$q$::jsonb, 0, $q$["נכון. זהו הרעיון המרכזי: מרחב ציבורי זול שבו התערבבו אנשים, ומתוכו צמחו שווקים ומוסדות שהתקיימו זמן רב.", "לא נכון. זו קביעה נכונה מהפסקה הראשונה, אך היא נקודת פתיחה בלבד ולא הרעיון המרכזי.", "לא נכון. זו קביעה נכונה מהפסקה האחרונה, אך היא אירוע יחיד ולא הרעיון המרכזי של הקטע.", "לא נכון. הפונדקים מוזכרים בפסקה השנייה רק כניגוד, והקטע אינו עוסק בתחרות ביניהם."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E2, passage=coffee-houses, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["explain why the social mixing mattered more than the coffee itself.", "describe the founding of the Lloyd's insurance market beside the river Thames.", "record the price of admission and the nickname the houses acquired.", "report the attempt by Charles II to suppress political conversation in London."]$q$::jsonb, 0, $q$["נכון. הפסקה השנייה פותחת בכך שלא הקפה עשה את המקומות האלה יוצאי דופן אלא ערבוב האנשים, ומפרטת מה התאפשר בזכותו.", "לא נכון. זהו תוכן הפסקה השלישית — הקמת שוק הביטוח של לוידס — ולא הפסקה השנייה.", "לא נכון. זהו תוכן הפסקה הראשונה — מחיר הפני והכינוי — ולא הפסקה השנייה.", "לא נכון. זהו תוכן הפסקה האחרונה — ניסיונו של צ'ארלס השני — ולא הפסקה השנייה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=coffee-houses, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the third paragraph is to —$q$, $q$["explain how coffee first travelled from the Ottoman world into England.", "show that several lasting business and scientific institutions began in particular houses.", "describe the rules of behaviour that customers were expected to follow inside.", "argue that the Royal Exchange was more important than any coffee house was."]$q$::jsonb, 1, $q$["לא נכון. זהו תוכן הפסקה הראשונה — הגעת הקפה לאירופה — ולא הפסקה השלישית.", "נכון. הפסקה השלישית מביאה שלוש דוגמאות — לוידס, ג'ונתן'ס והחברה המלכותית — כדי להראות שמוסדים מתמשכים צמחו מבתי קפה מסוימים.", "לא נכון. הפסקה אינה מפרטת כללי התנהגות רשמיים; היחס בין מעמדות מתואר בפסקה השנייה.", "לא נכון. הפסקה מזכירה את הבורסה המלכותית רק כמקום שממנו גורשו הסוחרים, ואינה מדרגת חשיבות."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=coffee-houses, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the fourth paragraph, all of the following are true EXCEPT —$q$, $q$["Charles II ordered the closing of London's coffee houses in 1675.", "The order against the coffee houses was withdrawn within a few days.", "The king complained that the houses spread false reports among the public.", "Parliament passed a permanent law banning political talk inside coffee houses."]$q$::jsonb, 3, $q$["לא נכון. זו קביעה נכונה על פי הפסקה האחרונה, ולכן אינה החריג המבוקש — צ'ארלס השני אכן ניסה לסגור את בתי הקפה ב-1675.", "לא נכון. זו קביעה נכונה על פי הפסקה האחרונה, ולכן אינה החריג המבוקש — הצו אכן בוטל בתוך ימים.", "לא נכון. זו קביעה נכונה על פי הפסקה האחרונה, ולכן אינה החריג המבוקש — המלך אכן התלונן שהמקומות מפיצים דיווחים כוזבים.", "נכון. זו הקביעה השגויה — הפסקה אינה מזכירה חוק פרלמנטרי קבוע כלשהו, אלא צו מלכותי שבוטל במהירות."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["but the order was withdrawn within days"]$q$::jsonb, $q$shabbat batch E2, passage=coffee-houses, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the sentence "...and the insurance market of Lloyd's grew from it," the word "it" refers to —$q$, $q$["the shipping news that merchants and captains exchanged", "the coffee house kept by Edward Lloyd", "the river Thames beside which the house stood", "the Royal Exchange from which dealers were expelled"]$q$::jsonb, 1, $q$["לא נכון. חדשות הספנות הן מה שנסחר במקום, אך שוק הביטוח צמח מהמקום עצמו ונשא את שמו.", "נכון. המשפט מתאר את בית הקפה של אדוארד לויד ליד התמזה, ושוק הביטוח לוידס צמח ממנו — ולכן 'it' מתייחס לבית הקפה.", "לא נכון. הנהר מופיע רק כציון מיקום של הבית ואינו מה ששוק הביטוח צמח ממנו.", "לא נכון. הבורסה המלכותית מופיעה במשפט אחר, בהקשר של סוחרי המניות שעברו לג'ונתן'ס."]$q$::jsonb, $q$reference_word$q$, $q$anchor$q$, $q$["the insurance market of Lloyd's grew from it"]$q$::jsonb, $q$shabbat batch E2, passage=coffee-houses, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$From the Daguerreotype to the Snapshot$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$From the Daguerreotype to the Snapshot$q$, $q$In 1839 the French government announced a process developed by Louis Daguerre and gave it, in effect, to the world. A daguerreotype was a mirror-like image on a silvered copper plate, sharp in detail and impossible to copy. Sitters had to hold still for a long exposure, which is why early portraits look so solemn and stiff. The plates were fragile and were usually kept in small cases lined with velvet. Within twenty years the process was obsolete, replaced by negatives on glass that allowed many prints from one exposure.

Glass negatives made photography cheaper, yet they did not make it convenient. The wet collodion plate had to be coated, exposed and developed while still damp, so photographers carried a darkroom with them. Landscape and war photographers travelled with wagons full of chemicals, glass and tents. Dry plates, sold ready-made from the 1870s, freed the photographer from that burden. Exposures grew shorter, and for the first time a camera could record a moving figure without blurring it beyond recognition.

The decisive change came from George Eastman, who wanted photography to be as simple as using a pencil. His company replaced glass with flexible roll film and in 1888 sold a small camera already loaded with a hundred exposures. The owner pressed the button and sent the whole camera back to the factory, which developed the pictures and returned it reloaded. The advertising slogan promised that the customer pressed the button while the company did the rest. Photography stopped being a profession practised by specialists and became a habit of family life.$q$, $q$arts / photography$q$, 4, 259, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$An appropriate title for this text would be —$q$, $q$["The Chemistry of the Wet Collodion Plate Explained", "How Photography Became Cheap, Portable and Ordinary", "George Eastman and the Founding of an American Company", "Why Early Portrait Sitters Look Solemn and Stiff"]$q$::jsonb, 1, $q$["לא נכון. לוח הקולודיון הרטוב הוא שלב אחד בפסקה השנייה, ולא נושא הקטע.", "נכון. הקטע עוקב אחר המעבר מתהליך יקר ומסורבל לצילום זול, נייד ויומיומי, וזהו מהלכו המרכזי.", "לא נכון. איסטמן מופיע רק בפסקה השלישית, והקטע אינו עוסק בהקמת חברה.", "לא נכון. זהו פרט מהפסקה הראשונה, ולא הרעיון המרכזי של הקטע."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E2, passage=photography-snapshot, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, why do people in early portraits look stiff?$q$, $q$["The photographers instructed them to imitate classical statues.", "The silvered copper plates could not record any facial expression.", "They were required to remain completely motionless throughout a long exposure period.", "The cases the plates were kept in were small and narrow."]$q$::jsonb, 2, $q$["לא נכון. הפסקה אינה מזכירה הוראות לחקות פסלים.", "לא נכון. הפסקה מציינת שהתמונה הייתה חדה בפרטים, ולא שלא יכלה לתעד הבעות.", "נכון. הפסקה כותבת שהמצטלמים נאלצו לעמוד ללא תנועה במשך חשיפה ארוכה, ולכן הם נראים חמורי סבר ונוקשים.", "לא נכון. הקופסאות מוזכרות כאמצעי אחסון של הלוחות, ואין להן קשר להבעת המצטלמים."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=photography-snapshot, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["explain that cheaper negatives were still awkward to use until dry plates arrived.", "describe the announcement made by the French government in the year 1839.", "present the roll film camera that Eastman's company sold from 1888.", "argue that war photography was more difficult than landscape photography."]$q$::jsonb, 0, $q$["נכון. הפסקה פותחת בכך שהנגטיבים הוזילו את הצילום אך לא הפכו אותו לנוח, ומסתיימת בלוחות היבשים ששחררו את הצלם מהנטל.", "לא נכון. זהו תוכן הפסקה הראשונה — ההכרזה הצרפתית מ-1839 — ולא הפסקה השנייה.", "לא נכון. זהו תוכן הפסקה השלישית — מצלמת סרט הגליל של איסטמן — ולא הפסקה השנייה.", "לא נכון. הפסקה מזכירה את שני סוגי הצלמים יחד ואינה משווה ביניהם."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=photography-snapshot, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the first paragraph, the word "obsolete" is closest in meaning to —$q$, $q$["Illegal under a newly introduced government regulation", "Extremely expensive for most professional users", "No longer in use because something better exists", "Difficult to explain to an untrained observer"]$q$::jsonb, 2, $q$["לא נכון. המילה אינה קשורה לאיסור חוקי; הממשלה הצרפתית דווקא העניקה את התהליך לציבור.", "לא נכון. המשפט מדבר על החלפה בשיטה טובה יותר, ולא על מחיר.", "נכון. 'obsolete' פירושו יצא מכלל שימוש משום שהופיע דבר טוב יותר — כאן הנגטיבים על זכוכית שאפשרו הדפסות רבות.", "לא נכון. המילה אינה עוסקת בקושי להסביר את התהליך."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["Within twenty years the process was obsolete"]$q$::jsonb, $q$shabbat batch E2, passage=photography-snapshot, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the passage, customers who "sent the whole camera back to the factory" received —$q$, $q$["a refund of the purchase price once the film was used up.", "a set of glass negatives that they could print themselves at home.", "written instructions explaining how to develop the pictures correctly.", "their developed pictures and the same camera loaded with fresh film."]$q$::jsonb, 3, $q$["לא נכון. הפסקה אינה מזכירה החזר כספי כלשהו.", "לא נכון. הפסקה מציינת שהזכוכית הוחלפה בסרט גליל גמיש, ושהפיתוח נעשה במפעל.", "לא נכון. הפסקה מדגישה שהחברה עשתה את כל השאר, ולא שנשלחו הוראות פיתוח ללקוח.", "נכון. הפסקה כותבת שהמפעל פיתח את התמונות והחזיר את המצלמה טעונה מחדש."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["sent the whole camera back to the factory"]$q$::jsonb, $q$shabbat batch E2, passage=photography-snapshot, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$The Stone That Made Hieroglyphs Speak$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$The Stone That Made Hieroglyphs Speak$q$, $q$Knowledge of how to read hieroglyphs disappeared in late antiquity, and for well over a thousand years the script was silent. European scholars assumed that each sign stood for an idea rather than a sound, and they produced confident but useless translations. This assumption blocked progress, because it treated a writing system as a collection of symbols instead of a record of speech. The mistake lasted until an accident of war supplied the missing evidence.

In 1799 French soldiers rebuilding a fort near the town of Rashid, which Europeans called Rosetta, uncovered a slab of dark stone. It carried the same decree, issued by priests in 196 BC, in three scripts: hieroglyphic, demotic and Greek. Because scholars could read Greek, the stone offered a controlled comparison between a known text and an unknown one. British forces took the stone after defeating the French in Egypt, and it has been in the British Museum since 1802.

Thomas Young, an English physician and physicist, made the first real advances by studying the demotic section. He showed that the oval rings called cartouches enclosed royal names and that some signs recorded sounds. The full decipherment belongs to Jean-Francois Champollion, who announced his results in 1822 after years of work. Champollion knew Coptic, the late form of the Egyptian language written in Greek letters, and that knowledge let him hear the words behind the signs.

He demonstrated that hieroglyphs combined sound signs, word signs and silent markers that indicated the category of a word. The system was neither a picture code nor an alphabet, but a mixture that had confused everyone who expected one or the other. Once the principle was accepted, thousands of inscriptions became readable, and three thousand years of Egyptian administration, poetry and complaint could be studied directly.$q$, $q$culture / language$q$, 5, 293, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$What is the main idea of the passage?$q$, $q$["A trilingual inscription and a knowledge of Coptic allowed scholars to abandon a false assumption and read hieroglyphs again.", "French soldiers rebuilding a fort in Egypt uncovered a slab of dark stone in the year 1799.", "Thomas Young studied the demotic script and identified the meaning of the oval cartouches.", "The British Museum has displayed the Rosetta Stone continuously since the year 1802."]$q$::jsonb, 0, $q$["נכון. זהו מהלך הקטע כולו: הנחה שגויה חסמה את הקריאה, ואבן תלת-לשונית יחד עם ידיעת הקופטית אפשרו לפענח את הכתב.", "לא נכון. זו קביעה נכונה מהפסקה השנייה, אך היא פרט אחד בשרשרת ולא הרעיון המרכזי.", "לא נכון. זו קביעה נכונה מהפסקה השלישית, אך היא שלב ביניים ולא הרעיון המרכזי של הקטע.", "לא נכון. זו קביעה נכונה מהפסקה השנייה, אך היא פרט שולי לחלוטין."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E2, passage=rosetta-stone, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, why did early European attempts to read hieroglyphs fail?$q$, $q$["The surviving inscriptions had been damaged beyond any possible repair.", "Scholars wrongly assumed that each sign represented an idea and not a sound.", "No scholar in Europe was able to read ancient Greek at that time.", "The Egyptian language itself had been completely forgotten by everyone."]$q$::jsonb, 1, $q$["לא נכון. הפסקה אינה מזכירה נזק לכתובות כסיבה לכישלון.", "נכון. הפסקה כותבת שהחוקרים הניחו שכל סימן מייצג רעיון ולא צליל, והנחה זו חסמה את ההתקדמות.", "לא נכון. הפסקה השנייה מציינת דווקא שהחוקרים ידעו לקרוא יוונית.", "לא נכון. הפסקה השלישית מציינת שהקופטית, צורתה המאוחרת של המצרית, עדיין הייתה ידועה."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=rosetta-stone, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["explain how the stone was found and why its three scripts were useful.", "describe the years of work that Champollion devoted to the problem.", "criticise the British for removing the stone from Egypt after the war.", "list the categories of sign that Egyptian writing was found to contain."]$q$::jsonb, 0, $q$["נכון. הפסקה השנייה מספרת על גילוי האבן ב-1799 ומסבירה שהיא אפשרה השוואה מבוקרת בין טקסט ידוע לטקסט לא ידוע.", "לא נכון. זהו תוכן הפסקה השלישית — עבודתו של שמפוליון — ולא הפסקה השנייה.", "לא נכון. הפסקה מדווחת על העברת האבן בלי לבקר את הבריטים.", "לא נכון. זהו תוכן הפסקה האחרונה — סוגי הסימנים — ולא הפסקה השנייה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=rosetta-stone, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the third paragraph that —$q$, $q$["Young and Champollion worked closely together on the decipherment.", "the Greek section of the stone was the hardest part to translate.", "knowing a related living language helped more than studying the stone alone.", "Coptic was written in the same signs as the demotic script was."]$q$::jsonb, 2, $q$["לא נכון. הפסקה מתארת את שניהם בנפרד ואינה מזכירה עבודה משותפת.", "לא נכון. הפסקה השנייה מציינת שהיוונית הייתה החלק הידוע והקריא.", "נכון. הפסקה מציינת ששמפוליון ידע קופטית, ושידע זה איפשר לו לשמוע את המילים שמאחורי הסימנים — יתרון שלא נבע מהאבן עצמה.", "לא נכון. הפסקה כותבת במפורש שהקופטית נכתבה באותיות יווניות."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=rosetta-stone, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the third paragraph, the word "decipherment" most nearly means —$q$, $q$["The physical restoration of a damaged ancient monument", "The public display of an object inside a large museum", "The act of working out how an unknown script is read", "The translation of a text from Greek into a modern language"]$q$::jsonb, 2, $q$["לא נכון. המילה אינה עוסקת בשחזור פיזי של אנדרטה.", "לא נכון. המילה אינה עוסקת בהצגה מוזיאלית, אף שהאבן אכן מוצגת במוזיאון הבריטי.", "נכון. 'decipherment' הוא פענוח — הבנת האופן שבו נקרא כתב לא מוכר, וזה בדיוק מה ששמפוליון השיג ב-1822.", "לא נכון. המילה אינה מתארת תרגום מיוונית, אלא פענוח של הכתב המצרי."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["The full decipherment belongs to Jean-Francois Champollion"]$q$::jsonb, $q$shabbat batch E2, passage=rosetta-stone, q5$q$, 5, true);
  end if;
end $$;