do $$ declare v_pid uuid; begin

  if not exists (select 1 from reading_passages where title = $q$The Tomato's Long Journey$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$The Tomato's Long Journey$q$, $q$The tomato is native to western South America, where wild forms still grow as small yellow berries. It was farmed in Mexico long before Europeans arrived, and the name comes from the Nahuatl word tomatl. Spanish ships carried the plant across the Atlantic during the sixteenth century, together with maize and potatoes. Botanists in Europe placed it in the same family as deadly nightshade, which gave it a dangerous reputation. For a long time it was grown in gardens as a curiosity rather than eaten as food.

Southern Europe accepted the tomato earlier than the north, partly because the climate suited it. Italian cooks were using tomatoes in sauces by the eighteenth century, though the pairing with pasta became common only later. In England the fruit remained suspect for decades, and some writers warned that it caused illness. The fear was not entirely invented, since acidic tomato juice drew lead out of the pewter plates the wealthy used. Poorer households ate from wood or pottery and suffered no such harm.

The tomato spread far beyond Europe, and it often became central to cuisines that had never known it. Cooks in India, West Africa and the Middle East built the fruit into stews and sauces within a few generations. Canning in the nineteenth century made tomatoes available all year and turned them into an industrial crop. Today the plant is grown on every inhabited continent, and few kitchens treat it as foreign. A fruit once suspected of being poisonous now appears in more national dishes than almost any other.$q$, $q$culture / food$q$, 3, 258, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$An appropriate title for this text would be —$q$, $q$["Why Lead Poisoning Frightened Wealthy English Diners", "The Botanical Family of the Deadly Nightshade Plant", "How Canning Changed Nineteenth-Century Agriculture in Europe", "The Long Journey of the Tomato into World Cooking"]$q$::jsonb, 3, $q$["לא נכון. הרעלת העופרת היא פרט אחד בפסקה השנייה, ולא נושא הקטע.", "לא נכון. שיוך הצמח למשפחת הסולניים מוזכר בפסקה הראשונה כהסבר לחשד, ואינו נושא הקטע.", "לא נכון. השימורים מוזכרים במשפט אחד בפסקה האחרונה בלבד.", "נכון. הקטע עוקב אחר מסעה של העגבנייה מדרום אמריקה אל מטבחים בכל העולם, וזהו מהלכו המרכזי."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E2, passage=tomato-spread, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the second paragraph, all of the following are true EXCEPT —$q$, $q$["English cooks adopted the tomato earlier than cooks in southern Europe did.", "Some English writers warned that eating tomatoes could cause illness.", "Acidic tomato juice drew lead out of the pewter plates used by the wealthy.", "Italian cooks were already using tomatoes in sauces in the eighteenth century."]$q$::jsonb, 0, $q$["נכון. זו הקביעה השגויה — הפסקה כותבת שדרום אירופה אימצה את העגבנייה מוקדם יותר מהצפון, ושבאנגליה היא נותרה חשודה במשך עשרות שנים.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — כותבים אנגלים אכן הזהירו מפני מחלה.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — מיץ העגבניות החומצי אכן חילץ עופרת מצלחות הפיוטר.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — טבחים איטלקים אכן השתמשו בעגבניות ברטבים במאה ה-18."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["Southern Europe accepted the tomato earlier than the north"]$q$::jsonb, $q$shabbat batch E2, passage=tomato-spread, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the last paragraph is to —$q$, $q$["explain why the tomato was once thought to be poisonous in Europe.", "describe the wild forms of the plant that still grow in South America.", "compare Italian sauces with the stews cooked in West Africa and India.", "show how widely the tomato spread and how thoroughly it was absorbed."]$q$::jsonb, 3, $q$["לא נכון. החשד לרעילות מוסבר בפסקאות הראשונה והשנייה, ולא בפסקה האחרונה.", "לא נכון. זהו תוכן הפסקה הראשונה — הצורות הבר בדרום אמריקה — ולא הפסקה האחרונה.", "לא נכון. הפסקה מזכירה מטבחים שונים אך אינה משווה ביניהם.", "נכון. הפסקה האחרונה מראה עד כמה התפשטה העגבנייה ועד כמה הפכה למרכיב טבעי במטבחים שלא הכירו אותה קודם."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=tomato-spread, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The passage says the tomato was at first "grown in gardens as a curiosity rather than eaten as food" because —$q$, $q$["European soil was thought to be unsuitable for growing the plant.", "botanists had classified it with a well-known poisonous plant.", "the fruit could not survive the long sea voyage from Mexico.", "Spanish law forbade the eating of any plant brought from the Americas."]$q$::jsonb, 1, $q$["לא נכון. הפסקה אינה מזכירה בעיה של קרקע; היא דווקא מציינת שהצמח גודל בגנים.", "נכון. הפסקה הראשונה מסבירה שבוטנאים באירופה שייכו את העגבנייה לאותה משפחה של הבלדונה הרעילה, וכך נוצר לה מוניטין מסוכן.", "לא נכון. הפסקה מציינת שספינות ספרדיות הביאו את הצמח בהצלחה מעבר לאוקיינוס.", "לא נכון. הקטע אינו מזכיר חוק ספרדי כלשהו."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["grown in gardens as a curiosity rather than eaten as food"]$q$::jsonb, $q$shabbat batch E2, passage=tomato-spread, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the second paragraph that —$q$, $q$["tomatoes are harmless only when they are cooked for a long time.", "wealthy English families ate far more tomatoes than poorer ones did.", "the danger came from the dishes rather than from the fruit itself.", "Italian cooks discovered the lead problem before English writers did."]$q$::jsonb, 2, $q$["לא נכון. הפסקה אינה קושרת את הסכנה לבישול או לאורכו.", "לא נכון. הפסקה מבחינה בין סוגי הכלים של עשירים ועניים, ולא בכמות העגבניות שאכלו.", "נכון. הפסקה מציינת שהעופרת נשלפה מצלחות הפיוטר, ושמי שאכל מעץ או מחרס לא ניזוק — כלומר הסכנה נבעה מהכלים ולא מהפרי.", "לא נכון. הפסקה אינה מייחסת לטבחים האיטלקים שום גילוי בנוגע לעופרת."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=tomato-spread, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$When a Language Falls Silent$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$When a Language Falls Silent$q$, $q$Roughly seven thousand languages are spoken today, but they are distributed with extraordinary unevenness. A handful of languages account for most of the world's speakers, while thousands are used by very small communities. Linguists broadly agree that a large share of these smaller languages will lose their last fluent speakers this century. The process is rarely sudden, and it usually looks less like death than like a slow withdrawal from public life.

Languages seldom disappear because they are inadequate; they disappear because speaking them becomes costly. When schooling, employment and government operate in a dominant language, parents reasonably conclude that their children need it. The local language survives at home for a generation, then narrows to jokes and greetings, then falls silent. Coercion has played its part, from punished schoolchildren to official bans, yet quiet economic pressure has ended more languages than any decree.

What disappears with a language is harder to state than the loss itself. Every language encodes distinctions that its speakers found worth marking, and those distinctions are not always easy to translate. Some languages grammatically require the speaker to state how a fact was learned, whether by sight, by hearsay or by inference. Communities that live closely with a landscape often carry detailed knowledge of plants, weather and animal behaviour in vocabulary that no outside dictionary contains.

Revival is possible, though it is slow and rarely restores what existed before. Maori, Welsh and Hawaiian have all gained speakers through schools and broadcasting after long decline, and other communities are attempting the same. Such efforts succeed only when a language is given real work to do, since a tongue used solely in the classroom will not survive outside it.$q$, $q$culture / language$q$, 6, 282, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$What is the main idea of the passage?$q$, $q$["Coercive government policies are the main reason that small languages disappear.", "Most of the world's languages are spoken by very small communities today.", "Maori, Welsh and Hawaiian have all gained new speakers through schooling and broadcasting.", "Small languages are being abandoned under economic pressure, and their loss removes knowledge that is hard to replace."]$q$::jsonb, 3, $q$["לא נכון. הפסקה השנייה כותבת שהלחץ הכלכלי השקט חיסל יותר שפות מכל צו רשמי.", "לא נכון. זו קביעה נכונה מהפסקה הראשונה, אך היא נתון פתיחה ולא הרעיון המרכזי.", "לא נכון. זו קביעה נכונה מהפסקה האחרונה, אך היא דוגמה ולא הרעיון המרכזי של הקטע.", "נכון. הקטע מסביר מדוע שפות ננטשות מסיבות כלכליות ומה בדיוק אובד יחד איתן, וזהו מהלכו המרכזי."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E2, passage=language-loss, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["list the regions in which the world's largest languages are spoken.", "explain why speakers give up a language even when nobody forbids it.", "describe the grammatical distinctions that some small languages require.", "assess how successful recent revival programmes have actually proved to be."]$q$::jsonb, 1, $q$["לא נכון. הפסקה אינה מונה אזורים גיאוגרפיים כלל.", "נכון. הפסקה השנייה מסבירה שהשפה ננטשת משום שהדיבור בה נעשה יקר מבחינה מעשית, גם ללא כפייה רשמית.", "לא נכון. זהו תוכן הפסקה השלישית — ההבחנות הדקדוקיות — ולא הפסקה השנייה.", "לא נכון. זהו תוכן הפסקה האחרונה — תוכניות ההחייאה — ולא הפסקה השנייה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=language-loss, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the third paragraph is to —$q$, $q$["argue that dictionaries of dominant languages should be enlarged.", "explain how schooling and employment operate in a dominant language.", "estimate how many languages will lose their last speakers this century.", "show what kinds of knowledge are carried by a language and lost with it."]$q$::jsonb, 3, $q$["לא נכון. המילונים מוזכרים רק כדי להראות שידע מסוים אינו מתועד בהם, ואין כאן קריאה להרחיבם.", "לא נכון. זהו תוכן הפסקה השנייה — פעולת החינוך והתעסוקה בשפה שלטת — ולא הפסקה השלישית.", "לא נכון. זהו תוכן הפסקה הראשונה — ההערכה לגבי המאה הנוכחית — ולא הפסקה השלישית.", "נכון. הפסקה השלישית מדגימה איזה ידע נישא בשפה — הבחנות דקדוקיות וידע מפורט על צמחים, מזג אוויר ובעלי חיים — וכך מראה מה אובד."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=language-loss, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the last paragraph, all of the following are true EXCEPT —$q$, $q$["Revival efforts have restored these languages to the position they once held.", "Maori, Welsh and Hawaiian have gained speakers after a long period of decline.", "Broadcasting and schooling have played a part in these revival efforts.", "A language used only in the classroom is unlikely to survive outside it."]$q$::jsonb, 0, $q$["נכון. זו הקביעה השגויה — הפסקה כותבת שההחייאה איטית ולעיתים רחוקות משיבה את מה שהיה קודם.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — מאורי, וולשית והוואית אכן זכו בדוברים לאחר דעיכה ארוכה.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — בתי ספר ושידור אכן מוזכרים כאמצעים.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — שפה המשמשת רק בכיתה לא תשרוד מחוצה לה."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["though it is slow and rarely restores what existed before"]$q$::jsonb, $q$shabbat batch E2, passage=language-loss, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$Based on the passage, what can be inferred about efforts to protect endangered languages?$q$, $q$["They are most effective when governments outlaw the dominant language.", "They generally fail because small languages lack an adequate vocabulary.", "They depend on giving the language genuine everyday uses.", "They matter mainly to linguists rather than to the communities themselves."]$q$::jsonb, 2, $q$["לא נכון. הקטע אינו מציע איסור על השפה השלטת, וגם מציין שכפייה אינה הגורם המרכזי לתהליך.", "לא נכון. הפסקה השנייה קובעת במפורש ששפות אינן נעלמות משום שהן בלתי מספקות.", "נכון. הפסקה השנייה מראה שהשפה נסוגה כשהיא מאבדת תפקיד ציבורי, והפסקה האחרונה קובעת שההחייאה מצליחה רק כשנותנים לשפה עבודה ממשית.", "לא נכון. הקטע מתאר קהילות הפועלות בעצמן להחייאת שפתן."]$q$::jsonb, $q$inference$q$, $q$text$q$, null, $q$shabbat batch E2, passage=language-loss, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$The Map That Ignored Geography$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$The Map That Ignored Geography$q$, $q$Before 1933 maps of the London Underground tried to show where the lines actually ran. Stations in the centre were crowded into a small area, while outlying branches stretched to the edges of the sheet. Passengers found the result difficult to read, and the network looked more complicated than it was. Harry Beck, a young draughtsman employed by the Underground, worked on the problem in his own time. He argued that a traveller underground does not care about distance, only about order and connections.

Beck's solution was to draw the network as an electrical circuit diagram rather than as a geographical map. Lines ran only horizontally, vertically or at forty-five degrees, and each was given its own colour. Distances in the crowded centre were stretched out, while the long suburban branches were compressed into short segments. The river Thames was kept as the single geographical landmark, and everything else was removed. Management thought the design too radical and hesitated, but agreed to a trial printing in 1933.

The trial leaflets were taken up so quickly that a larger run had to be ordered almost at once. Passengers understood the network faster, and the diagram soon appeared on station walls throughout the system. Beck continued to revise it for nearly thirty years and was paid very little for the work. Transport authorities in other cities adopted the same principles, and the schematic transit diagram became a worldwide standard. The design has one persistent cost: travellers trust its geometry and sometimes take a train between stations they could easily walk between.$q$, $q$arts / design$q$, 4, 257, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, what was the problem with earlier Underground maps?$q$, $q$["They omitted the river Thames and other useful geographical landmarks.", "They were printed in a single colour that made the lines hard to follow.", "They showed only the central stations and left out the suburban branches.", "They followed real geography, which crowded the centre and confused passengers."]$q$::jsonb, 3, $q$["לא נכון. התמזה מוזכרת בפסקה השנייה כציון הדרך היחיד שנשמר בשרטוט של בק, ולא כחסר במפות הישנות.", "לא נכון. הצבעים לפי קווים הם חידוש של בק בפסקה השנייה, והפסקה הראשונה אינה מתלוננת על צבע.", "לא נכון. הפסקה כותבת דווקא שהענפים החיצוניים נמתחו עד קצות הדף, כלומר הם כן הופיעו.", "נכון. הפסקה הראשונה מסבירה שהמפות ניסו להראות היכן הקווים עוברים במציאות, ולכן המרכז נדחס והנוסעים התקשו לקרוא אותן."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=underground-map, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["explain why the management was reluctant to print Beck's design at first.", "describe the rules Beck used to redraw the network as a diagram.", "show how quickly passengers accepted the leaflets when they appeared.", "criticise Beck's employers for paying him so little over thirty years."]$q$::jsonb, 1, $q$["לא נכון. היסוס ההנהלה מוזכר במשפט אחד בסוף הפסקה, ואינו מטרתה.", "נכון. הפסקה השנייה מפרטת את כללי השרטוט של בק: זוויות קבועות, צבע לכל קו, מתיחה של המרכז וכיווץ הפרברים, והשארת התמזה בלבד.", "לא נכון. זהו תוכן הפסקה השלישית — קליטת העלונים — ולא הפסקה השנייה.", "לא נכון. שכרו הנמוך מוזכר בפסקה השלישית, והקטע אינו מותח על כך ביקורת."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=underground-map, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the last paragraph, the word "schematic" most nearly means —$q$, $q$["Simplified to show relationships rather than exact positions", "Printed in several colours on high-quality paper", "Drawn to an accurate and consistent geographical scale", "Produced by a committee rather than by one designer"]$q$::jsonb, 0, $q$["נכון. 'schematic' מתאר שרטוט מפושט המראה יחסים וקשרים ולא מיקומים מדויקים, וזה בדיוק מה שבק עשה.", "לא נכון. המילה אינה עוסקת באיכות ההדפסה או במספר הצבעים.", "לא נכון. זהו ההפך מהמשמעות: השרטוט של בק ויתר בכוונה על קנה מידה גיאוגרפי מדויק.", "לא נכון. המילה מתארת את אופי השרטוט ולא את זהות מי שהכין אותו."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["the schematic transit diagram became a worldwide standard"]$q$::jsonb, $q$shabbat batch E2, passage=underground-map, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The statement that travellers "sometimes take a train between stations they could easily walk between" suggests that —$q$, $q$["the diagram contains printing errors that the designer never corrected.", "walking between central stations is usually slower than travelling by train.", "the diagram's distortions can mislead people about real distances.", "passengers prefer the Underground because the streets above are unpleasant."]$q$::jsonb, 2, $q$["לא נכון. הקטע מתאר עיוות מכוון של המרחקים, ולא טעויות דפוס.", "לא נכון. המשפט מרמז דווקא שההליכה קלה, ולכן הנסיעה מיותרת.", "נכון. הפסקה השנייה מציינת שמרחקי המרכז נמתחו, והמשפט האחרון מראה שהנוסעים סומכים על הגיאומטריה הזו ומסיקים ממנה מרחקים שגויים.", "לא נכון. הקטע אינו אומר דבר על הרחובות שמעל הקרקע."]$q$::jsonb, $q$inference$q$, $q$anchor$q$, $q$["travellers trust its geometry and sometimes take a train between stations they could easily walk between"]$q$::jsonb, $q$shabbat batch E2, passage=underground-map, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$Which of the following is NOT mentioned in the last paragraph?$q$, $q$["The diagram was displayed on station walls across the system.", "Beck went on revising the design for nearly thirty years.", "Other cities adopted the same principles for their own transit networks.", "Beck was rewarded with a large payment for his design."]$q$::jsonb, 3, $q$["לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — השרטוט אכן הוצג על קירות התחנות.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — בק אכן המשיך לעדכן את השרטוט כשלושים שנה.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — רשויות תחבורה בערים אחרות אכן אימצו את העקרונות.", "נכון. זו הקביעה שאינה מופיעה — הפסקה אומרת שבק קיבל תמורה זעומה על עבודתו."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["was paid very little for the work"]$q$::jsonb, $q$shabbat batch E2, passage=underground-map, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$Sixpence and a Serious Book$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$Sixpence and a Serious Book$q$, $q$Cheap books in paper covers existed long before the twentieth century, but they were usually badly printed and badly regarded. Railway stalls sold sensational stories on rough paper, and respectable publishers kept their distance from them. A serious book was expected to be a hardback, and its price put it beyond most household budgets. Libraries and lending clubs filled the gap for readers who could not afford to buy. The idea that a good new novel might cost about the same as a packet of cigarettes seemed unlikely.

In 1935 Allen Lane, an English publisher, launched a series called Penguin Books at sixpence a volume. The list mixed novels, crime stories and serious non-fiction, and the covers used plain colour bands instead of pictures. The colour indicated the category, so a buyer could recognise a Penguin thriller from across a crowded shop. Booksellers were unenthusiastic about the experiment, and the series was rescued by a large order from the Woolworths chain. Within a year Penguin had sold millions of copies, and other publishers hurried to imitate the format.

The paperback changed who read books and where reading actually happened. Books were now bought in chemists, railway stations and department stores rather than only in specialist bookshops. Soldiers in the Second World War were supplied with paperbacks designed to fit a uniform pocket. Publishers discovered that there was a large audience for serious writing which the hardback trade had never reached. Paper covers were not new, however, and the real innovation was respectability: good books sold cheaply, without apology.$q$, $q$culture / media$q$, 3, 257, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, how were cheap paper-covered books regarded before the twentieth century?$q$, $q$["As badly produced reading matter that serious publishers preferred to avoid.", "As the standard format for new novels by respected authors.", "As too expensive for the ordinary household to buy regularly.", "As the main source of income for public lending libraries."]$q$::jsonb, 0, $q$["נכון. הפסקה כותבת שהספרים הזולים היו מודפסים גרוע ונחשבו נחותים, ושמוציאים לאור מכובדים שמרו מהם מרחק.", "לא נכון. הפסקה מציינת שספר רציני היה אמור להיות בכריכה קשה.", "לא נכון. המחיר הגבוה מיוחס בפסקה לכריכה הקשה, לא לספרים בכריכה רכה.", "לא נכון. הספריות מוזכרות כפתרון לקוראים שלא יכלו לקנות, ולא כמי שהתפרנסו מספרים אלה."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=paperback-revolution, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["explain why hardbacks remained beyond most household budgets.", "describe the paperbacks that were supplied to soldiers during the war.", "argue that colour is more useful than pictures on a book cover.", "recount how Penguin was launched and how quickly it succeeded."]$q$::jsonb, 3, $q$["לא נכון. זהו תוכן הפסקה הראשונה — מחיר הכריכה הקשה — ולא הפסקה השנייה.", "לא נכון. זהו תוכן הפסקה האחרונה — הספרים לחיילים — ולא הפסקה השנייה.", "לא נכון. הפסקה מתארת את פסי הצבע ככלי זיהוי, אך אינה טוענת שהם עדיפים על תמונות באופן כללי.", "נכון. הפסקה השנייה מספרת על השקת פינגווין ב-1935, על הצלת הסדרה בזכות הזמנת וולוורת'ס ועל מיליוני העותקים שנמכרו בתוך שנה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=paperback-revolution, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The passage states that the series "was rescued by a large order from the Woolworths chain." This was necessary because —$q$, $q$["the first Penguin titles had been printed with serious errors.", "ordinary booksellers had shown little enthusiasm for the series.", "Allen Lane had run out of suitable books to include in the list.", "the colour bands on the covers had confused most early buyers."]$q$::jsonb, 1, $q$["לא נכון. הפסקה אינה מזכירה טעויות דפוס כלשהן.", "נכון. אותו משפט עצמו פותח בכך שהמוכרים הרגילים לא גילו התלהבות מהניסוי, ולכן ההזמנה הגדולה הצילה את הסדרה.", "לא נכון. הפסקה מציינת שהרשימה כללה רומנים, ספרי מתח ועיון רציני.", "לא נכון. הפסקה כותבת שפסי הצבע דווקא סייעו לקונים לזהות את סוג הספר."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["the series was rescued by a large order from the Woolworths chain"]$q$::jsonb, $q$shabbat batch E2, passage=paperback-revolution, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the last paragraph, the word "respectability" most nearly means —$q$, $q$["The ability to be sold at a very low price", "The habit of reading books in public places", "A cover design that uses colour instead of pictures", "The status of being taken seriously by readers"]$q$::jsonb, 3, $q$["לא נכון. המחיר הנמוך אינו החידוש לפי הפסקה, שהרי כריכות נייר זולות כבר היו קיימות.", "לא נכון. המילה אינה מתארת היכן קוראים אלא כיצד נתפסים הספרים.", "לא נכון. עיצוב הכריכה מתואר בפסקה השנייה ואינו משמעות המילה.", "נכון. 'respectability' פירושו מעמד של דבר הנחשב רציני ומכובד — כאן ספרים טובים שנמכרו בזול בלי להתנצל."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["the real innovation was respectability"]$q$::jsonb, $q$shabbat batch E2, passage=paperback-revolution, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$Based on the passage, what can be inferred about the audience for serious books before 1935?$q$, $q$["It consisted mainly of soldiers and of railway travellers.", "It was shrinking because of competition from cheap newspapers.", "It was larger than publishers had realised.", "It preferred crime stories to any other kind of writing."]$q$::jsonb, 2, $q$["לא נכון. החיילים מופיעים רק בהקשר של מלחמת העולם השנייה, לאחר 1935.", "לא נכון. הקטע אינו מזכיר תחרות מצד עיתונים ואינו טוען שקהל הקוראים הצטמצם.", "נכון. הפסקה האחרונה כותבת שהמוציאים לאור גילו קהל גדול לכתיבה רצינית שסחר הכריכה הקשה מעולם לא הגיע אליו — כלומר הקהל היה קיים אך לא זוהה.", "לא נכון. ספרי המתח הם רק אחד מסוגי הספרים ברשימת פינגווין, והקטע אינו מדרג העדפות."]$q$::jsonb, $q$inference$q$, $q$text$q$, null, $q$shabbat batch E2, passage=paperback-revolution, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$Reading or Hearing a Foreign Film$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$Reading or Hearing a Foreign Film$q$, $q$Silent films crossed borders easily, since a printed title card could be replaced in any language for very little money. The arrival of synchronised sound at the end of the 1920s ended that freedom almost overnight. Studios briefly tried shooting the same film several times with different casts, an expensive method that satisfied nobody. Two solutions replaced it, and the choice between them hardened into national habit within a decade. Subtitles were cheap and quick to produce, while dubbing was costly but left the image uninterrupted.

Cost alone does not explain the pattern that eventually emerged across Europe. Small markets with high literacy, such as the Netherlands and the Nordic countries, adopted subtitles and kept them. Larger markets with strong national film industries, including Germany, Italy, Spain and France, built dubbing studios instead. Political motives reinforced the economic ones, since authoritarian governments in the 1930s preferred a version of a foreign film they could rewrite. Audiences then grew up with one convention and came to find the other distracting.

These inherited habits still shape which films travel abroad and how they are received there. A subtitled film reaches viewers with the original performance intact, yet it asks them to read while they watch. Dubbing removes that effort but replaces the actor's voice, which is a large part of a performance. Distributors know this, and a film with dense dialogue is harder to sell into a dubbing market than a film built on action. Streaming services now offer both options on the same title, although national preferences have proved surprisingly durable.$q$, $q$culture / media$q$, 6, 260, true, $q$reading_shabbat_2026-09-05_E2$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, all of the following are true EXCEPT —$q$, $q$["Title cards in silent films could be translated cheaply for foreign markets.", "Studios briefly filmed the same story several times with different casts.", "Dubbing cost more than subtitling but left the picture undisturbed.", "Subtitling was invented before synchronised sound reached the cinema."]$q$::jsonb, 3, $q$["לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — כרטיסיות הכיתוב אכן הוחלפו בזול בכל שפה.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — האולפנים אכן צילמו את אותו סרט כמה פעמים עם צוותי שחקנים שונים.", "לא נכון. זו קביעה נכונה על פי הפסקה, ולכן אינה החריג המבוקש — הדיבוב אכן היה יקר יותר אך השאיר את התמונה שלמה.", "נכון. זו הקביעה השגויה — הפסקה מציגה את הכתוביות כאחד משני הפתרונות שהופיעו אחרי בוא הקול, ולא לפניו."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["Two solutions replaced it, and the choice between them hardened into national habit within a decade"]$q$::jsonb, $q$shabbat batch E2, passage=subtitles-dubbing, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["describe the multi-language versions that studios abandoned in the 1930s.", "explain why different countries settled on different translation methods.", "show how streaming services now offer viewers a choice of both options.", "argue that dubbing damages the performance an actor originally gave."]$q$::jsonb, 1, $q$["לא נכון. הגרסאות הרב-לשוניות מתוארות בפסקה הראשונה, ולא בשנייה.", "נכון. הפסקה השנייה מונה את הגורמים — גודל השוק, אוריינות, תעשיית קולנוע מקומית ומניעים פוליטיים — שהובילו מדינות שונות לבחירות שונות.", "לא נכון. זהו תוכן הפסקה האחרונה — שירותי הסטרימינג — ולא הפסקה השנייה.", "לא נכון. הטענה על קולו של השחקן מופיעה בפסקה האחרונה, והפסקה השנייה אינה מכריעה בין השיטות."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=subtitles-dubbing, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the sentence "Audiences then grew up with one convention and came to find the other distracting," the phrase "the other" refers to —$q$, $q$["the translation method their own country had not adopted", "the original language of the imported film", "the political motives of governments in the 1930s", "the national film industry of a larger market"]$q$::jsonb, 0, $q$["נכון. הפסקה מציגה שתי שיטות תרגום, ולכן 'the other' הוא השיטה השנייה — זו שהמדינה של אותם צופים לא אימצה.", "לא נכון. שפת המקור אינה אחת משתי המוסכמות שהפסקה מעמידה זו מול זו.", "לא נכון. המניעים הפוליטיים מוזכרים במשפט הקודם כסיבה, ואינם 'המוסכמה האחרת'.", "לא נכון. תעשיית הקולנוע המקומית היא גורם שהשפיע על הבחירה, ולא שיטת התרגום עצמה."]$q$::jsonb, $q$reference_word$q$, $q$anchor$q$, $q$["Audiences then grew up with one convention and came to find the other distracting."]$q$::jsonb, $q$shabbat batch E2, passage=subtitles-dubbing, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the last paragraph, the word "durable" is closest in meaning to —$q$, $q$["Expensive to maintain over a long period of time", "Difficult for outsiders to understand clearly", "Shared by audiences in every European country", "Lasting rather than quickly disappearing"]$q$::jsonb, 3, $q$["לא נכון. המילה אינה עוסקת בעלות אחזקה.", "לא נכון. המילה אינה עוסקת במידת המובנוּת של ההעדפות.", "לא נכון. הפסקה השנייה מדגישה שההעדפות שונות ממדינה למדינה, ולא משותפות לכולן.", "נכון. 'durable' פירושו מתמיד ועמיד — ההעדפות הלאומיות שרדו גם כששירותי הסטרימינג הציעו את שתי האפשרויות."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["national preferences have proved surprisingly durable"]$q$::jsonb, $q$shabbat batch E2, passage=subtitles-dubbing, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the last paragraph that —$q$, $q$["dubbed films always earn more money abroad than subtitled ones do.", "viewers in subtitling countries read more slowly than other viewers.", "a talkative film may be a harder sale in a dubbing market.", "streaming services have ended the difference between the two traditions."]$q$::jsonb, 2, $q$["לא נכון. הפסקה אינה משווה רווחים בין השיטות.", "לא נכון. הפסקה אינה אומרת דבר על מהירות הקריאה של הצופים.", "נכון. הפסקה כותבת שסרט עתיר דיאלוג קשה יותר למכירה לשוק דיבוב מאשר סרט המבוסס על פעולה.", "לא נכון. הפסקה מסיימת בכך שההעדפות הלאומיות התגלו כעמידות במפתיע."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E2, passage=subtitles-dubbing, q5$q$, 5, true);
  end if;
end $$;