do $$ declare v_pid uuid; begin

  if not exists (select 1 from reading_passages where title = $q$Cleaning the Sistine Ceiling$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$Cleaning the Sistine Ceiling$q$, $q$Michelangelo painted the ceiling of the Sistine Chapel between 1508 and 1512, working in fresco on wet plaster. Over the following centuries the surface darkened under smoke from candles and braziers, and earlier restorers brushed on glues and varnishes meant to revive the colors. By the middle of the twentieth century visitors saw a solemn, shadowy scheme dominated by browns and grays. Many writers had come to regard that somber atmosphere as an essential quality of Michelangelo's art.

A full cleaning began in 1980 and continued for more than a decade, financed by a Japanese television company in exchange for filming rights. Conservators tested solvents on small areas, removed the added layers and recorded every stage in photographs and technical reports. What emerged was a startling range of pink, orange, apple green and pale blue. The figures now appeared to be modeled by color itself rather than by deep shadow.

The result provoked one of the fiercest arguments in the history of conservation. Critics, among them the art historian James Beck, insisted that Michelangelo had returned to the dry plaster to add final shadows and adjustments. If such a layer had existed, the cleaning would have stripped away the artist's own last touches and left an unnaturally bright surface. Defenders replied that laboratory analysis identified the dark material as animal glue, soot and later varnish, none of it original.

The dispute was never settled to everyone's satisfaction, although most specialists accepted the evidence of the conservators. It did, however, change the way major restorations are carried out and explained to the public. Projects are now documented in far greater detail, and conservators are expected to justify each decision openly rather than only to their colleagues. The episode also reminded museums that an appearance people believe to be original may in fact be the work of time and of earlier repairs.$q$, $q$arts / visual$q$, 6, 307, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$What is the main idea of the passage?$q$, $q$["Michelangelo used a dry plaster technique that later conservators completely failed to understand.", "Japanese television companies have paid for several of the major art restorations in Italy.", "The cleaning of the ceiling revealed bright colors and raised lasting questions about restoration.", "Modern conservation science can now identify every material found on a painted surface."]$q$::jsonb, 2, $q$["לא נכון. שאלת השכבה היבשה היא טענת המבקרים בפסקה השלישית, והקטע אינו מציג אותה כעובדה מוכחת.", "לא נכון. המימון היפני הוא פרט אחד בפסקה השנייה, ולא הרעיון המרכזי.", "נכון. הקטע מתאר את הניקוי, את הצבעים שנחשפו ואת הוויכוח שהוא עורר על דרכי השימור — וזהו הרעיון המרכזי.", "לא נכון. הקטע מזכיר בדיקות מעבדה כראיה בוויכוח, אך אינו טוען שהמדע מזהה כל חומר."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E1, passage=sistine-restoration, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, why did the ceiling look dark before the cleaning?$q$, $q$["Michelangelo had deliberately chosen brown and gray pigments for the whole scheme.", "Smoke had settled on the surface and earlier restorers had added glues and varnishes.", "The windows of the chapel had been blocked up during the nineteenth century.", "The wet plaster had absorbed moisture that gradually dulled the original colors."]$q$::jsonb, 1, $q$["לא נכון. הפסקה מציינת שהצבעים הכהים היו תוצאה של פיח וחומרים שנוספו, ולא בחירה של מיכלאנג'לו.", "נכון. הפסקה הראשונה מסבירה שעשן הנרות והכירות השחיר את המשטח ושמשמרים קודמים מרחו דבקים ולכות.", "לא נכון. הפסקה אינה מזכירה חלונות שנחסמו.", "לא נכון. הפסקה אינה מייחסת את ההכהיה לספיגת לחות בטיח."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=sistine-restoration, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the third paragraph is to —$q$, $q$["describe the technical procedures that the conservators followed during the cleaning.", "explain why museums today document their restoration projects so carefully.", "set out the objection raised against the cleaning and the answer given to it.", "praise the television company that paid for the work in exchange for filming rights."]$q$::jsonb, 2, $q$["לא נכון. תיאור הפרוצדורות מופיע בפסקה השנייה, ולא בשלישית.", "לא נכון. התיעוד המוקפד של ימינו מתואר בפסקה האחרונה, ולא בשלישית.", "נכון. הפסקה השלישית מציגה את טענת המבקרים בראשות ג'יימס בק ואת תשובת המגינים המבוססת על בדיקות מעבדה.", "לא נכון. המימון מוזכר בפסקה השנייה, והקטע אינו משבח את החברה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=sistine-restoration, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the last paragraph is to —$q$, $q$["describe the solvents and the testing methods used during the cleaning itself.", "explain what the restoration changed in the practice of conservation.", "restate the objection raised by the art historian James Beck.", "describe the appearance of the ceiling in the years before the cleaning began."]$q$::jsonb, 1, $q$["לא נכון. הממסים ושיטות הבדיקה מתוארים בפסקה השנייה, ולא באחרונה.", "נכון. הפסקה האחרונה מתארת את מורשת הפרויקט: תיעוד מפורט יותר, חובת הסבר פומבית ותובנה על מה שנתפס כמראה מקורי.", "לא נכון. טענת בק מופיעה בפסקה השלישית, והפסקה האחרונה אינה חוזרת עליה.", "לא נכון. מראה התקרה לפני הניקוי מתואר בפסקה הראשונה, ולא באחרונה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=sistine-restoration, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the first paragraph, the word "somber" most nearly means —$q$, $q$["carefully planned well in advance", "unfinished and left in a rough state", "widely admired by ordinary visitors", "dark and serious in mood"]$q$::jsonb, 3, $q$["לא נכון. המילה מתארת אווירה ולא תכנון מוקדם.", "לא נכון. המילה אינה מתייחסת למידת השלמתה של היצירה.", "לא נכון. המילה מתארת את אופי האווירה, לא את יחס המבקרים.", "נכון. המשפט הקודם מתאר סכמה חמורה ומוצללת בחומים ואפורים, ולכן 'somber' פירושו כהה ורציני באווירתו."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["regard that somber atmosphere as an essential quality"]$q$::jsonb, $q$shabbat batch E1, passage=sistine-restoration, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$Jazz on the Northbound Trains$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$Jazz on the Northbound Trains$q$, $q$Jazz took shape in New Orleans in the first years of the twentieth century, drawing on blues, ragtime and brass band music. The city's dance halls and street parades gave players constant work and a reason to experiment with improvisation. At the same time, life for Black Americans in the rural South was governed by segregation laws, debt and the threat of violence. Beginning in the 1910s, hundreds of thousands of people boarded trains for Chicago, Detroit, New York and other industrial cities. This movement, later called the Great Migration, continued for decades and reshaped the population of the North.

Musicians traveled with everyone else, carrying a southern style into cities that had never heard it. Chicago became the center of the music in the early 1920s, where King Oliver led a celebrated band on the South Side. Louis Armstrong joined him there in 1922, and his solos soon persuaded other players to treat improvisation as the heart of the music. Recording companies noticed the demand and began issuing discs aimed at Black audiences. Radio then carried the same performances into homes that no dance hall could ever reach.

New York gradually overtook Chicago as the capital of the music during the late 1920s. Harlem attracted writers, painters and musicians, and Duke Ellington built a national reputation through nightly broadcasts from a Harlem nightclub. The audience for jazz widened far beyond the communities that had created it, which brought both money and difficult compromises. White bandleaders often earned more from the style than the musicians who had shaped it. Nevertheless, the migration had turned a regional music into something the whole country recognized as its own.$q$, $q$arts / music$q$, 5, 275, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$An appropriate title for this text would be —$q$, $q$["The Dance Halls and Street Parades of Early New Orleans", "How a Great Movement of People Carried Jazz Across the United States", "Duke Ellington's Nightly Radio Broadcasts from a Harlem Nightclub", "The Unequal Rewards That White Bandleaders Received from Jazz"]$q$::jsonb, 1, $q$["לא נכון. אולמות הריקודים והתהלוכות מוזכרים בפסקה הראשונה כרקע להתפתחות הסגנון בלבד.", "נכון. הקטע קושר בין ההגירה הגדולה לצפון לבין התפשטות הג'אז מניו אורלינס לשיקגו ולניו יורק, וזהו נושאו המרכזי.", "לא נכון. אלינגטון והשידורים הם דוגמה אחת בפסקה השלישית, ולא נושא הקטע.", "לא נכון. פער הרווחים מוזכר במשפט אחד לקראת הסוף, ואינו הרעיון המרכזי."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E1, passage=jazz-migration, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the passage, what led people to board trains for the northern cities?$q$, $q$["Record companies in the North were recruiting southern musicians directly.", "Segregation, debt and the threat of violence shaped daily life in the rural South.", "The city of New Orleans had banned public dance halls and street parades.", "Radio stations in Chicago were offering regular work to traveling performers."]$q$::jsonb, 1, $q$["לא נכון. חברות התקליטים מוזכרות בפסקה השנייה, לאחר ההגירה, ולא כגורם שהניע אותה.", "נכון. המשפט שלפני כן מתאר חיים הנשלטים בידי חוקי הפרדה, חובות ואיום של אלימות, וזהו ההקשר שבו אנשים עלו על הרכבות.", "לא נכון. הקטע אינו מזכיר איסור על אולמות ריקודים בניו אורלינס.", "לא נכון. הרדיו מופיע בפסקה השנייה כאמצעי הפצה, ולא כמעסיק שמשך מהגרים."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["hundreds of thousands of people boarded trains for Chicago, Detroit, New York and other industrial cities"]$q$::jsonb, $q$shabbat batch E1, passage=jazz-migration, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["describe the musical traditions that were combined in early New Orleans jazz.", "explain how Chicago became the center of the music and how recordings spread it.", "describe the growth of Harlem as a gathering place for writers and painters.", "argue that written arrangements mattered more to jazz than improvisation did."]$q$::jsonb, 1, $q$["לא נכון. המסורות המוזיקליות שהתמזגו מתוארות בפסקה הראשונה, ולא בשנייה.", "נכון. הפסקה השנייה מתארת את שיקגו כמרכז החדש, את אוליבר ואת ארמסטרונג, ואת התקליטים והרדיו שהפיצו את המוזיקה.", "לא נכון. הארלם מתוארת בפסקה השלישית, ולא בשנייה.", "לא נכון. הפסקה דווקא מציינת שהאלתור הפך ללב המוזיקה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=jazz-migration, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the third paragraph, all of the following are true EXCEPT —$q$, $q$["New York replaced Chicago as the leading city for jazz in the late 1920s.", "Duke Ellington gained a national reputation partly through regular radio broadcasts.", "Jazz found listeners well beyond the communities in which the music began.", "Black bandleaders earned more from the style than white bandleaders did."]$q$::jsonb, 3, $q$["לא נכון. זו קביעה נכונה על פי הפסקה השלישית, ולכן אינה החריג המבוקש.", "לא נכון. זו קביעה נכונה על פי הפסקה השלישית, ולכן אינה החריג המבוקש.", "לא נכון. זו קביעה נכונה על פי הפסקה השלישית, ולכן אינה החריג המבוקש.", "נכון. זו הקביעה השגויה: הפסקה כותבת שדווקא מנהיגי תזמורות לבנים הרוויחו לרוב יותר מהמוזיקאים שעיצבו את הסגנון."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["White bandleaders often earned more from the style than the musicians who had shaped it."]$q$::jsonb, $q$shabbat batch E1, passage=jazz-migration, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the sentence "This movement, later called the Great Migration, continued for decades," the phrase "This movement" refers to —$q$, $q$["the spread of jazz recordings into homes across the country", "the departure of large numbers of Black southerners for northern cities", "the growth of dance halls and street parades in the city of New Orleans", "the arrival of European immigrants in the industrial centers of America"]$q$::jsonb, 1, $q$["לא נכון. התקליטים והרדיו מופיעים רק בפסקה השנייה, אחרי המשפט הזה.", "נכון. המשפט הקודם מתאר מאות אלפי אנשים שעלו על רכבות מהדרום הכפרי אל ערי התעשייה בצפון, וזו התנועה שאליה מכוון 'This movement'.", "לא נכון. אולמות הריקודים מוזכרים בתחילת הפסקה בהקשר אחר לגמרי.", "לא נכון. הקטע אינו עוסק כלל בהגירה מאירופה."]$q$::jsonb, $q$reference_word$q$, $q$anchor$q$, $q$["This movement, later called the Great Migration, continued for decades"]$q$::jsonb, $q$shabbat batch E1, passage=jazz-migration, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$Fourteen Years That Shaped Design$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$Fourteen Years That Shaped Design$q$, $q$The Bauhaus opened in Weimar in 1919, when the architect Walter Gropius merged a fine art academy with a school of applied arts. Gropius argued that the division between the artist and the craftsman was an accident of history rather than a natural law. Every student therefore began with a preliminary course in materials, color and form before entering a workshop. The workshops were led by two masters at once, one trained in a craft and one trained as an artist.

The teaching staff included the painters Paul Klee and Wassily Kandinsky, whose classes on color and composition became famous. Early work at the school leaned towards handicraft and towards expressive experiment. After 1923, however, Gropius pushed the Bauhaus towards industry, under the slogan art and technology, a new unity. Designs were now meant as prototypes for factories, and the school earned income by licensing them to manufacturers.

In 1925 the school moved to Dessau, into a glass and concrete building that Gropius designed as a demonstration of its principles. The products of these years still shape everyday objects: tubular steel chairs, adjustable lamps and plain typefaces without serifs. Political pressure grew as the decade ended, and the school moved again to Berlin under its last director, Mies van der Rohe. The Nazi authorities forced it to close in 1933, after only fourteen years of existence.

The school's influence spread further after its closure, precisely because its teachers were scattered across the world. Gropius and Marcel Breuer went to Harvard, Mies to Chicago, and Josef Albers to an experimental college in North Carolina. Architects working in the same spirit built much of central Tel Aviv, a district later recognized by UNESCO. Critics have long complained that the resulting style is cold and indifferent to how people actually live. Its vocabulary of clean surfaces and honest materials nevertheless remains the ordinary language of modern design.$q$, $q$arts / architecture$q$, 6, 310, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, how were the Bauhaus workshops organized?$q$, $q$["Each one was directed by a craftsman and an artist together.", "Students chose a workshop before taking any other courses at the school.", "Each workshop was supervised in person by Walter Gropius himself.", "Workshops were open only to students who had already trained as craftsmen."]$q$::jsonb, 0, $q$["נכון. הפסקה הראשונה מציינת שכל סדנה הונהגה בידי שני מורים במקביל, אחד בעל הכשרה במלאכה ואחד בעל הכשרה אמנותית.", "לא נכון. הפסקה מציינת שכל תלמיד התחיל בקורס מקדים ורק אחר כך נכנס לסדנה.", "לא נכון. הפסקה אינה מייחסת לגרופיוס פיקוח אישי על כל סדנה.", "לא נכון. הפסקה אינה מזכירה תנאי קבלה של הכשרה קודמת במלאכה."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=bauhaus, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["describe the design of the school's new building in the city of Dessau.", "explain how the aims of the school moved from handicraft towards industry.", "list the painters who taught courses on color and composition at the school.", "show why the political authorities regarded the school as dangerous."]$q$::jsonb, 1, $q$["לא נכון. הבניין בדסאו מתואר בפסקה השלישית, ולא בשנייה.", "נכון. הפסקה השנייה מתארת את המעבר מעבודת יד וניסוי אקספרסיבי אל תכנון אבות טיפוס לתעשייה אחרי 1923.", "לא נכון. שמות הציירים מוזכרים בפסקה כפרט פותח, אך מטרתה היא לתאר את שינוי הכיוון של בית הספר.", "לא נכון. הלחץ הפוליטי מתואר בפסקה השלישית, ולא בשנייה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=bauhaus, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the last paragraph that —$q$, $q$["the closure of the school helped rather than hindered the spread of its ideas", "Bauhaus teachers were forbidden to work as architects after leaving Germany", "the style was accepted everywhere without any serious criticism from architects", "the whole of central Tel Aviv was designed by architects trained at Dessau"]$q$::jsonb, 0, $q$["נכון. הפסקה כותבת שהשפעת בית הספר התפשטה דווקא בגלל שמוריו התפזרו ברחבי העולם לאחר הסגירה.", "לא נכון. הפסקה מציינת שהמורים המשיכו ללמד ולבנות בארצות הברית ובמקומות אחרים.", "לא נכון. הפסקה מזכירה במפורש מבקרים שטענו שהסגנון קר ואדיש.", "לא נכון. הפסקה כותבת שאדריכלים ברוח דומה בנו חלק גדול ממרכז תל אביב, ולא שכולם הוכשרו בדסאו."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=bauhaus, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$Which of the following is NOT mentioned in the third paragraph?$q$, $q$["The school moved in 1925 into a building that Gropius had designed.", "The last director of the school was Mies van der Rohe.", "The authorities forced the school to close down in 1933.", "The school earned money by licensing its designs to manufacturers."]$q$::jsonb, 3, $q$["לא נכון. פרט זה אכן מופיע בפסקה השלישית, ולכן אינו התשובה המבוקשת.", "לא נכון. פרט זה אכן מופיע בפסקה השלישית, ולכן אינו התשובה המבוקשת.", "לא נכון. פרט זה אכן מופיע בפסקה השלישית, ולכן אינו התשובה המבוקשת.", "נכון. מכירת הרישיונות ליצרנים מופיעה בפסקה השנייה ולא בשלישית, ולכן זהו הפרט שאינו מוזכר שם."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=bauhaus, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the second paragraph, the word "prototypes" most nearly means —$q$, $q$["original models to be copied in production", "decorative objects made only for exhibition", "drawings kept in the school's private archive", "hand-made goods sold directly to wealthy buyers"]$q$::jsonb, 0, $q$["נכון. המשפט מדבר על עיצובים שנועדו לבתי חרושת ועל רישיונות ליצרנים, ולכן 'prototypes' פירושו דגמים ראשוניים שנועדו לייצור.", "לא נכון. הפסקה מדגישה ייצור תעשייתי ולא חפצי תצוגה.", "לא נכון. המילה מתייחסת לדגמים לייצור, לא לשרטוטים בארכיון.", "לא נכון. הפסקה מתארת מעבר מעבודת יד לתעשייה, כלומר ההפך מכך."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["Designs were now meant as prototypes for factories"]$q$::jsonb, $q$shabbat batch E1, passage=bauhaus, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$When the Pictures Learned to Talk$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$When the Pictures Learned to Talk$q$, $q$Silent films were never really silent. In most theaters a pianist, an organist or even a small orchestra played along with the picture. Printed cards called intertitles carried the important lines of dialogue, and skilled actors told the rest of the story with their faces and their bodies. Because there was no recorded speech, the same print could be shown anywhere in the world with new cards in the local language. Studios in Europe, Japan and the United States all exported their films with little difficulty.

Inventors had been trying to join sound to film for years, but the results were quiet, brief or badly synchronized. Warner Brothers took a risk with a system that played music from large discs turning beside the projector. In 1927 the studio released The Jazz Singer, which combined a recorded score with a few songs and a short passage of speech. Audiences lined up around the block, and other studios understood that they could not afford to wait. Within about three years almost every American feature film was being made with sound.

The change was harder than it looked. Early microphones picked up every noise, so the camera had to be shut inside a padded box and could barely move. Actors were forced to stand near hidden microphones, and some performers with unsuitable voices lost their careers. Theaters had to install expensive equipment, and small ones in poor districts closed instead. Charlie Chaplin resisted the trend for years, releasing City Lights in 1931 with music and effects but no spoken dialogue.$q$, $q$culture / film$q$, 3, 255, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, how did audiences learn what the characters were saying?$q$, $q$["An actor stood beside the screen and spoke all of the lines aloud.", "Printed cards showed the important lines between the scenes.", "The orchestra played a different melody for each character in the film.", "Programs handed out at the door contained the full text of the dialogue."]$q$::jsonb, 1, $q$["לא נכון. הפסקה אינה מזכירה שחקן שהקריא את הדיאלוג ליד המסך.", "נכון. הפסקה מציינת שכרטיסיות מודפסות, הקרויות intertitles, נשאו את שורות הדיאלוג החשובות.", "לא נכון. הפסקה מזכירה ליווי מוזיקלי, אך לא מנגינה נפרדת לכל דמות.", "לא נכון. הפסקה אינה מזכירה תוכניות שחולקו לקהל."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=silent-to-sound, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["describe how one successful film pushed the whole industry towards sound.", "explain why silent films could be exported so easily to other countries.", "list the technical problems that early microphones created on the film set.", "describe the musicians who accompanied silent films in the larger theaters."]$q$::jsonb, 0, $q$["נכון. הפסקה השנייה מתארת את מערכת ורנר, את הצלחת 'זמר הג'אז' ואת המעבר המהיר של כל התעשייה לקול.", "לא נכון. קלות הייצוא מוסברת בפסקה הראשונה, ולא בשנייה.", "לא נכון. בעיות המיקרופונים מתוארות בפסקה השלישית, ולא בשנייה.", "לא נכון. הנגנים המלווים מתוארים בפסקה הראשונה, ולא בשנייה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=silent-to-sound, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the second paragraph, how did the Warner Brothers system produce the sound?$q$, $q$["From large discs that turned next to the projector.", "From a magnetic strip attached to the edge of the film itself.", "From loudspeakers behind the screen that the pianist controlled.", "From musicians hidden below the stage who followed a written score."]$q$::jsonb, 0, $q$["נכון. הפסקה מציינת שוורנר ברדרס השתמשה במערכת שניגנה מוזיקה מתקליטים גדולים שהסתובבו לצד המקרן.", "לא נכון. הפסקה אינה מזכירה פס מגנטי על סרט הצילום.", "לא נכון. הרמקולים והפסנתרן אינם מוזכרים כמקור הצליל במערכת הזו.", "לא נכון. נגנים חיים מתוארים בפסקה הראשונה כליווי לסרט האילם, ולא כמערכת של וורנר."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["a system that played music from large discs turning beside the projector"]$q$::jsonb, $q$shabbat batch E1, passage=silent-to-sound, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the third paragraph, all of the following are true EXCEPT —$q$, $q$["The camera had to be enclosed so that microphones would not record its noise.", "Some actors lost their careers because their voices did not suit the new films.", "Small theaters in poor districts shut down rather than buy the new equipment.", "Charlie Chaplin adopted spoken dialogue earlier than most other filmmakers."]$q$::jsonb, 3, $q$["לא נכון. זו קביעה נכונה על פי הפסקה השלישית, ולכן אינה החריג המבוקש.", "לא נכון. זו קביעה נכונה על פי הפסקה השלישית, ולכן אינה החריג המבוקש.", "לא נכון. זו קביעה נכונה על פי הפסקה השלישית, ולכן אינה החריג המבוקש.", "נכון. זו הקביעה השגויה: הפסקה כותבת שצ'פלין התנגד למגמה במשך שנים והוציא ב-1931 סרט בלי דיאלוג מדובר."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["Charlie Chaplin resisted the trend for years"]$q$::jsonb, $q$shabbat batch E1, passage=silent-to-sound, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$Based on the passage, what can be inferred about the export of films after 1927?$q$, $q$["It became more complicated, because recorded speech was tied to one language.", "It stopped completely until dubbing equipment was invented in the 1930s.", "It grew easier, since recorded sound made the stories clearer to foreign viewers.", "It was controlled by a single company that owned the patents on sound."]$q$::jsonb, 0, $q$["נכון. הפסקה הראשונה מסבירה שהיעדר דיבור מוקלט איפשר להחליף כרטיסיות בשפה המקומית, ומכאן שקול מוקלט הצמיד את הסרט לשפה אחת והקשה על הייצוא.", "לא נכון. הקטע אינו טוען שהייצוא נפסק לחלוטין.", "לא נכון. זו מסקנה הפוכה לרמז שבפסקה הראשונה על היתרון של סרטים ללא דיבור מוקלט.", "לא נכון. הקטע מזכיר את ורנר ברדרס כחלוצה, אך אינו מדבר על שליטה בפטנטים או על ייצוא."]$q$::jsonb, $q$inference$q$, $q$text$q$, null, $q$shabbat batch E1, passage=silent-to-sound, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$A Penny to Stand at the Globe$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$A Penny to Stand at the Globe$q$, $q$The Globe Theatre opened in 1599 on the south bank of the River Thames, across the water from the city of London. It was built by the acting company to which William Shakespeare belonged, using timber taken from an older playhouse that they had dismantled. The site lay outside the control of the city authorities, who disapproved of plays and of the crowds they attracted. The building was a tall wooden ring with three levels of covered galleries around an open yard. Performances took place in the afternoon, since the stage depended entirely on daylight.

A place in the yard cost one penny, and those who paid it stood on their feet for the whole play. Wealthier visitors paid more for a bench in the galleries, and a cushion cost extra. Scholars estimate that the theatre could hold something close to three thousand people. The audience mixed apprentices, servants, merchants and gentlemen, which was unusual in a society organized around rank. Spectators ate, talked back to the actors and showed their opinions loudly, so a play had to hold their attention.

The stage itself was almost bare, with no painted scenery to explain where a scene was set. Instead the words did that work, which is why the plays describe forests, battlefields and moonlit nights so vividly. Women were not permitted to perform in public, so boys played the female parts. In 1613 a cannon fired during a performance set the thatched roof alight, and the theatre burned to the ground within an hour. A new Globe rose on the same site the following year, and a modern reconstruction opened nearby in 1997.$q$, $q$arts / theatre$q$, 3, 270, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, why was the Globe built outside the city of London?$q$, $q$["The acting company could not afford any land inside the city walls.", "The site lay beyond the reach of officials who disliked plays and crowds.", "The riverbank gave the stage better daylight for afternoon performances.", "The older playhouse they had dismantled also stood on the south bank."]$q$::jsonb, 1, $q$["לא נכון. הפסקה אינה מזכירה מחירי קרקע או קשיים כספיים של הלהקה.", "נכון. הפסקה מציינת שהמגרש היה מחוץ לשליטת שלטונות העיר, שהתנגדו להצגות ולקהל שהן משכו.", "לא נכון. אור היום מוזכר כסיבה לשעת ההצגה, ולא כסיבה למיקום מחוץ לעיר.", "לא נכון. הפסקה אינה מציינת היכן עמד בית ההצגות הישן."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=globe-theatre, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["describe who came to the Globe, what they paid and how they behaved.", "explain why the company used timber from an earlier playhouse.", "describe the bare stage and the language that replaced painted scenery.", "explain how the theatre was destroyed by fire and later rebuilt."]$q$::jsonb, 0, $q$["נכון. הפסקה השנייה עוסקת במחירי הכניסה, בהרכב הקהל ובהתנהגותו הרועשת במהלך ההצגה.", "לא נכון. השימוש בקורות מבית הצגות ישן מוזכר בפסקה הראשונה, ולא בשנייה.", "לא נכון. הבמה החשופה והשפה המתארת מופיעות בפסקה השלישית, ולא בשנייה.", "לא נכון. השרפה והבנייה מחדש מתוארות בפסקה השלישית, ולא בשנייה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=globe-theatre, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$Based on the passage, what can be inferred about the playwrights of the period?$q$, $q$["They wrote descriptive language partly because the stage had no scenery.", "They had to submit every new play to the city authorities before performance.", "They wrote mainly for the wealthy spectators seated in the covered galleries.", "They avoided female characters because women were not allowed to act."]$q$::jsonb, 0, $q$["נכון. הפסקה השלישית מסבירה שהמילים מילאו את תפקיד התפאורה, ומכאן שהתיאורים העשירים נבעו בין היתר מהבמה החשופה.", "לא נכון. הקטע מציין שהשלטונות התנגדו להצגות, אך אינו מזכיר חובת אישור מראש לכל מחזה.", "לא נכון. הפסקה השנייה מדגישה קהל מעורב, והמחזות היו צריכים להחזיק את תשומת ליבו כולו.", "לא נכון. הפסקה מציינת שנערים גילמו את התפקידים הנשיים, כלומר דמויות נשים אכן הופיעו במחזות."]$q$::jsonb, $q$inference$q$, $q$text$q$, null, $q$shabbat batch E1, passage=globe-theatre, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the second paragraph that —$q$, $q$["the Globe drew spectators from social groups that rarely mixed elsewhere", "the theatre earned most of its income from the pennies paid in the yard", "the actors took no notice of how the audience reacted during a performance", "only wealthy Londoners were permitted to attend plays at the Globe"]$q$::jsonb, 0, $q$["נכון. הפסקה מציינת שהקהל ערבב שוליות, משרתים, סוחרים ואדונים, ושדבר כזה היה חריג בחברה המאורגנת לפי מעמדות.", "לא נכון. הפסקה מציינת מחירים שונים אך אינה אומרת מהיכן הגיע רוב ההכנסה.", "לא נכון. הפסקה מדגישה שהצופים הגיבו בקול ושההצגה נדרשה להחזיק את תשומת ליבם.", "לא נכון. הפסקה מתארת קהל מעורב, כולל שוליות ומשרתים ששילמו פני אחד."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=globe-theatre, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the last paragraph is to —$q$, $q$["explain how the price of admission differed between the yard and the galleries.", "describe the staging conventions of the Globe and the later history of the building.", "argue that the plays of the period were too difficult for ordinary spectators.", "describe the construction of the wooden ring and its position beside the river."]$q$::jsonb, 1, $q$["לא נכון. מחירי הכניסה מתוארים בפסקה השנייה, ולא באחרונה.", "נכון. הפסקה האחרונה מתארת את הבמה החשופה, את תפקיד המילים ואת הנערים בתפקידי נשים, ולאחר מכן את השרפה ואת הבנייה מחדש.", "לא נכון. הפסקה אינה טוענת דבר על רמת הקושי של המחזות עבור הקהל.", "לא נכון. בניית הטבעת העץ ומיקומה מתוארים בפסקה הראשונה, ולא באחרונה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=globe-theatre, q5$q$, 5, true);
  end if;
end $$;