do $$ declare v_pid uuid; begin

  if not exists (select 1 from reading_passages where title = $q$The Press and the New Reader$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$The Press and the New Reader$q$, $q$Before the middle of the fifteenth century, nearly every book in Europe was copied out by hand. A skilled scribe might spend months on a single volume, and the finished book cost far more than most families could ever spend. Books were therefore owned mainly by monasteries, universities and wealthy nobles. Around 1450, a goldsmith in Mainz named Johannes Gutenberg combined several existing ideas into a working printing system. His key innovation was movable metal type: individual letters that could be arranged, inked, printed and then reused for a completely different page.

The new technology spread across Europe with remarkable speed. Within fifty years, printing workshops were operating in hundreds of towns from Italy to Scandinavia. Prices fell sharply, and books that had once been treasures became ordinary objects that a merchant or a student could afford. Printers also standardized features that readers now take for granted, such as title pages, page numbers and indexes. These small conveniences made it far easier to find a particular passage without reading an entire volume.

The effects on reading itself were profound. Silent, private reading gradually replaced the older habit of reading aloud to a group, because copies were plentiful enough for each person to hold one. Scholars could compare several editions of the same text side by side and notice errors that centuries of hand-copying had introduced. Printing also encouraged writing in everyday languages rather than Latin, since local readers formed the largest market. However, the change was not universally welcomed, and some scholars complained that cheap books would flood the world with careless and unreliable work.$q$, $q$culture / literature$q$, 4, 264, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$An appropriate title for this text would be —$q$, $q$["The Careful Work of Medieval Scribes and Their Monastery Libraries", "Johannes Gutenberg's Career as a Goldsmith in the City of Mainz", "How Printing Changed the Price, the Form and the Habits of Reading", "Why Some Scholars Objected to the Spread of Cheap Printed Books"]$q$::jsonb, 2, $q$["לא נכון. עבודת המעתיקים מוזכרת בפסקה הראשונה כרקע בלבד, ואינה הנושא המרכזי של הקטע.", "לא נכון. גוטנברג מוזכר במשפט אחד בלבד, והקטע אינו עוסק בקורות חייו.", "נכון. הקטע עוקב אחר ירידת מחירי הספרים, השינויים בצורת הספר והשינוי בהרגלי הקריאה — וזהו הנושא המרכזי שלו.", "לא נכון. התנגדות המלומדים מופיעה במשפט האחרון בלבד, ואינה הרעיון המרכזי של הקטע."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E1, passage=printing-press, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the second paragraph, what did printers introduce that helped readers locate a particular passage?$q$, $q$["Workshops in hundreds of towns stretching from Italy to Scandinavia.", "Reading aloud in groups, which allowed several people to share one copy.", "Numbered pages, opening title pages and indexes that guided the reader.", "Translations of Latin works prepared for scholars in other countries."]$q$::jsonb, 2, $q$["לא נכון. בתי הדפוס הרבים אכן מוזכרים בפסקה, אך הם אינם האמצעי שסייע לקורא לאתר קטע מסוים.", "לא נכון. קריאה בקול בקבוצה מוזכרת בפסקה השלישית כהרגל שנעלם, ולא כאמצעי עזר שהדפוסים הנהיגו.", "נכון. הפסקה מציינת ששערי ספר, מספור עמודים ומפתחות הפכו לתקן, וכך היה קל בהרבה למצוא קטע מסוים בלי לקרוא את כל הספר.", "לא נכון. הפסקה אינה מזכירה תרגומים; הכתיבה בשפות המקום מוזכרת בפסקה השלישית."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["such as title pages, page numbers and indexes"]$q$::jsonb, $q$shabbat batch E1, passage=printing-press, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the last paragraph is to —$q$, $q$["explain how Gutenberg combined existing ideas into a working printing system.", "list the European towns where printing workshops were established after 1450.", "describe how the abundance of printed books altered the way people read.", "argue that hand-copied manuscripts were more accurate than early printed books."]$q$::jsonb, 2, $q$["לא נכון. זהו תוכן הפסקה הראשונה, ולא מטרת הפסקה האחרונה.", "לא נכון. התפשטות בתי הדפוס מתוארת בפסקה השנייה, ולא בפסקה האחרונה.", "נכון. הפסקה האחרונה מתארת כיצד ריבוי הספרים המודפסים שינה את אופן הקריאה — קריאה שקטה, השוואת מהדורות וכתיבה בשפות המקום.", "לא נכון. הפסקה דווקא מציינת שהעתקה ידנית הכניסה שגיאות לאורך מאות שנים."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=printing-press, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the second paragraph that —$q$, $q$["printing spread quickly because rulers across Europe ordered towns to build workshops", "readers of the time were unable to locate information without an index", "most printers of this period worked in Scandinavia rather than in Italy", "books reached a much wider range of buyers than before"]$q$::jsonb, 3, $q$["לא נכון. הפסקה אינה מזכירה צווים של שליטים; היא מתארת התפשטות מהירה בלבד.", "לא נכון. הפסקה אומרת שהמפתחות הקלו על החיפוש, לא שבלעדיהם היה בלתי אפשרי.", "לא נכון. הפסקה מזכירה את איטליה ואת סקנדינביה כקצוות התפשטות, ואינה טוענת שרוב הדפוסים היו בסקנדינביה.", "נכון. הפסקה מציינת שהמחירים צנחו ושספרים הפכו לחפצים רגילים שסוחר או סטודנט יכלו להרשות לעצמם, ומכאן שקהל הקונים התרחב מאוד."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=printing-press, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the third paragraph, the word "profound" most nearly means —$q$, $q$["difficult for ordinary readers to notice at all", "small and quickly forgotten", "far-reaching and deep in their consequences", "expressed in language that few people could understand"]$q$::jsonb, 2, $q$["לא נכון. המילה מתארת את עומק ההשפעה, לא את מידת הבחנתם של הקוראים בה.", "לא נכון. זו משמעות הפוכה; הפסקה מתארת שינויים שנמשכו והתבססו.", "נכון. הפסקה מפרטת שינויים עמוקים בהרגלי הקריאה, ולכן 'profound' פירושו עמוק ובעל השלכות מרחיקות לכת.", "לא נכון. המילה אינה מתייחסת לרמת הלשון של הטקסטים."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["The effects on reading itself were profound."]$q$::jsonb, $q$shabbat batch E1, passage=printing-press, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$The Theft That Made a Portrait Famous$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$The Theft That Made a Portrait Famous$q$, $q$Leonardo da Vinci painted the portrait known as the Mona Lisa in Florence during the early years of the sixteenth century. He carried the picture with him to France, where it entered the royal collection and eventually reached the Louvre in Paris. For centuries it hung there as one admired painting among thousands of others. Art historians praised Leonardo's soft modeling and the strange, shifting expression of the sitter. Ordinary visitors, however, walked past it without much notice, and newspapers rarely mentioned it at all.

That changed in the late summer of 1911, when the staff of the Louvre realized that the painting was gone. The thief was Vincenzo Peruggia, an Italian craftsman who had helped fit protective glass onto pictures in the Louvre. He had hidden in the building overnight, lifted the small wooden panel from its hooks and walked out with it under his clothing. French police questioned hundreds of people, including the poet Guillaume Apollinaire and the young painter Pablo Picasso. The empty wall itself became an attraction, and crowds lined up to stare at the iron pegs where the portrait had hung.

Newspapers across the world printed the picture beside stories about the hunt, and millions of readers saw it for the first time. Peruggia kept the panel in his lodgings for two years before offering it to a dealer in Florence, who alerted the authorities. He claimed he had acted out of patriotism, wishing to return an Italian masterpiece to Italy. When the painting came back to Paris in 1914, it was greeted like a returning celebrity rather than a quiet object of study. Its fame has only grown since then, although that fame now rests as much on the theft as on the brushwork itself.$q$, $q$arts / visual$q$, 4, 289, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$What is the main idea of the passage?$q$, $q$["Leonardo's painting technique explains why art historians have always admired the portrait.", "The Louvre improved its security arrangements after a long series of famous thefts.", "A theft in 1911 turned a respected painting into the most famous picture in the world.", "Vincenzo Peruggia was driven by patriotism rather than by any hope of financial reward."]$q$::jsonb, 2, $q$["לא נכון. שבחי ההיסטוריונים לטכניקה של לאונרדו מופיעים כפרט בפסקה הראשונה, ואינם הרעיון המרכזי.", "לא נכון. הקטע אינו מזכיר כלל שיפורי אבטחה בלובר או סדרת גניבות.", "נכון. הקטע מתאר ציור מוערך אך לא מפורסם במיוחד, ומראה כיצד הגניבה של 1911 והסיקור העיתונאי הפכו אותו לתמונה המפורסמת בעולם.", "לא נכון. טענת הפטריוטיות מופיעה במשפט אחד בפסקה השלישית, והיא פרט בתוך הסיפור ולא הרעיון המרכזי."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E1, passage=mona-lisa-theft, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the passage, what connection did the thief have with the museum before the theft?$q$, $q$["He had been dismissed from the museum after an earlier attempt at theft.", "He had studied Leonardo's technique as a student in the museum's own art school.", "He had worked on the job of fitting glass over paintings there.", "He had sold several Italian paintings to the Louvre through a dealer in Florence."]$q$::jsonb, 2, $q$["לא נכון. הקטע אינו מזכיר פיטורים או ניסיון גניבה קודם.", "לא נכון. הקטע אינו מזכיר בית ספר לאמנות של המוזיאון או לימודים של פרוג'ה.", "נכון. הפסקה השנייה מציינת שפרוג'ה היה בעל מלאכה איטלקי שסייע בהתקנת זכוכית מגן על תמונות בלובר.", "לא נכון. הסוחר מפירנצה מופיע רק בפסקה השלישית, כמי שפרוג'ה ניסה למכור לו את הציור."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["helped fit protective glass onto pictures in the Louvre"]$q$::jsonb, $q$shabbat batch E1, passage=mona-lisa-theft, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the first paragraph is to —$q$, $q$["describe the search that the French police conducted after the painting disappeared.", "explain how newspapers around the world reported the story of the missing portrait.", "establish that the painting was respected by specialists but not widely known.", "argue that Leonardo should never have carried the picture with him to France."]$q$::jsonb, 2, $q$["לא נכון. חקירת המשטרה מתוארת בפסקה השנייה, ולא בראשונה.", "לא נכון. הסיקור העיתונאי העולמי מתואר בפסקה השלישית, ולא בראשונה.", "נכון. הפסקה הראשונה מציגה ציור שהמומחים העריכו אך המבקרים הרגילים חלפו על פניו, וכך מכינה את הרקע לשינוי שיבוא.", "לא נכון. הפסקה מציינת שלאונרדו לקח את הציור לצרפת כעובדה, ואינה שופטת את המעשה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=mona-lisa-theft, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the second paragraph, all of the following are true EXCEPT —$q$, $q$["The thief stayed inside the Louvre overnight before removing the painting.", "The police questioned the poet Guillaume Apollinaire in connection with the theft.", "Visitors came to look at the bare wall on which the portrait had been displayed.", "The painting was cut out of its frame and rolled up so that it could be carried away."]$q$::jsonb, 3, $q$["לא נכון. זו קביעה נכונה על פי הפסקה השנייה, ולכן אינה החריג המבוקש — הגנב אכן התחבא בבניין במשך הלילה.", "לא נכון. זו קביעה נכונה על פי הפסקה השנייה, ולכן אינה החריג המבוקש — אפולינר אכן נחקר.", "לא נכון. זו קביעה נכונה על פי הפסקה השנייה, ולכן אינה החריג המבוקש — קהל אכן הגיע להתבונן בקיר הריק.", "נכון. זו הקביעה השגויה: הפסקה כותבת שהגנב הוריד לוח עץ קטן מהוויים ויצא איתו מתחת לבגדיו, ולא שחתך את הציור מהמסגרת וגלגל אותו."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["lifted the small wooden panel from its hooks"]$q$::jsonb, $q$shabbat batch E1, passage=mona-lisa-theft, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the sentence "He claimed he had acted out of patriotism, wishing to return an Italian masterpiece to Italy," the word "He" refers to —$q$, $q$["the art dealer in Florence who contacted the authorities", "the museum official who first discovered that the picture was missing", "Leonardo da Vinci, who had painted the portrait in Florence", "Vincenzo Peruggia, the man who had taken the painting"]$q$::jsonb, 3, $q$["לא נכון. הסוחר הוא זה שהודיע לרשויות, ולא זה שטען שפעל מתוך פטריוטיות.", "לא נכון. הקטע אינו מזכיר פקיד מסוים שגילה את הגניבה, אלא את צוות המוזיאון בכללותו.", "לא נכון. לאונרדו מוזכר בפסקה הראשונה בלבד, ואינו נושא המשפט הזה.", "נכון. המשפט הקודם עוסק בפרוג'ה שהחזיק את הלוח ואז הציע אותו לסוחר, ולכן 'He' מתייחס אליו."]$q$::jsonb, $q$reference_word$q$, $q$anchor$q$, $q$["He claimed he had acted out of patriotism, wishing to return an Italian masterpiece to Italy."]$q$::jsonb, $q$shabbat batch E1, passage=mona-lisa-theft, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$One Name, Many Film Industries$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$One Name, Many Film Industries$q$, $q$Indian cinema began in 1913, when Dadasaheb Phalke released Raja Harishchandra, a silent film drawn from Hindu mythology. Phalke had to train his own actors and assemble much of his own equipment, since almost nothing existed in India at the time. His success encouraged other producers, and small studios soon appeared in Bombay, Calcutta and Madras. Within two decades a national film culture had taken shape, supported by audiences who came in enormous numbers.

The arrival of sound in 1931 transformed the industry more deeply in India than in almost any other country. The first Indian talking picture, Alam Ara, contained several songs, and audiences immediately expected music in every film that followed. Songs became so central that composers and playback singers grew as famous as the actors on the screen. Sound also divided the market by language, because a film in Hindi could not simply be shown to Tamil or Bengali speakers.

The Hindi-language industry based in Bombay, now Mumbai, gradually became the largest and most visible of these regional centers. Journalists began calling it Bollywood in the 1970s, joining the name of the city to that of Hollywood. The label is misleading, however, since Indian cinema has always been many industries rather than one. Studios in the south produce films in Tamil, Telugu, Malayalam and Kannada that often outsell Hindi releases in their own regions.

Taken together, these industries make India the largest producer of feature films in the world. A typical popular release mixes romance, comedy, family drama, music and action within a single long story. Critics once dismissed this blending as commercial noise, yet many scholars now study it as a distinct narrative tradition. Indian films also travel widely, drawing devoted audiences across Africa, the Middle East and Central Asia, and among Indian communities abroad.$q$, $q$culture / film$q$, 4, 297, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$An appropriate title for this text would be —$q$, $q$["Dadasaheb Phalke and the Making of the First Indian Feature Film", "The Objections That Critics Have Raised Against Popular Indian Storytelling", "Why Songs Became a Necessary Ingredient of Every Hindi Film", "The Growth of Indian Cinema and the Many Industries Behind One Name"]$q$::jsonb, 3, $q$["לא נכון. פאלקה והסרט הראשון מופיעים בפסקה הראשונה בלבד, כנקודת פתיחה ולא כנושא הקטע.", "לא נכון. ביקורת המבקרים מוזכרת במשפט אחד בפסקה האחרונה בלבד.", "לא נכון. מרכזיות השירים היא פרט חשוב בפסקה השנייה, אך אינה מקיפה את הקטע כולו.", "נכון. הקטע עוקב אחר התפתחות הקולנוע ההודי ומדגיש שמאחורי השם האחד עומדות תעשיות רבות בשפות שונות."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E1, passage=bollywood, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the second paragraph, how did the coming of sound affect the Indian film market?$q$, $q$["It reduced the number of songs that producers were willing to pay for.", "It allowed one film to be shown across the whole country without any changes.", "It split the audience by language, since a Hindi film did not suit Tamil speakers.", "It made imported foreign films more popular than films produced inside India."]$q$::jsonb, 2, $q$["לא נכון. הפסקה מציינת בדיוק את ההפך: הקהל ציפה למוזיקה בכל סרט.", "לא נכון. זו בדיוק היכולת שאבדה עם המעבר לקול, כפי שמתואר בסוף הפסקה.", "נכון. הפסקה כותבת שהקול חילק את השוק לפי שפה, משום שסרט בהינדי לא התאים לדוברי טמילית או בנגלית.", "לא נכון. הפסקה אינה עוסקת כלל בסרטים מיובאים."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=bollywood, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the third paragraph is to —$q$, $q$["describe the difficulties Phalke faced when he trained his first group of actors.", "show that playback singers became more famous than the actors who appeared on screen.", "list the regions in which Indian films have found their most devoted foreign audiences.", "explain where the name Bollywood came from and why it describes the country poorly."]$q$::jsonb, 3, $q$["לא נכון. הקשיים של פאלקה מתוארים בפסקה הראשונה, ולא בשלישית.", "לא נכון. תהילת הזמרים מופיעה בפסקה השנייה, ולא בשלישית.", "לא נכון. הקהלים בחו\"ל מוזכרים בפסקה האחרונה, ולא בשלישית.", "נכון. הפסקה השלישית מסבירה כיצד נוצר השם בוליווד ומדוע הוא מטעה, שכן הקולנוע ההודי מורכב מתעשיות רבות."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=bollywood, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$Based on the statement that critics "once dismissed this blending as commercial noise," what can be inferred?$q$, $q$["The critics of Indian cinema were mainly foreign journalists with little local knowledge.", "Indian producers stopped mixing genres as soon as critics objected to the practice.", "Scholarly opinion about popular Indian cinema has shifted over time.", "Popular Indian films are now widely considered better than the films of other countries."]$q$::jsonb, 2, $q$["לא נכון. הקטע אינו אומר דבר על זהותם או מוצאם של המבקרים.", "לא נכון. הפסקה מציינת שהערבוב נותר מאפיין טיפוסי של הסרטים, ולא שהופסק.", "נכון. המילה 'once' והניגוד 'yet many scholars now study it' מלמדים שהיחס האקדמי לערבוב הז'אנרים השתנה עם השנים.", "לא נכון. הפסקה אומרת שחוקרים לומדים את המסורת הזו, ולא שהיא נחשבת עדיפה על קולנוע אחר."]$q$::jsonb, $q$inference$q$, $q$anchor$q$, $q$["Critics once dismissed this blending as commercial noise"]$q$::jsonb, $q$shabbat batch E1, passage=bollywood, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the third paragraph, the word "misleading" most nearly means —$q$, $q$["difficult for foreign readers to pronounce", "borrowed from an older foreign language", "used only by journalists working outside India", "likely to give a false impression of the facts"]$q$::jsonb, 3, $q$["לא נכון. המילה אינה עוסקת בהגייה של השם.", "לא נכון. הפסקה אמנם מסבירה את מקור השם, אך 'misleading' אינו עוסק בשאילה מלשון אחרת.", "לא נכון. הפסקה כותבת שעיתונאים הם שטבעו את השם, אך זו אינה משמעות המילה.", "נכון. המשך המשפט מסביר שהשם יוצר רושם שגוי, כאילו מדובר בתעשייה אחת ולא ברבות."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["The label is misleading, however, since Indian cinema has always been many industries rather than one."]$q$::jsonb, $q$shabbat batch E1, passage=bollywood, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$How the Piano Displaced the Harpsichord$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$How the Piano Displaced the Harpsichord$q$, $q$For most of the seventeenth century, the harpsichord was the leading keyboard instrument in European music. Pressing a key caused a small quill to pluck a string, producing a bright and precise sound. Because the quill plucked with the same force however hard the player pressed, the instrument could not grow louder or softer under the fingers. Builders worked around this limit by adding extra sets of strings and keyboards that the player could switch between. The result was a range of contrasting tone colors, but not the gradual swell that singers and violinists took for granted.

Around 1700, Bartolomeo Cristofori, who cared for the instruments of the Medici court in Florence, built a keyboard that struck its strings with small hammers. His mechanism threw each hammer at the string and then let it fall back at once, so the string could go on ringing freely. Because the hammer moved faster when the key was pressed harder, the player could shape the volume of every note. Cristofori called his invention a harpsichord with soft and loud, a phrase later shortened to pianoforte and finally to piano. Few musicians paid attention at first, and the instrument remained a curiosity for several decades.

German builders improved the action during the eighteenth century, and composers slowly began writing music that depended on changes of volume. Mozart performed on pianos in Vienna, and by the end of the century publishers were advertising sonatas for the newer instrument. Nineteenth-century makers added iron frames, thicker strings and felt-covered hammers, producing a tone powerful enough for large concert halls. The harpsichord, which could not compete in such spaces, almost disappeared from musical life for a hundred years. It returned only in the twentieth century, when performers rediscovered it in order to play older music in something closer to its original sound.$q$, $q$arts / music$q$, 5, 303, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$What is the main idea of the passage?$q$, $q$["Cristofori's hammer mechanism was the most complicated device built during his century.", "Harpsichord builders added extra keyboards in order to imitate the sound of the human voice.", "The piano replaced the harpsichord because it let players control the volume of each note.", "Concert halls of the nineteenth century were too large for most instruments of the period."]$q$::jsonb, 2, $q$["לא נכון. הקטע מתאר את המנגנון של קריסטופורי אך אינו טוען שהיה המכשיר המורכב ביותר במאה שלו.", "לא נכון. הפסקה הראשונה מסבירה שהמקלדות הנוספות נועדו לגוונים מנוגדים, לא לחיקוי הקול האנושי.", "נכון. הקטע בנוי סביב מגבלת עוצמת הקול של הצ'מבלו ופתרונה בפסנתר, ומסביר כך את ההחלפה בין שני הכלים.", "לא נכון. גודל אולמות הקונצרטים הוא פרט בפסקה השלישית התומך בטיעון, ולא הרעיון המרכזי."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E1, passage=piano-harpsichord, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the passage, harpsichord builders added extra sets of strings and keyboards in order to —$q$, $q$["make the instrument easier for beginners to learn", "reduce the cost of building a large and complicated keyboard instrument", "allow the player to press the keys with far greater physical force", "offer contrasting tone colors despite the fixed volume of each note"]$q$::jsonb, 3, $q$["לא נכון. הפסקה אינה עוסקת כלל בקלות הלימוד של הכלי.", "לא נכון. הפסקה אינה מזכירה שיקולי עלות בבניית הכלי.", "לא נכון. הפסקה מציינת שעוצמת הפריטה לא הושפעה מכוח הלחיצה כלל.", "נכון. הפסקה הראשונה מסבירה שהתוספות נועדו לעקוף את מגבלת עוצמת הקול, והתוצאה הייתה מגוון של גוונים מנוגדים."]$q$::jsonb, $q$explicit_detail$q$, $q$anchor$q$, $q$["adding extra sets of strings and keyboards that the player could switch between"]$q$::jsonb, $q$shabbat batch E1, passage=piano-harpsichord, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the second paragraph is to —$q$, $q$["describe how Cristofori's hammer action gave the player control over volume.", "explain why the harpsichord nearly vanished from European musical life.", "list the composers who wrote sonatas for the newly invented instrument.", "describe the improvements that nineteenth-century makers introduced to the piano."]$q$::jsonb, 0, $q$["נכון. הפסקה השנייה מתארת את מנגנון הפטישים של קריסטופורי ומסבירה כיצד הוא איפשר לנגן לעצב את עוצמת כל צליל.", "לא נכון. היעלמות הצ'מבלו מתוארת בפסקה השלישית, ולא בשנייה.", "לא נכון. הסונטות והמו\"לים מופיעים בפסקה השלישית, ולא בשנייה.", "לא נכון. השיפורים של המאה התשע-עשרה מתוארים בפסקה השלישית, ולא בשנייה."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=piano-harpsichord, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the last paragraph that —$q$, $q$["the harpsichord came back because audiences had grown tired of the piano's loud tone", "changes in the size of concert spaces affected which instrument survived", "Mozart preferred the harpsichord to the pianos that were available in Vienna", "iron frames were first introduced by German builders in the eighteenth century"]$q$::jsonb, 1, $q$["לא נכון. הפסקה מציינת שהצ'מבלו חזר כדי לנגן מוזיקה עתיקה בצליל קרוב למקור, ולא בגלל עייפות מהפסנתר.", "נכון. הפסקה קושרת בין הצליל החזק המתאים לאולמות גדולים לבין העובדה שהצ'מבלו לא יכול היה להתחרות במרחבים כאלה ונעלם.", "לא נכון. הפסקה מציינת שמוצרט ניגן על פסנתרים בווינה, ואינה מייחסת לו העדפה לצ'מבלו.", "לא נכון. הפסקה מייחסת את המסגרות מברזל ליצרני המאה התשע-עשרה, ולא לבנאים הגרמנים של המאה הקודמת."]$q$::jsonb, $q$inference$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=piano-harpsichord, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the second paragraph, the word "curiosity" most nearly means —$q$, $q$["an object of interest that is not yet widely used", "a strong wish to learn about new inventions", "an instrument reserved for royal and noble households", "a device that proved impossible to build a second time"]$q$::jsonb, 0, $q$["נכון. המשפט מציין שמעטים שמו לב לכלי, ולכן 'curiosity' פירושו דבר מעניין שעדיין אינו בשימוש נרחב.", "לא נכון. כאן המילה מתארת חפץ ולא רגש של סקרנות.", "לא נכון. הפסקה אינה מגבילה את הכלי לחצרות מלוכה; היא מציינת שמעטים התעניינו בו.", "לא נכון. הפסקה אינה טוענת שהכלי לא ניתן היה לשחזור."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["the instrument remained a curiosity for several decades"]$q$::jsonb, $q$shabbat batch E1, passage=piano-harpsichord, q5$q$, 5, true);
  end if;

  if not exists (select 1 from reading_passages where title = $q$Prints from the Floating World$q$) then
    insert into reading_passages(title, body, topic, difficulty, word_count, is_published, generation_batch)
      values ($q$Prints from the Floating World$q$, $q$During Japan's Edo period, city dwellers bought colored woodblock prints in enormous quantities. Known as ukiyo-e, or pictures of the floating world, they showed actors, travelers, courtesans and famous landscapes. A single print required a designer, a block cutter and a printer, and the finished sheet was cheap enough for ordinary workers to buy. Artists such as Hokusai, Hiroshige and Utamaro were commercial illustrators rather than court painters, and their work reached ordinary households.

Japan traded with the outside world only under tight restrictions until the middle of the nineteenth century. Once those limits eased, prints began arriving in European ports along with porcelain, lacquer and silk. Collectors in Paris and London bought them eagerly, and the Japanese displays at international exhibitions attracted very large crowds. By the 1870s critics had coined the term japonisme for the enthusiasm that followed.

European painters were struck less by the subjects of the prints than by the way the images were organized. Ukiyo-e artists used flat areas of color, firm outlines and high viewpoints instead of the shading and single perspective taught in the academies. They cut figures off at the edge of the sheet, allowing a bridge or a kimono to continue beyond the picture. Empty space was treated as an active part of the design rather than as an area waiting to be filled.

Vincent van Gogh collected hundreds of prints and painted careful copies of two designs by Hiroshige. Claude Monet hung his own collection at Giverny, and the cropped, off-center compositions of Edgar Degas owe an obvious debt to Japanese models. Mary Cassatt produced a series of color prints after seeing a large exhibition of Japanese work in Paris. Yet these artists were not imitating Japan so much as using its example to loosen their own inherited rules.$q$, $q$arts / visual$q$, 5, 299, true, $q$reading_shabbat_2026-09-05_E1$q$)
      returning id into v_pid;
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$An appropriate title for this text would be —$q$, $q$["The Craft Workshops That Produced Colored Prints in the Cities of Edo Japan", "How Japanese Prints Reached Europe and Changed the Way Painters Composed", "Vincent van Gogh's Careful Copies of Two Landscape Designs by Hiroshige", "The International Exhibitions That Introduced Asian Goods to European Buyers"]$q$::jsonb, 1, $q$["לא נכון. תהליך ההפקה מתואר בפסקה הראשונה בלבד, והקטע ממשיך הרבה מעבר לכך.", "נכון. הקטע עוקב אחר הדרך שבה ההדפסים הגיעו לאירופה ומסביר כיצד שינו את אופן בניית התמונה אצל ציירים אירופיים.", "לא נכון. ההעתקים של ואן גוך הם דוגמה אחת בפסקה האחרונה, ולא נושא הקטע.", "לא נכון. התערוכות הבינלאומיות מוזכרות במשפט אחד בפסקה השנייה בלבד."]$q$::jsonb, $q$main_idea$q$, $q$text$q$, null, $q$shabbat batch E1, passage=ukiyo-e-europe, q1$q$, 1, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$According to the first paragraph, all of the following are true EXCEPT —$q$, $q$["Ukiyo-e prints were bought in very large numbers by people living in cities.", "Producing a print required a designer, a block cutter and a printer.", "The prints showed subjects such as actors, travelers and famous landscapes.", "The prints were made for a small circle of aristocratic collectors at court."]$q$::jsonb, 3, $q$["לא נכון. זו קביעה נכונה על פי הפסקה הראשונה, ולכן אינה החריג המבוקש.", "לא נכון. זו קביעה נכונה על פי הפסקה הראשונה, ולכן אינה החריג המבוקש.", "לא נכון. זו קביעה נכונה על פי הפסקה הראשונה, ולכן אינה החריג המבוקש.", "נכון. זו הקביעה השגויה: הפסקה מדגישה שההדפסים היו זולים דיים לפועלים רגילים ושהאמנים היו מאיירים מסחריים ולא ציירי חצר."]$q$::jsonb, $q$explicit_detail$q$, $q$paragraph$q$, $q$["the finished sheet was cheap enough for ordinary workers to buy"]$q$::jsonb, $q$shabbat batch E1, passage=ukiyo-e-europe, q2$q$, 2, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$The main purpose of the third paragraph is to —$q$, $q$["explain which features of the prints most interested European painters.", "describe the trade routes that carried Japanese goods to European ports.", "argue that academic training in perspective was of no real value to painters.", "name the European artists who assembled the largest collections of prints."]$q$::jsonb, 0, $q$["נכון. הפסקה השלישית מפרטת את המאפיינים החזותיים — שטחי צבע שטוחים, קווי מתאר, נקודות מבט גבוהות וחיתוך דמויות — שמשכו את הציירים האירופיים.", "לא נכון. דרכי המסחר מוזכרות בפסקה השנייה, ולא בשלישית.", "לא נכון. הפסקה משווה בין שתי גישות אך אינה טוענת שההכשרה האקדמית חסרת ערך.", "לא נכון. שמות האספנים מופיעים בפסקה האחרונה, ולא בשלישית."]$q$::jsonb, $q$paragraph_purpose$q$, $q$paragraph$q$, null, $q$shabbat batch E1, passage=ukiyo-e-europe, q3$q$, 3, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$It can be inferred from the last sentence of the passage that European painters —$q$, $q$["eventually abandoned Japanese models and returned to their academic training", "regarded Japanese prints as technically superior to all European painting", "used Japanese prints to question the conventions they had been taught", "traveled to Japan in order to study printmaking with local masters"]$q$::jsonb, 2, $q$["לא נכון. המשפט אינו מדבר על נטישה של המודלים היפניים ועל חזרה לאקדמיה.", "לא נכון. המשפט אינו מדרג את איכות ההדפסים היפניים מול הציור האירופי.", "נכון. המשפט אומר שהאמנים השתמשו בדוגמה היפנית כדי לרופף את הכללים שירשו, כלומר כדי לערער על המוסכמות שלמדו.", "לא נכון. הקטע מתאר הדפסים שהגיעו לאירופה, ואינו מזכיר נסיעות של ציירים ליפן."]$q$::jsonb, $q$inference$q$, $q$anchor$q$, $q$["Yet these artists were not imitating Japan so much as using its example to loosen their own inherited rules."]$q$::jsonb, $q$shabbat batch E1, passage=ukiyo-e-europe, q4$q$, 4, true);
    insert into reading_questions(passage_id, question_text, options, correct_option_index, explanations_he, question_type, window_size, highlight_spans, qa_note, display_order, is_published)
      values (v_pid, $q$In the second paragraph, the word "coined" most nearly means —$q$, $q$["invented and put into use", "translated out of another European language", "attacked in the popular press of the day", "borrowed from a much older written source"]$q$::jsonb, 0, $q$["נכון. המשפט מתאר יצירת מונח חדש לתופעה, ולכן 'coined' פירושו טבע והכניס לשימוש.", "לא נכון. המילה אינה עוסקת בתרגום משפה אחרת.", "לא נכון. הפסקה מתארת התלהבות מהאמנות היפנית, ולא התקפה עיתונאית.", "לא נכון. המילה מציינת מונח חדש, לא שאילה ממקור עתיק."]$q$::jsonb, $q$vocab_in_context$q$, $q$anchor$q$, $q$["By the 1870s critics had coined the term japonisme"]$q$::jsonb, $q$shabbat batch E1, passage=ukiyo-e-europe, q5$q$, 5, true);
  end if;
end $$;